### ISSUE TITLE
what's terminal theme do you use ?

### ISSUE THREAD

**Issue by Restry** [vadimdemedes/ink#10]
hi @vadimdemedes  
looks your mac terminal theme it's very nice in the readme.md . 
would you tell me what's your theme ?

thanks :)

**Comment by sindresorhus** [comment]
It's [Hyper](https://hyper.is) with the [Pure](https://github.com/sindresorhus/pure) prompt and the [Snazzy](https://github.com/sindresorhus/iterm2-snazzy) theme.

**Comment by Restry** [comment]
wow it's awesome :)  thanks
