### ISSUE TITLE
Calling renderString with an array of strings

### ISSUE THREAD

**Issue by larsgw** [vadimdemedes/ink#103]
To [`cli-columns`](https://www.npmjs.com/package/cli-columns)nify my output, I used the `StringComponent`/`renderString` pattern from e.g. `Indent`. However, the `children` aren't passed as an array, I noticed. Is the recommended pattern in this case the following?

```js
class Columns extends Component {
  render () {
    return columns(this.props.children.map(renderToString))
  }
}
```

I think it does the same under the hood, but it feels a bit like a hack. The other workaround *is* more of a hack though, so this is probably better.

**Comment by vadimdemedes** [comment]
I recommend using Ink 2 beta (https://github.com/vadimdemedes/ink/tree/next), where you can use `<Box>` component. Ink 2 supports flexbox layout, so instead of using `cli-columns` you can use:

```jsx
<Box>
  <Box flex={1}>
	A
  </Box>

  <Box flex={1}>
	B
  </Box>
</Box>
```

And "A" and "B" will be on the same line, taking 50% of available space each.

**Comment by larsgw** [comment]
Oh, so that's where those feature requests went :slightly_smiling_face:. Thanks for the info, will look into it!
