### ISSUE TITLE
dynamic children break div

### ISSUE THREAD

**Issue by maticzav** [vadimdemedes/ink#109]
Hey 👋,

I have captured two samples of the problem as I couldn't find the origin of the error besides the fact that it has to be connected with `children` somehow. I have made an "infinite scroll" component which adapts the mask as you move up and down but there seems to be a rendering problem as with one case certain items flicker. I am using `div` to wrap all the children but it works all the same with `Box` probably due to the implementation of `Box`.

If I use the following code the items flicker;

```ts
return <div>{renderedItems}</div>
```

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3924224/48857872-3b561f80-edba-11e8-8611-b418d516ab79.gif)

However, if I add a simple text or `Color` it works fine.

```ts
return (
  <div>
    <Color rgb={[0, 255, 255]}>{`${renderedItems.length}`}</Color>
    {renderedItems}
  </div>
)
```

![with_string](https://user-images.githubusercontent.com/3924224/48857805-08ac2700-edba-11e8-9154-46c958fecfef.gif)

You can find a reproduction [here](https://github.com/maticzav/emma/blob/master/packages/emma/src/components/InfiniteScroll.tsx). I hope this helps you with the release of the next version 🙂

**Comment by vadimdemedes** [comment]
Shouldn't be a problem anymore with Ink 2, but please let me know if it's still there.
