### ISSUE TITLE
Example on how to use without JSX

### ISSUE THREAD

**Issue by nmehta6** [vadimdemedes/ink#11]
I am curious if there is a way to avoid a transpiler since I like to rely on node's native support for new syntax.

**Comment by sindresorhus** [comment]
You only have to transpile the JSX. You don't have to transpile any of the other syntax.

**Comment by xdave** [comment]
@nmehta6  It has the same API as `React.createElement()`.  Just call `h()` instead.   See here: https://facebook.github.io/react/docs/react-without-jsx.html

**Comment by nmehta6** [comment]
@xdave Thank you!
