### ISSUE TITLE
Bold text inline?

### ISSUE THREAD

**Issue by bestguy** [vadimdemedes/ink#119]
I'm attempting to make a word in the middle of line bold, but <Color /> seems to add line breaks?

    <div>
      I am <Color bold>bold</Color>, hello world.
    </div>

Output:

```
I am
bold
, hello world.
```

What is the correct way to accomplish this?

**Comment by lucasconstantino** [comment]
Having the same issue... Text and Color both use Box underneath, but even using chalk directly gives me this problem. I solved it by wrapping everything in a Box component - which uses flex-box for internal layout, thus fixing the issue.

**Comment by bestguy** [comment]
Ah thanks, let me try that workaround

**Comment by bestguy** [comment]
Yes this works, thank you!

```
      <div>
        <Box>Hey, hey mama, said the way you <Color bold>move</Color>,</Box>
        <Box>Gonna make you <Color bold>sweat</Color>, gonna make you groove.</Box>
      </div>
```

Leaving issue open as unsure if this is intentional or a bug.

**Comment by lucasconstantino** [comment]
Honestly, if that's intentional it it definitely confusing and missing in the docs...

**Comment by vadimdemedes** [comment]
`<div>` or `<span>` shouldn't be used with Ink 2, that's why all code examples and mentions of them are removed from the readme - https://github.com/vadimdemedes/ink/tree/next. Use `<Box>` every time you think to use a `<div>` ;)

**Comment by vadimdemedes** [comment]
Also, keep in mind that every `<Box>` is a flexbox container, same as `<div style="display: flex">` in the browser.

**Comment by lucasconstantino** [comment]
@vadimdemedes we got that. But, it really seems odd that the default layout behavior of a `Color` component is that of a block element, not that of an inline element.

**Comment by vadimdemedes** [comment]
It's not the default layout behavior of `<Color>`, parent container decides how children are laid out. If you'll have this sort of markup, all text will be on one line:

```jsx
<Box>
	This is <Color green>awesome</Color>
</Box>
```

**Comment by lucasconstantino** [comment]
I got the point. Make sense, really. Maybe this should be better documented, though. I'm heavily using `ink` right now, so perhaps I'll make some documentation pull-requests ;)

By the way: v2 is way better, generally speaking.

**Comment by vadimdemedes** [comment]
I will go through documentation again and see if I missed anything, thanks! Glad you like v2, let me know if you run into any issues!

**Comment by bestguy** [comment]
Thanks for the update and info
