### ISSUE TITLE
Screen does not clear properly if terminal lines wrap

### ISSUE THREAD

**Issue by zkat** [vadimdemedes/ink#126]
When a component has a line that wraps, refreshing doesn't seem to work properly on rerender.

Repro steps:

1. `git clone https://github.com/npm/libpickupdates && cd libpickupdates`
2. `git checkout bed8908`
3. `npm i && npm run build`
4. `node index.js`
5. Move around with arrow keys, press spacebar, etc, in the update picker

See gif:

![kapture 2019-02-18 at 11 57 30](https://user-images.githubusercontent.com/17535/52973973-d0929100-3374-11e9-93d1-222ae29a857b.gif)

**Comment by vadimdemedes** [comment]
That's actually fixed already, but didn't release it yet. I'm going to address other issues you've pointed out and then release it all at once :) Hope to get it all sorted out in a few hours!

**Comment by zkat** [comment]
bugs that are already fixed are the best kinds of bug. Thanks, @vadimdemedes!

**Comment by vadimdemedes** [comment]
Released `2.0.0-13` and tested `libpickupdates` with it, seems to be ok now!
