### ISSUE TITLE
Allow multiple top-level components

### ISSUE THREAD

**Issue by sindresorhus** [vadimdemedes/ink#13]
So we can get rid of the annoying `<div>` wrapping requirement.

**Comment by vadimdemedes** [comment]
While it's still a requirement to pass a single component to `render()` (the top-most component):

```jsx
render(<Root/>);
```

You can skip `<div>` and `<span>` when returning children from component's `render()`:

```jsx
class Test extends Component {
  render() {
    return [
      <A/>,
      <B/>,
      <C/>
    ];
  }
}
```

Or you meant support passing multiple components initially to `render()`?

```jsx
render([<A/>, <B/>]);
```

**Comment by sindresorhus** [comment]
I meant all cases. Would like to be able to do `render(<A/><B/>);`. In a CLI app you usually glue components together in a final output.

**Comment by brigand** [comment]
@sindresorhus that's invalid syntax, babel won't compile it. It's like `render(h(A)h(B))`. Passing an array is a valid option.

**Comment by sindresorhus** [comment]
@brigand I had imaged that it could compile to something like `render(h(Wrapper))` of which `Wrapper` contained `A` and `B`, but I guess an array would work too.

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/vadimdemedes/ink/issues/46
