### ISSUE TITLE
[v2] ^C during React state update triggers warning

### ISSUE THREAD

**Issue by zkat** [vadimdemedes/ink#130]
Every now and then, when I ^C, I've started getting this message after updating to `2.0.0-16`.

#### Repro Steps:

1. clone `npm/libpickupdates`
2. `cd libpickupdates && npm i && npm run build`
3. `node index.js`
4. Try to ^C ONCE during `checking dependency updates` phase.
5. Repeat until the warning is logged. It doesn't take too many tries to get it.

#### Result

<img width="693" alt="screen shot 2019-02-20 at 09 38 21" src="https://user-images.githubusercontent.com/17535/53112450-132ea780-34f4-11e9-8f90-40fb31467748.png">

**Comment by vadimdemedes** [comment]
Interesting, it should unmount and let the process exit on Ctrl+C. Any chance you have a timer/event listener/async op that doesn't get cleaned up in `componentWillUnmount()`?

**Comment by zkat** [comment]
@vadimdemedes Ah! Yes, this makes sense. I'm using `setTimeout()` and that's probably what's triggering this. Sorry for the trouble! I'll close this ticket now, since I'm pretty sure I understand what's going on now. <3

p.s. thanks for the update yesterday. Things are working _wonderfully_.

**Comment by vadimdemedes** [comment]
No worries! Glad to hear it's working great :) I was waiting until you confirmed everything was smooth, and now I think Ink 2 is ready for the official release!

**Comment by zkat** [comment]
Looking forward to it! I'll keep filing issues as I find them. Very excited to show off all this work once we get it into npm, too :D
