### ISSUE TITLE
[v2] re-rendering devours previous lines?

### ISSUE THREAD

**Issue by zkat** [vadimdemedes/ink#131]
This only seems to happen on Hyper for me, when using tmux with a log line and not all the time, but I managed to get a recording of it, and my `npm pick-updates` npm branch seems to reproduce it for me fairly often.

#### Repro Steps

1. Get Hyper and tmux
1. `git clone https://github.com/npm/cli && cd cli`
2. `make link`
3. `npm pick-updates`
4. Move your cursor around.

#### Results

![kapture 2019-02-20 at 11 42 23](https://user-images.githubusercontent.com/17535/53119787-19794f80-3505-11e9-9ac4-feb0bd6aba49.gif)

**Comment by vadimdemedes** [comment]
Didn't see that before, will check it out today!

**Comment by vadimdemedes** [comment]
Reproduced this after resizing Hyper, it seems Hyper doesn't wrap terminal output correctly as you resize the window.

**Comment by vadimdemedes** [comment]
I was unable to fix it yet, but I do have some ideas that I'll try out tomorrow.

**Comment by vadimdemedes** [comment]
It seems I'll have to implement own wrapping of terminal output. I've tried `wrap-ansi` and `terminal-kit`, but no luck. If you know of any other packages that wrap output while handling ANSI escapes, please send me a link!

**Comment by vadimdemedes** [comment]
After implementing 3 different functions for wrapping terminal output, I decided to try to patch `wrap-ansi` itself: https://github.com/chalk/wrap-ansi/pull/29. It still has one issue left to fix, but I thought it would be useful to give you an update and a way to track progress of this issue.

**Comment by zkat** [comment]
Thanks a lot for looking into this! Hopefully they'll land your patch soon 💚

**Comment by vadimdemedes** [comment]
Fixed in 2.0.0-17!
