### ISSUE TITLE
[v2] Congratulations!

### ISSUE THREAD

**Issue by zkat** [vadimdemedes/ink#135]
No issues here but I wanted to send you some huge congrats on getting v2 out! It was some awesome, hard work, and I'm looking forward to seeing all the amazing things that get created with this. This is a huge step forward for command line UIs!
✨ 🚀 ✨

**Comment by vadimdemedes** [comment]
Thank you so much! 🎉 I'm extremely excited to see `npm pick-updates` command be powered by Ink, can't wait to check it out live!

P.S. I did a quiet release yesterday, but I'm going to "officially" announce it this week with a blog post and fireworks 😆 Also going to publish `ink-testing-library` today + migration guide from Ink 0.x, then should be good to go!

**Comment by zkat** [comment]
Excellent. If you DM me on twitter when you announce it, I'll give you some RTs and attention on there for it 👍

**Comment by vadimdemedes** [comment]
That'd be great, thank you!

**Comment by codyaverett** [comment]
I'm extremely excited about this too!  Great work @vadimdemedes !!!

**Comment by vadimdemedes** [comment]
Thank you @codyaverett! :)

**Comment by LitoMore** [comment]
An awesome package for CLI tools! Good work @vadimdemedes !

**Comment by vadimdemedes** [comment]
Thanks @LitoMore!
