### ISSUE TITLE
React Hooks

### ISSUE THREAD

**Issue by sindresorhus** [vadimdemedes/ink#137]
I'm opening this issue so we can discuss how Ink could take advantage of [React Hooks](https://reactjs.org/docs/hooks-intro.html).

For example, maybe `useStdin()` instead of `<StdinContext>`?

**Comment by jedahan** [comment]
```js
const useKeyHandler = keyHandler => { const { stdin, setRawMode } = useContext(StdinContext) useEffect(() => { setRawMode(true) stdin.on('data', keyHandler) return () => { stdin.off('data', keyHandler) setRawMode(false) } }, [stdin, setRawMode]) } 

useKeyHandler(data => { if (data === 's') setSyncing(syncing => !syncing) if (data === 'p') setCreature(ascii()) if (data === 'q') process.exit(0) })
```

**Comment by sindresorhus** [comment]
@jedahan I think you meant to comment on #138.

**Comment by jedahan** [comment]
What would useStdin expose ideally, beyond something like `const { stdin, setRawMode } = useContext(StdinContext)` ?

**Comment by vadimdemedes** [comment]
In `2.5.0` `useApp`, `useStdin` and `useStdout` hooks were added.

**Comment by mAAdhaTTah** [comment]
I have a `useExit` hook for a project I'd be willing to upstream:

```ts
import { useEffect } from 'react';
import { useApp } from 'ink';

export class ExitError extends Error {
  public code: number;

  constructor(code: number, message?: string) {
    super(message);
    this.code = code;
  }
}

export const useExit = (error?: Error) => {
  const { exit } = useApp();

  useEffect(() => {
    exit(error);
  }, [exit]);
};
```

Don't know if the `ExitError` class is something you want or not, but it enables the code that runs the CLI to set the process's exit code.

Happy to PR this if you want it.

**Comment by vadimdemedes** [comment]
I don't think there's a benefit to having `useExit` when `useApp` exposes the same functionality via `exit` function.

**Comment by mAAdhaTTah** [comment]
Fair. This issue might be worth closing now that the first batch is in.
