### ISSUE TITLE
Warnings are printed when testing an Ink component

### ISSUE THREAD

**Issue by sindresorhus** [vadimdemedes/ink#139]
```
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
```

According to @vadimdemedes:

> It’s from React actually. I don’t know how to make it forget about previous Ink reconciler instances. Because in tests you create a new Ink instance in every test, which creates a new React reconciler instance. And React apparently keeps track of context providers, but this conflict happens. Even if tests are run serially, it still complains. I tried unmounting between tests, but didn’t help. I don’t know how to clean up its cache or whatever to make React forget that this context was used before.

**Comment by mAAdhaTTah** [comment]
Has there been any outreach to the React team for insight?

**Comment by vadimdemedes** [comment]
There are issues already opened (and fixed) in React's repo: https://github.com/facebook/react/issues/13150 and https://github.com/facebook/react/issues/13177. Just need to figure out how to bring the fix to Ink. If you would be willing to work on that, any help is appreciated!

**Comment by vadimdemedes** [comment]
I digged into React's source code and found that React only checks for multiple renderers in development mode, so executing Ink app with `NODE_ENV=production` removes that warning. That's just a workaround though, not a solution. I'm yet to figure out what it is.

**Comment by vadimdemedes** [comment]
I think I found a React bug 😮React tracks if the same context is rendered more than once by assigning `_currentRenderer = {}` to it. Problem is, it doesn't clear that property when context is no longer used (on unmount, for example). So when you `render()` again and use the same context, even with a fresh reconciler, containers, etc, it still thinks that context is being used. For example (pseudo-code):

```js
const Context = React.createContext();
Context._currentRenderer; //=> undefined

const {unmount} = render(<Context.Provider>...</Context.Provider>);
Context._currentRenderer; //=> {}

unmount();
Context._currentRenderer; //=> {}, but should be undefined
```

I will open an issue on React's repo tomorrow.

**Comment by vadimdemedes** [comment]
Interestingly, it doesn't seem to affect any of React's behavior, this check only exists to output that `Detected multiple renderers concurrently rendering the same context provider` warning.

**Comment by vadimdemedes** [comment]
Update: tried reproducing it with react-dom and I couldn't get the same warning message, however I did confirm that React isn't clearing `_currentRenderer` of the context. This led to another interesting discovery - react-dom doesn't create a new reconciler instance for each container node (separate app), like Ink does. Instead, react-dom implements `getRootHostContext` reconciler method, which allows to use one reconciler for multiple containers (apps). I assume if Ink implemented it the same way, this warning would disappear. I will get on it this week.

**Comment by vadimdemedes** [comment]
Submitted https://github.com/vadimdemedes/ink/pull/170 to fix this. I would appreciate if anyone tried it out with their Ink apps to see if there are any regressions, thanks!
