### ISSUE TITLE
Suggestion: create-ink-app

### ISSUE THREAD

**Issue by gc** [vadimdemedes/ink#143]
a "create-ink-app" CLI application, made by ink, seems pretty fitting - and would be very useful I think in instantly having a project setup without having to setup babel/etc. For example, this is definitely a cool project that a lot of people are having a look at, if they could instantly have an example running on their machine it would be nice.

It could also serve as an example of a fairly complex app made with ink, showing people how to structure things, etc

**Comment by SimenB** [comment]
There is https://github.com/vadimdemedes/generator-ink-cli

Having one that works with `npm init` and `yarn create` would be cool, though

**Comment by vadimdemedes** [comment]
@SimenB I'm actually planning to deprecate it in favor of having `create-ink-app`! Was meant to create an issue about it, but @gc beat me to it!

**Comment by yestoall** [comment]
i need that to make babel work in cli

any working environment sample test?

**Comment by zimme** [comment]
Name suggestion here, `create-react-cli`, it would compliment `create-react-app` quite well i think.

**Comment by LitoMore** [comment]
We need a **new CLI library** or a **sub-command** for create an ink component.

For the ink component, we don't need add `ink` and `react` to the `dependencies`, put them to the `devDependencies` just be OK.

Like this: https://github.com/LitoMore/ink-color-pipe/blob/master/package.json

**Comment by vadimdemedes** [comment]
It's out now! https://github.com/vadimdemedes/create-ink-app
