### ISSUE TITLE
Suggestion: add prettier

### ISSUE THREAD

**Issue by thebuilder** [vadimdemedes/ink#144]
It's not that i want to start the whole **space** vs **tab** debate, but because all the examples are using tab for indentation, trying to get an understanding of the code is pretty hard when viewed on mobile.

![img_4a38707ec072-1](https://user-images.githubusercontent.com/3764345/53954527-c1327800-40d6-11e9-8284-bbe3ed30ba34.jpeg)

Adapting [Prettier](https://prettier.io/) would be a good solution for this, since it can format both your source code and the markdown files. Combine it with a [precommit](https://prettier.io/docs/en/precommit.html) hook, and it will also make it much easier to keep a consistent code style between contributors.

**Comment by sindresorhus** [comment]
> but because all the examples are using tab for indentation, trying to get an understanding of the code is pretty hard when viewed on mobile.

Report it to GitHub. They are the ones setting the tab size to an unreadable width (8).

> Adapting Prettier would be a good solution for this, since it can format both your source code and the markdown files.

I don't see how this would help the readmes on mobile. We would still use tab indentation.

**Comment by thebuilder** [comment]
Fair enough - you could set Prettier to format only the `.md` files with space indentation, and keep tabs in source files.

**Comment by peritpatrio** [comment]
> Report it to GitHub. They are the ones setting the tab size to an unreadable width (8).

This is (at least nowadays) possible from the settings: 

https://github.com/settings/appearance#tab-size-heading

**Comment by zkr128** [comment]
@peritpatrio what about the default public pages without user session?
Does [npmjs.com/package/ink](https://www.npmjs.com/package/ink) also have tab settings on the package pages with user session? What about public pages without user sessions there?

<img src="https://github.com/vadimdemedes/ink/assets/106959015/227b8486-b214-402f-bceb-d6eaf136d807" width="300" />

I really can't understand why people get obsesed with such minor things that affecting thousands of other people.

We are right and Github is wrong, NPMJS is wrong, we don't care go tell them that they are wrong.

Maybe we should go and yield at W3 CSS Working Group about the spec standards `tab-size` default value... it shouldn't be `8`, they don't know what they're doing... https://drafts.csswg.org/css-text/#tab-size-property

Like it will hurt some "ego" if spaces used for the documentation only and tabs for the actual source code.
