### ISSUE TITLE
Create quick start, working boilerplate repository for newcomers

### ISSUE THREAD

**Issue by kutsan** [vadimdemedes/ink#15]
Like https://github.com/gaearon/react-hot-boilerplate.

**Comment by vadimdemedes** [comment]
Agree, this would be useful.

**Comment by vadimdemedes** [comment]
Released [generator-ink-cli](https://github.com/vadimdemedes/generator-ink-cli) - a generator for Yeoman to quickly scaffold out a CLI based on Ink. Will add it tomorrow to the readme, just thought you might want to play with it before anyone else :)

**Comment by kutsan** [comment]
Hey, thanks! Looks really cool.

**Comment by kutsan** [comment]
By the way, you may want to show generating the boilerplate with new built-in npx.
Type `npx -p yo -p generator-ink-cli -- yo ink-cli`.

**Comment by vadimdemedes** [comment]
This looks bit painful, tbh. Let's give it time to mature a little, fix bugs, etc.

**Comment by kutsan** [comment]
Yeah, but there is a [issue](https://github.com/yeoman/yo/issues/528) about that. Probably we could just write `npx yo ink-cli` in future.

**Comment by konsumer** [comment]
Another approach would be to name an npm package `create-ink`, so `npm init ink` will call `npx create-ink` for 0-install initial demo project. You can read more about it [here](https://docs.npmjs.com/cli/init). If you make a `bin` named `create-ink` in that project, that does the actual install, you should be all set.
