### ISSUE TITLE
Use WebAssembly build of Yoga

### ISSUE THREAD

**Issue by alcuadrado** [vadimdemedes/ink#150]
Hi @vadimdemedes! Congrats on shipping v2, it's an amazing project! Thanks for creating it :)

One thing I noticed is that it's startup time takes quite a bit. It takes 150-190ms to run a `require("ink")` in my 2017 MBP.

Using [`time-require`](https://www.npmjs.com/package/time-require) I found that 70% of that time is spent in `node_modules/yoga-layout-prebuilt/yoga-layout/dist/entry-browser.js`, your asm.js build of Yoga. I think this could be improved if Yoga is compiled into wasm.

There's no official way doing that in Yoga, but I found [this build](https://github.com/vincentriemer/yoga-dom), which seems to load 2x faster than the asm.js version. It has no docs, and importing it is an async operation, so it may not be a good fit.

**Comment by vadimdemedes** [comment]
Thank you!

Nice suggestion, I'll see how it works and maybe will integrate it into https://github.com/vadimdemedes/yoga-layout-prebuilt, which Ink uses.

**Comment by apatrida** [comment]
Another WASM build of Yoga: https://github.com/rickbutton/yoga-wasm

**Comment by vadimdemedes** [comment]
Nice, I'll check it out.

**Comment by vadimdemedes** [comment]
Fixed via #550.
