### ISSUE TITLE
Respond and reflow with terminal resize events

### ISSUE THREAD

**Issue by duncanbeevers** [vadimdemedes/ink#153]
Listening to `stdout.on('resize')` is pretty straight-forward, but it looks like the ink renderer is instantiated at a [fixed terminalWidth](https://github.com/vadimdemedes/ink/blob/1aaabc62c819d7f06f1dc12573f008adcd43f92f/src/renderer.js#L25).

Is it feasible to reconfigure the renderer or to create a new renderer in response to terminal size changes?

**Comment by vadimdemedes** [comment]
Yep, it's possible and Ink had it in pre-release versions, but I reverted it because of bugs. Will try it out again.

**Comment by vadimdemedes** [comment]
Fix is in master, going to keep this issue open until Ink 3 release is out.

**Comment by vadimdemedes** [comment]
Ink 3 is out with the fix for this issue included! Read the full announcement at https://vadimdemedes.com/posts/ink-3 :)

**Comment by duncanbeevers** [comment]
Congrats @vadimdemedes !

**Comment by vadimdemedes** [comment]
Thanks @duncanbeevers!

**Comment by gajus** [comment]
This does not appear to work reliably.

Is there a way to manually trigger repaint/recalculation of window size?

For instance, in iTerm, I am using shift+cmd+return to focus/blur pane, and that appears to not recalculate the viewport size.

Either that, or my expectations are wrong.

<img width="2056" alt="Screenshot 2023-06-12 at 5 14 30 PM" src="https://github.com/vadimdemedes/ink/assets/973543/63be7851-dce9-4d0a-8719-2991b9856e6b">

<img width="2056" alt="Screenshot 2023-06-12 at 5 15 47 PM" src="https://github.com/vadimdemedes/ink/assets/973543/75cc09f5-0ca4-460a-8db2-475522ad62f8">

**Comment by gajus** [comment]
CC @vadimdemedes as this is a pretty old issue

**Comment by vadimdemedes** [comment]
@gajus Feel free to open a new issue for this.
