### ISSUE TITLE
Top and bottom padding are stacked

### ISSUE THREAD

**Issue by duncanbeevers** [vadimdemedes/ink#155]
### Bare text – works as expected
```jsx
<Box paddingTop={2} paddingBottom={2}>🍉</Box>
```

```
"\n\n🍉\n\n";
```

### Text node with margins – works as expected
```jsx
<Box marginTop={2} marginBottom={2}><Text>🥝</Text></Box>
```

```
"\n\n🥝\n\n";
```

### Text node case – padding is stacked
```jsx
<Box paddingTop={2} paddingBottom={2}><Text>🥕</Text></Box>
```

```
"🥕\n\n\n\n";
```

**Comment by vadimdemedes** [comment]
Reproduced, investigating.

**Comment by vadimdemedes** [comment]
Ink 3 is out with the fix for this issue included! Read the full announcement at https://vadimdemedes.com/posts/ink-3 :)
