### ISSUE TITLE
Display only last frame when running on CI

### ISSUE THREAD

**Issue by umidbekkarimov** [vadimdemedes/ink#156]
Just migrated my cli app from `ora`+`prompts` to `ink` and found a problem in Travis CI logs: https://travis-ci.com/dcodeteam/stylotron/jobs/184495917

This component https://github.com/dcodeteam/stylotron/blob/master/src/lint/FileLintStatus.tsx renders file details line.

Expected output in non tty environment looks like this: 
<img width="412" alt="Screen Shot 2019-03-13 at 17 24 38" src="https://user-images.githubusercontent.com/4734297/54278709-f0ecee80-45b4-11e9-8d65-26a72b04b776.png">

**Comment by umidbekkarimov** [comment]
Works as expected in Gitlab CI.

<img width="381" alt="Screen Shot 2019-03-13 at 17 37 56" src="https://user-images.githubusercontent.com/4734297/54279365-c439d680-45b6-11e9-8765-6019290edc9e.png">

**Comment by vadimdemedes** [comment]
I'm afraid that's the issue on Travis CI's side, apparently it doesn't handle erasing lines correctly. I remember in https://github.com/avajs/ava we had to write output using regular `process.stdout.write('something')` without `log-update`. One fix for this comes to my mind is to detect CI environment and render only last frame, before CLI exits. @umidbekkarimov @sindresorhus what do you think?

**Comment by umidbekkarimov** [comment]
> One fix for this comes to my mind is to detect CI environment and render only last frame, before CLI exits.

@vadimdemedes I like this idea. Most of the times we need final output in CIs, not the progress. If this fix will provide consistent output between environments - then I'm all for it.

Also it can make easier to build dynamic components (e.g. progress bars, spinners).

**Comment by SimenB** [comment]
Maybe dump all in `Static`, and last frame only if no static component in the tree? Something like that would be required for Jest (so we can render test results as the suites complete)

**Comment by vadimdemedes** [comment]
@SimenB Yep for sure, `<Static>` isn't affected by this issue, since it just writes directly to stdout, without erasing any lines.

**Comment by SimenB** [comment]
Perfect!

**Comment by mAAdhaTTah** [comment]
If you decide to go this route, `is-ci` should be a configurable option so you don't have to support every use case.

**Comment by vadimdemedes** [comment]
Fixed in master via https://github.com/vadimdemedes/ink/commit/92f43933f04f1d40175195a931fe5588885f7c1d, will close this issue when new release is out.

**Comment by vadimdemedes** [comment]
@umidbekkarimov would you be able to test latest Ink via `npm install vadimdemedes/ink` and see if it solves your problem?

**Comment by umidbekkarimov** [comment]
> @umidbekkarimov would you be able to test latest Ink via npm install vadimdemedes/ink and see if it solves your problem?

@vadimdemedes I tried to install `@vadimdemedes/ink` but it's not there https://www.npmjs.com/search?q=vadimdemedes%2Fink

**Comment by SimenB** [comment]
@umidbekkarimov not the `@`, he wanted you to install from github

**Comment by umidbekkarimov** [comment]
@vadimdemedes here logs with latest ink https://travis-ci.com/dcodeteam/stylotron/jobs/188297737, works great!

**Comment by vadimdemedes** [comment]
New release is out - https://github.com/vadimdemedes/ink/releases/tag/v2.1.0 🎆
