### ISSUE TITLE
Support for Box `flexBasis` or `minWidth`

### ISSUE THREAD

**Issue by duncanbeevers** [vadimdemedes/ink#157]
In order to create consistent displays of side-by-side information, it may be useful to have boxes that shrink no smaller than some fixed size.

Without support for overflow behavior like clipping, `width` or `maxWidth` props seem a bit further out-of-reach.

Using a `flexBasis` prop provides similar functionality to a `minWidth` / `minHeight`, and feels less out-of-place than an orphaned `minWidth` with no `width` or `maxWidth` counterparts.

**Comment by vadimdemedes** [comment]
Pushed support for `min-width`, `min-height` and `flex-basis` to `master` branch. Will add `max-width` and `max-height` once Ink implements overflow handling (wrapping) of individual nodes. Also discovered a potential Yoga issue along the way - https://github.com/facebook/yoga/issues/872.

**Comment by vadimdemedes** [comment]
New release is out, which adds support for `flexBasis`, `minWidth` and `minHeight` props - https://github.com/vadimdemedes/ink/releases/tag/v2.1.0 🎆

**Comment by vadimdemedes** [comment]
Want to keep this issue open until https://github.com/facebook/yoga/issues/872 is resolved and `maxWidth`/`maxHeight` are added too.

**Comment by vadimdemedes** [comment]
Closing, since https://github.com/facebook/yoga/issues/872 has been open since 2019, so it's unlikely to get fixed anytime soon.
