### ISSUE TITLE
Why not a react renderer?

### ISSUE THREAD

**Issue by naholyr** [vadimdemedes/ink#16]
Is there a specific reason you re-implement the whole react-like API instead of making it a custom renderer? I think about react-blessed here.
If there is no specific reason, how about making it a custom renderer?

**Comment by vadimdemedes** [comment]
There are multiple reasons:

- I wanted to learn how React's/Preact's diffing works and implement it
- React handles way more than Ink needed to
- I haven't found decent docs on how to make a custom React renderer and I didn't want to wait for Fiber
- I'm a JavaScript developer, that says it all 🤣

**Comment by naholyr** [comment]
Seems legit ;) I'd be interested in making a renderer, I'll try to play
with Ink for that part. Would you be interested in the result or is this
just not the desired direction?

Le mar. 11 juil. 2017 à 19:36, Vadim Demedes <notifications@github.com> a
écrit :

**Comment by vadimdemedes** [comment]
I don't see the good enough reason of dropping the whole work done on Ink and switching to a custom renderer. Hope you understand my reasoning :)

Although, I'd be indeed interested how it could be implemented, so make sure to ping back with the results!
