### ISSUE TITLE
Use exit to pass exit code

### ISSUE THREAD

**Issue by mAAdhaTTah** [vadimdemedes/ink#163]
Would it be possible to pass an exit code to the call to `AppContext`'s `exit` function? Then you'd get the value with `const code = await app.waitUntilExit()` and verify it's correct during testing.

I'd be willing to PR this.

**Comment by vadimdemedes** [comment]
I'm not sure it makes sense to pass exit code, since Ink doesn't actually exit the process via `process.exit(code)`. I think a better version of this would be to reject a promise returned by `waitUntilExit()` if error is passed, for example:

```jsx
<AppContext.Consumer>
	{({exit}) => exit(new Error('Oh no'))}
</AppContext.Consumer>

...
try {
	await app.waitUntilExit();
} catch (error) {
	console.log(error); //=> Error: Oh no
}
```

What do you think?

**Comment by mAAdhaTTah** [comment]
That would work. We could reject the promise with whatever is passed, if something is passed, and the calling code could call `process.exit(code)`.

**Comment by vadimdemedes** [comment]
Unfortunately Ink can't be responsible for calling `process.exit()` as it would interrupt other logic that may be running outside of Ink app. Ink did it before and npm had a problem with it, because they take care of process exiting with their own logic.

If you want to exit with a certain exit code on failure, that'd be fairly easy:

```js
try {
	await app.waitUntilExit();
} catch (error) {
        console.error(err.stack);
	process.exit(1); // <= your custom exit code
}
```

**Comment by sindresorhus** [comment]
Ink users can set [`process.exitCode`](https://nodejs.org/api/process.html#process_process_exitcode) themselves. We could document this as it's not well-known.

**Comment by mAAdhaTTah** [comment]
Yeah, to make it clear, I _don't_ want Ink to call process.exit itself. I _do_ want to provide a way to signal the results of the CLI run, specifically in unit tests, that would allow me to bootstrap & run the app and assert against the results. The error-passing mechanism seems good and I can take a crack at that.
