### ISSUE TITLE
Show a warning when <div> or <span> are used directly

### ISSUE THREAD

**Issue by vadimdemedes** [vadimdemedes/ink#164]
They're reserved for internal use and shouldn't be used directly. Prefer `<Box>`, `<Text>` or `<Color>` instead.

**Comment by LitoMore** [comment]
We could point this out in readme also.

**Comment by vadimdemedes** [comment]
Fixed in master, but will keep it open until Ink 3 is out.

**Comment by vadimdemedes** [comment]
Ink 3 is out! Read the full announcement at https://vadimdemedes.com/posts/ink-3 :)
