### ISSUE TITLE
How was media/demo.svg created?

### ISSUE THREAD

**Issue by mamachanko** [vadimdemedes/ink#167]
Hi, thanks for Ink! How was [`media/demo.svg`](https://github.com/vadimdemedes/ink/blob/master/media/demo.svg) created? It doesn't look like your off-the-shelf [asciicinema](https://asciinema.org/) recording.

**Comment by vadimdemedes** [comment]
You're welcome :) I used https://yarnpkg.com/en/package/svg-term-cli.

**Comment by mamachanko** [comment]
thanks @vadimdemedes

**Comment by mamachanko** [comment]
btw @vadimdemedes is there a `[Slack channel | Spectrum | Gitter | mailing list | .* ]` for the community or to get in touch with you other than GitHub Issues?
