### ISSUE TITLE
Box is not accepting percentages as sizes

### ISSUE THREAD

**Issue by danikaze** [vadimdemedes/ink#176]
In the examples/API is written:
```jsx
<Box width="50%">X</Box>
```
but when trying it, I get this error:
```
Warning: Failed prop type: Invalid prop `width` of type `string` supplied to `Box`, expected `number`.
```

Is it not supported anymore?

**Comment by vadimdemedes** [comment]
It is supported, I just didn't publish a new release. I'm planning to publish one tomorrow.

**Comment by danikaze** [comment]
I see, just saw it in the API docs and wasn't working...
But if you release that would be great!
I'll test it promptly! ^^

**Comment by vadimdemedes** [comment]
You can use latest Ink via `npm install vadimdemedes/ink` btw! Just don't forget to move back to regular installation when you're done testing ;)

**Comment by vadimdemedes** [comment]
I'm going to postpone release until tomorrow, because I've pushed a few big changes and it's late now.

**Comment by vadimdemedes** [comment]
New release is out - https://github.com/vadimdemedes/ink/releases/tag/v2.1.0 🎆
