### ISSUE TITLE
Ink v2.0 Changelog

### ISSUE THREAD

**Issue by brucou** [vadimdemedes/ink#177]
Hi,

I am writing an article on ink, and I was wondering what was the changes (features) brought about by the version 2.0?

**Comment by LitoMore** [comment]
I guess you mean a migration documentation for migrate to Ink 2.

We could add a migration guide for Ink 2 to the readme.

**Comment by brucou** [comment]
No I am really thinking of the additional features you added to the 2.0 vs. the previous release which I saw was the 0.5

**Comment by vadimdemedes** [comment]
I still have it in my todo, will write it up soon.

**Comment by LitoMore** [comment]
@vadimdemedes I think we also need a `How to create an Ink component` guide for Ink 2.

For the Ink component, there are some different with the Ink app (please correct me if I am wrong):

- We should put `ink` and `react` to the `devDependencies`
- We should add `ink` and `react` to the `peerDependencies`

**Comment by vadimdemedes** [comment]
@LitoMore  Agree, that's planned as well.

**Comment by vadimdemedes** [comment]
Will keep it open until I write that 2.0 changelog.

**Comment by ArvinH** [comment]
Hi @vadimdemedes Thanks for this awesome lib, I'd like to upgrade some incompatible components to v2, is there any migration guide I can follow with?

**Comment by vadimdemedes** [comment]
Currently there isn't unfortunately. Is your component open source? Perhaps I could give you some tips on how to migrate it and write the guide as we go.

**Comment by ArvinH** [comment]
Thank you @vadimdemedes, here's the repo I was planning to use https://github.com/maticzav/ink-autocomplete, I'm not the author but I'm more than happy to help to upgrade it.
