### ISSUE TITLE
Add absolute positioning to elements

### ISSUE THREAD

**Issue by danikaze** [vadimdemedes/ink#182]
So, the same as in HTML we have a layout and sometimes we want to display elements over it (i.e. alert or a popup, confirmation dialog, etc.), is it possible to render elements over an existing layout specifying a position of the screen? (i.e. dialog in the middle of the screen over everything else)

**Comment by vadimdemedes** [comment]
There isn't such a feature yet, but I think it's possible with Yoga layout (could be wrong). Do you have specific examples for terminal apps that need this?

**Comment by danikaze** [comment]
Specific example... basically what I said about popups and dialogs.
A fullscreen flex layout (think about a webpage), and sometimes a popup/dialog over it (i.e. yes/no confirmation dialog)
```jsx
return (
  <FullLayoutUi />
  { state.confirmation ? <Popup/> : null }
); 
```

**Comment by KyleAMathews** [comment]
Drag and drop interfaces perhaps?

**Comment by danikaze** [comment]
Well, that would be possible if something allows to draw over anything at an specified position, but I'm not targeting that (yet xD)

**Comment by danikaze** [comment]
So, taking a quick look to yoga, it has [absolute/relative layout](https://yogalayout.com/docs/absolute-relative-layout) but I'm not sure if it's implemented here.
Definitely possible. Going to take a look too.

**Comment by vadimdemedes** [comment]
I meant specific examples in the terminal, not on the web.

**Comment by danikaze** [comment]
Yes, I was referring to a terminal app :P
But I've nothing built yet (due to those limitations).
Would a mockup gif work?

**Comment by vadimdemedes** [comment]
Hm I don't think Ink would be a good fit for that sort of UI. This looks like a better fit for https://github.com/yomguithereal/react-blessed, which uses ncurses under the hood and can easily handle this sort of thing. Ink is intended for simpler, nicer and non-fullscreen UIs (think npm, Jest, AVA, etc etc).

**Comment by dustinlacewell** [comment]
I hope you reconsider

**Comment by vdawg-git** [comment]
Just found https://github.com/infely/react-curse, which looks really cool and has this stuff

**Comment by vdawg-git** [comment]
I switched to tuir, its an active fork and designed for fullscreen TUIs.
https://github.com/max5961/tuir
