### ISSUE TITLE
Avoid calling renderNodeToOutput for each call of Component.render.

### ISSUE THREAD

**Issue by acrazing** [vadimdemedes/ink#183]
I'm writing a terminal game(gomoku) with ink, and I find its performance is poor when I print a `15 * 15` board with `mobx`.

I use mobx to store the focused piece, and then, when any arrow input, all the pieces will rerender, but its output is not changed. But the program is paused, after inspect the cpu profile, I find ink will call `renderNodeToOutput` after any Component updated(call render function).

![image](https://user-images.githubusercontent.com/10029810/56257583-4a3dc580-60ff-11e9-9baf-f89d5e080d87.png)

You can see the source code at <https://github.com/acrazing/gomoku-terminal>.

**Comment by vadimdemedes** [comment]
There's definitely a room for progress in rendering / building layout performance. I can't promise any ETAs, but I'm planning to look into this more soon.

P.S. Nice app!

**Comment by acrazing** [comment]
Perhaps you could consider caching the render result of the component and not re-rendering it to stdout if the render function does not modify the result (I'm just guessing).

**Comment by vadimdemedes** [comment]
This might be possible. Currently Ink doesn't render to output if last output remained unchanged, but it still rebuilds the layout though.
