### ISSUE TITLE
react-native-ink?

### ISSUE THREAD

**Issue by piranna** [vadimdemedes/ink#184]
Does anyone knows of a `react-native-ink` to have React Native apps running in the terminal, similar to how [react-native-web](https://github.com/necolas/react-native-web) is build on top of React components? Or better than that, something like [react-native-dom](https://github.com/vincentriemer/react-native-dom), that have an architecture more alike to standard React Native core (using Yoga layout, that `Ink` already uses, and other alike things)?

**Comment by vadimdemedes** [comment]
I doubt such a thing exists. Also, because of the huge difference between terminal and web/mobile platforms, it doesn't sound likely to happen, in my opinion.

**Comment by piranna** [comment]
I started [ansi-widgets](https://github.com/piranna/ansi-widgets) just with this idea... unluckily I didn't have time to continue it :-( But maybe with `Ink` a faster approach based in something like `react-native-web` does could work :-)

**Comment by vadimdemedes** [comment]
Personally I'm not interested in making something like that, but feel free to experiment with it yourself and then ping us back on your progress.
