### ISSUE TITLE
Add isUserInputSupported property to AppContext

### ISSUE THREAD

**Issue by vadimdemedes** [vadimdemedes/ink#203]
I imagine not everyone is familiar with what raw mode means and what implications are there when it's not supported. To reduce confusion for Ink users, I think we should rename it to `isUserInputSupported`, since that's what it's basically about.

Before:

```
{stdin.isRawModeSupported && <TextInput/>}
```

After:

```
{stdin.isUserInputSupported && <TextInput/>}
```

**Comment by sindresorhus** [comment]
Raw mode is not just about user input: https://en.wikipedia.org/wiki/Terminal_mode

You would have to rename `setRawMode` to `setUserInput` or something too then, which would be weird.

**Comment by vadimdemedes** [comment]
Good point! Basically my intention with this idea is to remove the need to educate people about raw mode and force them to learn what it is. I imagine majority of users just care about receiving user input and I thought abstracting raw mode away would reduce the learning curve. As much as I don't like having multiple things that do one thing, how about adding `isUserInputSupported`, instead of renaming `isRawModeSupported`?

**Comment by sindresorhus** [comment]
👍

**Comment by vadimdemedes** [comment]
Closing, since users won't probably need to interact with `setRawMode` directly, given that we have `useInput` hook now.
