### ISSUE TITLE
🌈 Ink UI

### ISSUE THREAD

**Issue by LitoMore** [vadimdemedes/ink#211]
I'm working on a UI set for Ink, I named it [Ink UI](https://github.com/LitoMore/ink-ui).

### Problem 🤔️

Currently, our [useful components](https://github.com/vadimdemedes/ink#useful-components) are from different developers and they have totally different APIs. I think some of them could reuse each other and easier to understand.

### My goal 🏁

Create a UI set like [ant-design](https://github.com/ant-design/ant-design), but Ink UI is for CLI apps.

I will keep working on Ink UI and migrate more useful components to Ink UI. If you have any idea, please let me know, thanks!

**Comment by vadimdemedes** [comment]
Neat! Keep us posted how it goes.
