### ISSUE TITLE
Missing background color when using hex code

### ISSUE THREAD

**Issue by gc** [vadimdemedes/ink#214]
```jsx
import React, { Component } from 'react';
import { Color, Box } from 'ink';

export default class Counter extends Component {
	render() {
		return (
			<Box>
				{[1, 2, 3].map(num => (
					<Box key={num} flexDirection="column" paddingRight={1}>
						<Color bgHex={'#fff'} hex="#000">
							X
						</Color>
						<Color bgHex={'#fff'} hex="#000">
							X
						</Color>
					</Box>
				))}
			</Box>
		);
	}
}
```

Outputs:
![image](https://user-images.githubusercontent.com/30398469/61171315-3f3ce900-a5b9-11e9-8ef2-78660f428840.png)

It seems like the first column always has no color, is this a bug or am I making a mistake somewhere? The issue seems to arise from the outer `<Box>` component

I tested on multiple terminals (powershell, cmd, git bash) and found the same issue.
Versions:
ink: 2.3.0
react: 16.8.6
nodejs: 10.16.0

**Comment by vadimdemedes** [comment]
I reproduced your issue and it seems to be some issue with using hex colors. I swapped `<Color bgHex="#fff" hex="#000">` with `<Color bgWhite black>` and it renders as you would've expected. I would recommend using that as a workaround for now.
