### ISSUE TITLE
ES6 Imports with create-ink-app

### ISSUE THREAD

**Issue by illusaen** [vadimdemedes/ink#215]
Hey all,

So I'm pretty new to the React world (about a years' worth of experience with React Native); I've mostly stayed in the C-like or interpreted language families. I decided to start working on a little side project involving writing a console telnet client with Ink, but I'm having issues breaking out components with the default app made by create-ink-app. To be specific, I'm running into what I guess are babel issues.

I've run the gamut of issues, from "unexpected token export", to "unexpected token <", to import not working because of "unexpected identifier". Any ideas?

**Comment by maurer2** [comment]
Hello, you need to use importJsx to import a child component, e.g. 
```
import importJsx from 'import-jsx';

const ComponentName = importJsx('./ComponentName');
```
