### ISSUE TITLE
<Box> default wrapping behavior

### ISSUE THREAD

**Issue by benfletcher** [vadimdemedes/ink#216]
The docs are somewhat unclear on <Box>'s default wrapping behavior:

> textWrap
> 
> Type: string
> Values: wrap truncate truncate-start truncate-middle truncate-end [nowrap]
> [Default: nowrap]
> 
> This property tells Ink to wrap or truncate text content of <Box> if its width is larger than container. If wrap is passed, Ink will wrap text and split it into multiple lines. If truncate-* is passed, Ink will truncate text instead, which will result in one line of text with the rest cut off.
> 
> ~Note: Ink doesn't wrap text by default.~

I don't see "doesn't wrap" in the list of options -- is that 6th behavior that isn't explicitly selectable? In my testing it seems to truncate but without ellipses.

Should the default behavior have a name and be selectable? Since `Box` is so important to layouts, a very clear API and well-defined behavior is important. 

Alternatively splitting the option up into two -- wrap: (boolean, default false) and truncate: {start/middle/end, default end} would also be a possible, but breaking, approach.

Just adding a named "nowrap" behavior and identifying it as the default would be non-breaking. As proposed in the text above in brackets.

**Comment by vadimdemedes** [comment]
Hm, where did you copy pasted this quote from? Here's what we have in readme:

> ##### Wrapping
>
> ###### textWrap
>
> Type: `string`<br>
> Values: `wrap` `truncate` `truncate-start` `truncate-middle` `truncate-end`
>
> This property tells Ink to wrap or truncate text content of `<Box>` if its width is larger than container. If `wrap` is passed, Ink will wrap text and split it into multiple lines. If `truncate-*` is passed, Ink will truncate text instead, which will result in one line of text with the rest cut off.
>
> *Note:* Ink doesn't wrap text by default.

Note the last line, `<Box>` doesn't wrap text by default. I just confirmed this by using `<Box>{'test'.repeat(100)}</Box>`. If you're seeing different results, could you post how to reproduce them?

**Comment by benfletcher** [comment]
Re-reading my post I can see it was confusing. The "quote" was partially a quote and partially a suggested change, with the brackets the change.

I agree, the default is no wrapping, but a different kind of no wrapping than available with any of the defined options. I think the default behavior should have a name, be explicitly selectable and be defined. Nowhere is the default behavior's difference from the other options explained.

Sorry for confusion and hope this is more clear.

**Comment by vadimdemedes** [comment]
Ah, I see what you mean now. I will make note to explain `textWrap` better in the readme. Thanks!

**Comment by vadimdemedes** [comment]
Ink 3 is out! Read the full announcement at https://vadimdemedes.com/posts/ink-3 :)
