### ISSUE TITLE
<Colors> causes a newline

### ISSUE THREAD

**Issue by JureSotosek** [vadimdemedes/ink#217]
Before `ink@2.1.0`, three `<Color>` elements one after another would render in a single line.

After and including in `ink@2.1.0`, three `<Color>` elements one after another render in three lines.

This caused, for example, my component https://github.com/JureSotosek/ink-divider to start rending wrongly even when using the 2.0.0 carrot version of ink aka `ink@^2.0.0`. I'm not sure if this is intended behaviors or not but it sure did confuse me. The issue: https://github.com/JureSotosek/ink-divider/issues/4

Here is an example of the problem: https://repl.it/repls/SeparateHeartfeltDestination. Try running this as it is and then change ink to 2.1.0 and try running again. You will see the difference.

**Comment by LitoMore** [comment]
@JureSotosek You could use `<Box>` for a workaround. I think it's related to https://github.com/vadimdemedes/ink/issues/195.

**Comment by JureSotosek** [comment]
@LitoMore Did end up doing that.

**Comment by vadimdemedes** [comment]
Actually `<Box>` is a solution, not a workaround. There are no `<span>` or `<div>` elements in Ink. We'll have a warning when they're used soon, see https://github.com/vadimdemedes/ink/issues/164.
