### ISSUE TITLE
Terminalwidth is off by 1 character on windows.

### ISSUE THREAD

**Issue by wardpeet** [vadimdemedes/ink#218]
It seems like stdout.columns is off by 1 character. It could be an issue with yogalayout on windows. It works perfectly on mac osx.

https://github.com/vadimdemedes/ink/blob/6889f47e5c67210e780c357f0fbb51297a25f5e2/src/instance.js#L21-L23

![terminal picture](https://user-images.githubusercontent.com/11328618/60755580-a40ca800-9fe9-11e9-8cad-4bb48c6f6f04.png)

Component can be found here:
https://github.com/gatsbyjs/gatsby/blob/0e78f563a48092309ba56819c09ed8d398dc8764/packages/gatsby-cli/src/reporter/reporters/ink/components/develop.js#L68-L80

This issue got reported in https://github.com/gatsbyjs/gatsby/issues/15466. I'm happy to help out on a fix for this if you can give me any pointers where to look.

**Comment by vadimdemedes** [comment]
I don't have a Windows machine to test this out myself, but would you be able to write a simple script that logs `process.stdout.columns` and verify it doesn't match the actual column width in your terminal?

**Comment by herecydev** [comment]
Logging `process.stdout.columns` shows 120 on my windows machine which is what powershell terminal is set to by default (at least I haven't adjusted it). Problem still exists unfortunately:

![image](https://user-images.githubusercontent.com/11328618/62066401-1eb39680-b229-11e9-9ec9-24e905e93b7c.png)

**Comment by herecydev** [comment]
![image](https://user-images.githubusercontent.com/11328618/62071447-77d4f780-b234-11e9-9445-0ee0b574fa20.png)

I started an ink project using the `create-ink-app` so we can definitely rule out any downstream projects being the issue. Some further observations: It doesn't matter what character is printed or the width of the terminal, the outcome is the same.

1 ... N-1 characters => a line break => Nth character

**Comment by herecydev** [comment]
Logged upstream https://github.com/sindresorhus/log-update/issues/41

**Comment by wardpeet** [comment]
We probably want to pass `stdout.columns` - 1 like log-update does to yoga-layout.

**Comment by vadimdemedes** [comment]
@wardpeet Oh, I didn't know about that - https://github.com/sindresorhus/log-update/blob/master/index.js#L13-L17!

Would you like to create a PR for it?

**Comment by vadimdemedes** [comment]
@herecydev Hm, so you're saying `log-update` has the exact same issue, even without Ink?

**Comment by herecydev** [comment]
Yes the problematic code is within `log-update` and is not a direct fault of Ink. It would be good to keep this issue open depending on what we can do to fix `log-update`.

**Comment by herecydev** [comment]
By the way I've already created a PR to resolve the issue.

**Comment by herecydev** [comment]
This is fixed upstream, running `yarn ugrade` for yarn or `npm update` for npm should resolve this.
