### ISSUE TITLE
Click Event

### ISSUE THREAD

**Issue by ameerthehacker** [vadimdemedes/ink#220]
I'm looking for something like a button behavior in ink, i.e if I click on a text or item I should get an event trigger is that available in ink?

**Comment by vadimdemedes** [comment]
That's not possible, because there's no clicks in CLIs. I know it's possibly via ncurses (if I'm not mistaken), but that's not something I'd be interested to have in Ink.

**Comment by pfgithub** [comment]
Most terminals have mouse escape codes that can be enabled. An example of implementation in node is [terminal-kit's grabInput function](https://github.com/cronvel/terminal-kit/blob/HEAD/doc/high-level.md#grabinput-options--safecallback-).

**Comment by Ayc0** [comment]
I think this is indeed possible as blessed has a mouse option: https://github.com/chjj/blessed/blob/eab243fc7ad27f1d2932db6134f7382825ee3488/lib/program.js#L570
They are indeed listening to specific escape codes

**Comment by Ayc0** [comment]
I looked a bit at it and this is something that it's enabled by default
according to [this article](https://stackoverflow.com/questions/5966903/how-to-get-mousemove-and-mouseclick-in-bash):
![image](https://user-images.githubusercontent.com/22725671/89209699-1bcb4e80-d5bf-11ea-9a17-2acb8fa10d59.png)

I did a test with `process.stdin.on('data', chunk => console.log(chunk));` after running `echo -e "\e[?1000;1006;1015h"` in my terminal and it worked

blessed is enabling the mouse mode + doing the translation to X,Y coordinates in this file: https://github.com/chjj/blessed/blob/eab243fc7ad27f1d2932db6134f7382825ee3488/lib/program.js#L3084

**Comment by kevinwolfcr** [comment]
@vadimdemedes any plans to implement this sometime?

**Comment by h-sifat** [comment]
I think mouse would be really great. It's not always easy to navigate with keybindings in a complex app.

**Comment by muradbuyukasik** [comment]
It would really be handy for Termux CLI programs on Android

**Comment by undefined-moe** [comment]
Most terminal now supports mouse click events (Termux, VSCode, Windows Terminal, MobaXTerm, ...), and it would be great if click event can be handled. If this feature is not going to be implemented, I wonder if it's possible to know if its possible to get the component at the given position captured by other terminal toolkits, then programmaticly trigger the event.

There are many use cases to simplify user interaction logic in complicated terminal apps:

- For `ink-tab`, click to switch tab;
- For `ink-text-input`, focus on click;
- For `ink-select-input`, simply click a item;

**Comment by vadimdemedes** [comment]
> @vadimdemedes any plans to implement this sometime?

No, no plans to have mouse clicks in Ink.
