### ISSUE TITLE
Add <Newline> and <Spacer> components

### ISSUE THREAD

**Issue by colinking** [vadimdemedes/ink#229]
This question might make zero sense in the context of terminals, but would Ink consider adding support for the break line (`<br/>`) tag?

This would replace the need to use `{'\n'}` for new lines, though CMIIW and there is already a better way to add newlines to text in Ink! Might be that most use-cases should just use `flex`/`margin`/`height`, but that seems to quickly become verbose in my experiences so far.

**Comment by sindresorhus** [comment]
If we decide to add this, which I personally think could be useful, it should be something like `<Newline/>` and not `<br/>` as we also moved away from using `<div>` and `<span>`.

**Comment by vadimdemedes** [comment]
Could you share where do you find a need to use `\n`?

**Comment by vadimdemedes** [comment]
Hey @sindresorhus, curious why do you think a `<Newline/>` component would be useful, since there are margin and padding built in?

**Comment by sindresorhus** [comment]
1. Same reason I still use `<br>` in HTML. I'm lazy. I just want some quick vertical spacing. Padding/margin requires more thinking.
2. https://mxstbr.com/thoughts/margin
3. SwiftUI has a [`Spacer`](https://developer.apple.com/documentation/swiftui/spacer) component (which can have static height too).

**Comment by vadimdemedes** [comment]
Good points!

**Comment by vadimdemedes** [comment]
Added `<Newline>` in https://github.com/vadimdemedes/ink/commit/9f4c6f89088865c59bc84ebcf0bdadfef6606784.

However, not so sure about the usefulness of `<Spacer>`, when there are `alignItems` and `justifyContent` props in `<Box>`. E.g. these are the same:

```jsx
<Box justifyContent="space-between">
  <Text>Left</Text>
  <Text>Right</Text>
</Box>

<Box>
  <Text>Left</Text>
  <Spacer/>
  <Text>Right</Text>
</Box>
```

**Comment by sindresorhus** [comment]
What if you want:

```js
<Box>
  <Text>Left</Text>
  <Spacer/>
  <Text>Right</Text>
  <Text>Right2</Text>
</Box>
```

**Comment by vadimdemedes** [comment]
Good point again. This would require grouping `Right` and `Right2` nodes.

**Comment by vadimdemedes** [comment]
Added `<Spacer>` via https://github.com/vadimdemedes/ink/commit/e8ae2af76ec2b23a0b700f0c153e25579f2bcd3d. Going to keep this issue open until Ink 3 is out.

**Comment by vadimdemedes** [comment]
Ink 3 is out! Read the full announcement at https://vadimdemedes.com/posts/ink-3 :)

**Comment by NSExceptional** [comment]
Looks like `Spacer` doesn't actually add a space if the containing `Box` doesn't have room for it? What's up with that?

**Comment by vadimdemedes** [comment]
Can you open a separate issue with a minimal reproduction of the issue you're describing?

**Comment by NSExceptional** [comment]
@vadimdemedes I completely forgot about my issue above, I'm sorry, can't remember what my issue was exactly. But now I'm back with a new issue (#522) :P
