### ISSUE TITLE
Bug: wrapped text overrides margins when using escape sequences

### ISSUE THREAD

**Issue by colinking** [vadimdemedes/ink#230]
Stumbled into what might be a bug with how Ink handles wrapping text when that text contains certain escape sequences. Not sure if it affects all escape sequences, but I've included an example using the [escape sequences associated with linked text](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) (via [`ink-link`](https://github.com/sindresorhus/ink-link)).

-----

Here's an example of wrapped text + margins working as expected on some standard text:

```jsx
return (
  <Box marginTop={1} marginBottom={1}>
    <Box width={80} textWrap="wrap">
      React for CLIs. Build and test your CLI output using components. It even comes with convenient helpers for wrapping long text! Woot!
    </Box>
  </Box>
)
```

![image](https://user-images.githubusercontent.com/2907397/64932184-1bcd2f00-d7f2-11e9-85b6-85407295f86e.png)

As you can see, there's a single line of margin at the bottom of the output.

-----

Here's an example which includes a link that doesn't wrap. This also works fine:

```jsx
return (
  <Box marginTop={1} marginBottom={1}>
    <Box width={80} textWrap="wrap">
      Check out Ink's <Link url="https://github.com/vadimdemedes/ink">online docs</Link>.
    </Box>
  </Box>
)
```

![image](https://user-images.githubusercontent.com/2907397/64932215-4dde9100-d7f2-11e9-9950-fdf9c205b179.png)

-----

However, once that text overflows, the margin at the bottom is overridden:

```jsx
return (
  <Box marginTop={1} marginBottom={1}>
    <Box width={80} textWrap="wrap">
      React for CLIs. Build and test your CLI output using components. Check out the <Link url="https://github.com/vadimdemedes/ink">online docs</Link>.
    </Box>
  </Box>
)
```

![image](https://user-images.githubusercontent.com/2907397/64932241-69e23280-d7f2-11e9-8896-04a725e443d6.png)

For reference, it also breaks even if the escape sequences aren't part of the wrapped text:

![image](https://user-images.githubusercontent.com/2907397/64932290-b3cb1880-d7f2-11e9-8c26-e14037983be1.png)

**Comment by sindresorhus** [comment]
Ink uses `wrap-ansi` to wrap text. See https://github.com/chalk/wrap-ansi/issues/35.

**Comment by colinking** [comment]
Added the above examples to [`colinking/ink-testing`](https://github.com/colinking/ink-testing), so it can be run like so:

```sh
$ git checkout https://github.com/colinking/ink-testing.git
$ npm i
$ npx ts-node src/wrapping-links.tsx
```

Which produces this:

```sh
$ npx ts-node src/wrapping-links.tsx
Example 1

React for CLIs. Build and test your CLI output using components. It even comes
with convenient helpers for wrapping long text! Woot!

Example 2

Check out Ink's online docs.

Example 3

React for CLIs. Build and test your CLI output using components. Check out the
online docs.

$ 
```

Oddly enough, I'm not able to re-create my earlier examples, so I'm going to have to dig a bit more. 😅 

I believe this is still an issue, but going to close until I've got a recreate-able example :)
