### ISSUE TITLE
Examples of Usage with Oclif

### ISSUE THREAD

**Issue by JakeDawkins** [vadimdemedes/ink#239]
Are there any examples available where Ink is used with [oclif](https://oclif.io)? 

Oclif has some magic that happens in development where it looks at pre-build files to determine what commands are. And when using with ts, where you need to use the `tsx` extension to enable jsx, oclif won't pick up `tsx` files.

Not anything Ink can fix, just curious if there are any examples. I'd rather not use babel if I can help it :)

**Comment by schuchard** [comment]
https://ti.to/egghead-live-online-events/build-custom-cli-tooling-with-oclif-and-react-ink-with-shawn-swyx-wang-2019-11-18/en

**Comment by JakeDawkins** [comment]
Ah, interesting! Thanks for the link @schuchard

**Comment by vadimdemedes** [comment]
@schuchard Oh nice, wasn't aware of it!

@JakeDawkins This sounds like oclif should fix on their end.

**Comment by JakeDawkins** [comment]
In case anyone stumbles upon this in the future, It looks like oclif was having trouble because it was picking up the project's `tsconfig.json` and merging it with its own internal one (what??). So renaming the config something else was able to unblock this from working. Hopefully we'll have a CLI to show as proof soon! :) For now, just a WIP PR 💪 https://github.com/apollographql/apollo-tooling/pull/1697

**Comment by pieroproietti** [comment]
I'm trying to build a little CLI Linux installer using oclif and ink - just started to made the skeleton -  but I can say who mix oclif and ink work, almost for single command applications. Here the code: https://github.com/pieroproietti/camarones

**Comment by gael-boyenval** [comment]
Hey, would be great to have examples using Oclif + Ink... is it in the pipe ?

**Comment by ccdexcom** [comment]
https://github.com/chadian/heroku-festive
It's an oclif plugin but that's more or less the same process as doing it within an oclif cli
