### ISSUE TITLE
Breaking change while removing `emitKeypressEvents`

### ISSUE THREAD

**Issue by jdeniau** [vadimdemedes/ink#243]
Hi @vadimdemedes 

I am maybe late, but as you mentionned here : 
> Ink got rid of emitKeypressEvents usage (4960ff7#diff-57aa11691094c3295e1f9dcbe8432ba2L100), so it's indeed should longer be an issue. Btw, I now realize this may have been a breaking change! Haven't had any reports so far, I assume most people have just used ink-text-input for user input and didn't use keypress events directly.

https://github.com/vadimdemedes/ink/issues/213#issuecomment-538695630

As a matter of fact [ink-tab](https://github.com/jdeniau/ink-tab) is using `keypress` events :smile: 

The documentation is indeed still mentionning the call to `emitKeypressEvent`

What is the recommended way to fix this ? 
I temporary added the call to `emitKeypressEvent` directly in `ink-tab`, but it may be called two times for ink version < 2.4.0 (which does not seems to throw an error by the way).

It may not work with ink in the browser too.

I tried moving to `useInput`, but got stuck as it would require a complete rewrite of ink-tab to use functionnal components.

**Comment by vadimdemedes** [comment]
Ha, yeah sorry about that!

> The documentation is indeed still mentionning the call to emitKeypressEvent

Good catch, I'll remove it.

> What is the recommended way to fix this ?

I think you can keep using `emitKeypressEvents`, because calling it twice shouldn't be an issue.

> It may not work with ink in the browser too.

I wouldn't worry about that, Ink is only intended to be run in Node.js environment.

**Comment by jdeniau** [comment]
@vadimdemedes that's the solution I used thank you.

You can close this when the documentation is up to date (or whenever you want in fact 😉)
