### ISSUE TITLE
textWrap="wrap" unexpectedly truncates long strings

### ISSUE THREAD

**Issue by vladar** [vadimdemedes/ink#245]
Reproducible example:

```js
const React = require("react")
const { Box, Static, render } = require("ink")

const Message = ({ text }) => {
  return (
    <Box textWrap="wrap">
      {" "} {text}
    </Box>
  )
}

const CLI = ({ message }) => {
  return (
    <Box flexDirection="column">
      <Static>
        <Message text={message} />
      </Static>
    </Box>
  )
}

const message =
  "1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ornare elit sit amet lorem rutrum scelerisque.\n"+
  "2 Vivamus id mauris ac nisi tristique mollis id egestas risus. Integer cursus auctor eros, ac tempus velit cursus eu.\n"+
  "3 Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam luctus ornare sollicitudin.\n"+
  "4 Duis finibus ut enim vitae consequat. Curabitur non facilisis erat, at suscipit magna. Phasellus pellentesque pellentesque\n"

render(
  <CLI message={message} />
)

```

Steps to repro:
1. Resize terminal so that wrapping happens
2. Run the example above

Expected result:
```
Full `message` string to be rendered
```

Actual result:
```
Only the first 3 lines are displayed (sometimes 2 when terminal width is too small)
```

The interesting thing is that if we remove `{" "}` part from the message component - it works as expected. Removing `textWrap="wrap"` also helps.

**Comment by milesj** [comment]
I think I'm running into the same issue. Here's 2 examples, the first with `wrap`, the second without it. Note how wide my terminal is yet it still wraps!

<img width="1368" alt="Screen Shot 2020-03-28 at 13 28 28" src="https://user-images.githubusercontent.com/143744/77833117-18e3bd00-70f8-11ea-96e5-41e55a21e86f.png">

**Comment by vadimdemedes** [comment]
Ink 3 is out! Read the full announcement at https://vadimdemedes.com/posts/ink-3 :)
