### ISSUE TITLE
I can't run example code

### ISSUE THREAD

**Issue by szymex73** [vadimdemedes/ink#25]
I copy/pasted example code and tried to use `jsx` npm module to run it, transpile it, I also tried to transpile it using Babel but that didn't work either.
How should I run it?

**Comment by dodekeract** [comment]
Did you set the pragma to `h`?

**Comment by szymex73** [comment]
I did, I tried to run babel again and it worked like after 6 tries

**Comment by TimRChen** [comment]
I meet the same situation..

**Comment by gailingmic** [comment]
how exactly have you fixed this? 
I can't get it to work at all with this setup

`package.json`
```JSON
{
  "name": "inkTest",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "build": "babel index.js --out-file index.transpiled.js"
  },
  "dependencies": {
    "babel-cli": "^6.24.1",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-node6": "^11.0.0",
    "ink": "^0.3.0"
  }
}
```

`.babelrc`
```JSON
{
  "presets": [
    "es2015"
  ],
  "plugins": [
		[
			"transform-react-jsx",
			{
				"pragma": "h",
				"useBuiltIns": true
			}
		]
	]
}
```

**Comment by szymex73** [comment]
My NodeJS version is `v7.10.0`
`npm install --save-dev babel-plugin-transform-h-jsx`
.babelrc
```
{
        "plugins": ["transform-h-jsx"]
}
```
Hope this helps

**Comment by vadimdemedes** [comment]
@TimRChen @gailingmic what error do you get?

**Comment by TimRChen** [comment]
I run the demo successfully by using [https://github.com/vadimdemedes/generator-ink-cli](https://github.com/vadimdemedes/generator-ink-cli). Thanks for the generator. @vadimdemedes

**Comment by vadimdemedes** [comment]
You're welcome, @TimRChen!

**Comment by jaywcjlove** [comment]
@szymex73 example code https://github.com/TimRChen/react-cli

**Comment by vadimdemedes** [comment]
Closing due to lack of response. Feel free to reply here or open a new issue with more details, if anyone's still experiencing problems.
