### ISSUE TITLE
Add `clear` method to clear output

### ISSUE THREAD

**Issue by goliney** [vadimdemedes/ink#252]
I want to clear the screen before exiting.
This is what I tried:
```js
app.rerender(<Box />);
```
But it doesn't work.

If I try to print an empty line with `app.rerender(<Box>{'\n'}</Box>);` it works, but I don't need an empty line.

Could you please give me a piece of advice?

**Comment by vadimdemedes** [comment]
I'll add a `clear` method 👍

**Comment by vadimdemedes** [comment]
Implemented in https://github.com/vadimdemedes/ink/commit/fec1c4d62cdb1b988e967acfe91da007e5dff500, will be released as part of Ink 3.

**Comment by vadimdemedes** [comment]
Ink 3 is out! Read the full announcement at https://vadimdemedes.com/posts/ink-3 :)

**Comment by goliney** [comment]
Oh man, this is huge! I will totally check this out 👍
