### ISSUE TITLE
import statements

### ISSUE THREAD

**Issue by marchingband** [vadimdemedes/ink#253]
how can I use import statements?
your examples in the readme use them, but they don't work for me after using create-ink-app

**Comment by marchingband** [comment]
I've had success with pastel, perhaps mentioning that tool in the ink readme would be helpful

**Comment by marchingband** [comment]
(for those finding this thread)
this tool sets up a tool chain that uses the es6 import syntax we might expect.

https://github.com/vadimdemedes/pastel

**Comment by vadimdemedes** [comment]
`import` syntax isn't related to Ink. Google it and I'm sure you'll find how to use ES6 import statements in Node.js.
