### ISSUE TITLE
Console logs and the <Static> component

### ISSUE THREAD

**Issue by arabold** [vadimdemedes/ink#258]
I've just started using Ink, so I might be overlooking something obvious here. But I'm trying to have  my CLI user interface play nice with my logging components. I would like to see logs dumped on screen above the actual UI itself. Following the documentation I use a `<Static>` component for this. It works perfectly fine as long as I keep all log lines in an array and then render that array within the as follows:
```js
<Box flexDirection="column">
  <Static>{logs.map(log => <LogEntry {...log} />)}</Static>
  <Box>{/* rest of my UI */}</Box>
</Box>
```

But because these are logs, the array can get huge and eventually I will run out of memory. Is there better way to achieve the same behavior? Again, I want the logs to appear above the regular UI and simply scroll out of view eventually while the UI remains. The `Static` component does that but with the caveat of needing an ever growing array.

**Comment by vadimdemedes** [comment]
There's a similar issue open at https://github.com/vadimdemedes/ink/issues/162. My first attempt at solving it fail, will try again soon.

Meanwhile, you can limit the size of `logs` array to only store 100 logs, for example. However, you have to have a ton of logs to run out of memory.

**Comment by arabold** [comment]
Thanks for the update and looking forward to a possible final solution soon. In the meantime limiting the log array size will not work, however, as the Static component only seems to render new lines if the array size increases. Hence my original question if I'm doing something wrong or misunderstand how to use Static.

**Comment by vadimdemedes** [comment]
Could you try adding `experimental: true` option and checking if all items are rendered this time? See https://github.com/vadimdemedes/ink#experimental.
