### ISSUE TITLE
Using features not supported in Node 4

### ISSUE THREAD

**Issue by citycide** [vadimdemedes/ink#26]
ink's `engines` field specifies Node >= 4 while using features unsupported in Node < 6. This includes default & rest parameters and destructuring ( all things I hate to lose when supporting node 4 :laughing: ).

I don't personally use anything but `latest` but some might still use Node 4, so the options I'd bet you're aware of already are:

1. Change the `engines` field and drop support for node 4 ahead of its April '18 EOL.
2. Don't use destructuring or fancy parameters.
3. Transpile before publishing.

I realize ink is < 1.0 but this is a good thing to be aware of.

**Comment by vadimdemedes** [comment]
I think I forgot to change it to `6`, since I didn't want to support 4. Will change, thanks!

**Comment by vadimdemedes** [comment]
Fixed in the new release.
