### ISSUE TITLE
`waitUntilExit` never resolves in Jest

### ISSUE THREAD

**Issue by milesj** [vadimdemedes/ink#267]
I'm unable to test my CLI that uses async rendering and `waitUntilExit` as it never resolves in Jest. Even the most basic example:

```ts
it('does something', async () => {
  function Test() {
    return <Box>Test</Box>;
  }

  await render(<Test />, {
    debug: true,
  }).waitUntilExit();

  expect(true).toBe(true);
});
```

Times out and fails with:

```
Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:
```

I've tried with debug on/off, experimental on/off, different stdin/stdout, and every other combinations, and its always the same timeout.

I'm guessing `unmount` is never called because there is no signal.

**Comment by milesj** [comment]
I got it sort of working with this, which is pretty janky.

```ts
jest.mock('ink', () => {
  const { render, Box, Color, Static } = require.requireActual('ink');

  return {
    Box,
    Color,
    Static,
    render(element, options) {
      return {
        waitUntilExit() {
          try {
            render(element, options);
          } catch (error) {
            return Promise.reject(error);
          }

          return Promise.resolve();
        },
      };
    },
  };
});
```

**Comment by vadimdemedes** [comment]
See docs - https://github.com/vadimdemedes/ink/#waituntilexit, it's not going to trigger until app is unmounted either via [`unmount()`](https://github.com/vadimdemedes/ink/#unmount) or exiting the entire process.
