### ISSUE TITLE
Larger amounts of text don't get removed correctly

### ISSUE THREAD

**Issue by KyleAMathews** [vadimdemedes/ink#274]
Reproduces every time past say 20 lines e.g. I render the text and then when it should be removed, much of it isn't.

You can see this happening at second 47 of my screen recording here https://twitter.com/kylemathews/status/1248723127787388928?s=09

**Comment by vadimdemedes** [comment]
Not sure I understand the issue by looking at the video there, would you be able to publish a minimal reproduction for this or explain how can I reproduce it myself?

**Comment by KyleAMathews** [comment]
https://github.com/KyleAMathews/test-ink

Run `test-ink` and then press enter twice — the longer text won't clear out properly. If you cut down the amount of longer text, then it does clear out.

Is this a built-in terminal limit e.g. if some of the text has gone off-screen? Ah, actually that seems to be it — I shrunk the text size down a ton and then the text was cleared as expected.

I guess this means then I need to calculate how many lines the text to render will take and then limit it to the height of the screen 🤔 

Maybe add some sort of paging capability 🤔

**Comment by KyleAMathews** [comment]
This issue basically https://github.com/vadimdemedes/ink/issues/222
