### ISSUE TITLE
Connect to React Devtools

### ISSUE THREAD

**Issue by KyleAMathews** [vadimdemedes/ink#279]
For debugging & general development, it'd be great if there was some way to connect to the React devtools. It can be hard to figure out what's going on sometimes & the ability to manipulate values live would be 👨‍🍳 💋

**Comment by vadimdemedes** [comment]
Implemented, will ship with Ink 3 :)

**Comment by vadimdemedes** [comment]
Landed in `master` -> https://github.com/vadimdemedes/ink/pull/287. Will keep this issue open until Ink 3 is out.

**Comment by vadimdemedes** [comment]
Ink 3 is out! Read the full announcement at https://vadimdemedes.com/posts/ink-3 :)

**Comment by ParadiseWitch** [comment]
How to connect React Devtool on the Win10? It reminds me "Cannot find the command dev" when I input "dev = true"
![image](https://user-images.githubusercontent.com/37146904/131215367-b3172f97-aa48-4962-918f-97b2a4e1474c.png)
