### ISSUE TITLE
Unexpected display ??

### ISSUE THREAD

**Issue by OuyangQianba** [vadimdemedes/ink#28]
Run the below code
```javascript
import { h, Text, render, Component, span } from "ink"
class Test1 extends Component {
  state = {
    text: ""
  }
  componentDidMount() {
    let number = 0
    setInterval(() => {
      let text = this.state.text;
      number++;
      text += number + "-"
      this.setState({
        text
      })
    }, 100)
  }
  render() {
    return (<Text>{this.state.text}</Text>)
  }
}
render(<Test1 />)
```
When the length of `this.state.text` great then the columns of terminal, the output seams not correct, is it ?
![image](https://user-images.githubusercontent.com/17270099/28759519-0ecf9444-75d1-11e7-8628-89839834e590.png)

The same situation appears on `TextInput` , when the input text more then one line, it was repeated again and again when I typed.

```javascript
class Test extends Component {
  state = {
    value: ""
  }
  render() {
    return (<TextInput value={this.state.value} onChange={(v) => this.setState({ value: v })} />)
  }
}
```

**Comment by sindresorhus** [comment]
@vadimdemedes I think you need to update `log-update` to fix this.

**Comment by OuyangQianba** [comment]
Yes , I had read the source code of ink and log-update and I found that too. I deleted log-update and installed the latest version (2.1.0), the issue disappeared. @sindresorhus  @vadimdemedes

**Comment by vadimdemedes** [comment]
Updated in master, will keep this open until next release is out.

**Comment by vadimdemedes** [comment]
Thanks for reporting, @OuyangQianba.

**Comment by vadimdemedes** [comment]
https://github.com/vadimdemedes/ink/releases/tag/v0.3.1 is out.
