### ISSUE TITLE
Announce to ReasonML binding for Ink

### ISSUE THREAD

**Issue by cometkim** [vadimdemedes/ink#289]
Hi :wave: thank you for making & maintaining this great project.

Not an issue, I wanna let you know I just release [reason-ink](https://github.com/cometkim/reason-ink), a BuckleScript binding for Ink.

https://github.com/cometkim/reason-ink

ReasonML (& OCaml) people can use ink to build a CLI app!

**Comment by vadimdemedes** [comment]
This is amazing! Do you think you'd be able to update these after Ink 3 is out? :)

**Comment by cometkim** [comment]
v3 sounds sweat! I'd love to follow it :)

Right after the v3 released, I will move the existing version into the `ReasonInkLegacy` (or another name) module and build new bindings on top of v3.

**Comment by vadimdemedes** [comment]
Hey @cometkim, Ink 3 is out now, would you be able to update the ReasonML bindings for it? No pressure, totally cool if not :)
