### ISSUE TITLE
Transform component is not available

### ISSUE THREAD

**Issue by p2kmgcl** [vadimdemedes/ink#290]
I tried to use `Transform` component (using ink 2.7.1 on a Typescript project), and there is no `Transform` export on ink module. I checked the `node_modules/ink` directory for the case that type definitions where not updated, but I can't find it, however it appears on the repo:
- https://github.com/vadimdemedes/ink#transform
- https://github.com/vadimdemedes/ink/blob/master/src/components/Transform.tsx

Should it be available?

![Untitled](https://user-images.githubusercontent.com/800645/82294962-3d993a00-99af-11ea-8eff-809d7a9f3f35.png)

![image](https://user-images.githubusercontent.com/800645/82294864-15114000-99af-11ea-8905-3f94ca771276.png)

**Comment by sindresorhus** [comment]
It's not released yet. Like most projects on GitHub, the readme shows what's in `master`, not what's in the latest version.

You want to look at: https://github.com/vadimdemedes/ink/tree/fc1f0c2320e66598c7c5cf72e172070722aab4ef#readme
