### ISSUE TITLE
Issue in rendering big string inside <Text> tag

### ISSUE THREAD

**Issue by Adi2612** [vadimdemedes/ink#293]
I am having an issue with this code

```jsx
import React from 'react';
import {render, Text} from 'ink';

class TestBug extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      renderData: null,
    };
  }
  componentDidMount() {
    let renderData = '';
    for (let i = 0; i <= 100; i++) {
      renderData += '"things are going wrong :/" ' + i + '  ,\n';
    }
    this.setState({ renderData: renderData });
  }
  render() {
    const { renderData } = this.state;
    return <Text> {renderData} </Text>;
  }
}
render(<TestBug />);

```
We will notice  that counting repeat after reaching certain number. the problem is occurring in ink -v 2.7.1  but it's working fine in v 2.4.0 . It means `<Text>` tag is rendering incomplete string first and then print a complete string.-- means printing it twice.

**Comment by vadimdemedes** [comment]
Could you show what's the actual and expected outputs?

**Comment by Adi2612** [comment]
@vadimdemedes  :
*Expected Output* : 
`things are going wrong :/ ${i} ` should be printed 101 times as the for loop runs for 101 times

*Actual Output* : 
`things are going wrong :/ ${i}` is printed more than 101 times as initial part of sequence is rendered twice.

**Comment by vadimdemedes** [comment]
Ah, that has nothing to do with Ink. It's how terminals deal with erasing long content. Ink erases previous output before rendering a new one. If output is taller than height of the terminal, the part of output that's outside the viewport doesn't get properly cleaned up and ends up repeated.

If you need to display a lot of log-like data that's not going to change after you render it, I'd recommend taking a look at `<Static>` component.
