### ISSUE TITLE
Question: Is it possible to try out 3.0.0?

### ISSUE THREAD

**Issue by charlex** [vadimdemedes/ink#294]
Looking to try and use React suspense. #254 

I tried installing from Github, but I'm not sure it has all of the right folders in it.

**Comment by charlex** [comment]
Would it be possible to set up @next or @beta release stream?

**Comment by beaucollins** [comment]
If you want to try it out without a release pushed this _should_ give you `master`:

```
git clone git@github.com:vadimdemedes/ink.git
cd ink
npm install
npm version 3.0.0-dev
npm pack
``

This should produce a file within `./ink` named `ink-3.0.0-dev.tgz`.

Then in your `npm` project:

```
npm install ~/path/to/ink/ink-3.0.0-dev.tgz
```

Your `dependencies` will look something like this:

```json
  "dependencies": {
    "ink": "file:../ink/ink-3.0.0.tgz",
    "react": "^16.13.1"
  }
```

**Comment by beaucollins** [comment]
You can also put that `tgz` up somewhere (like say your GitHub project's files) and use the full URL for it.

Or perhaps even push it to your project's package repository: https://github.com/features/packages

**Comment by charlex** [comment]
Awesome, thank you for helping me figure this out! I've never had to do something similar to this, so again, very appreciative for the help. @beaucollins
