### ISSUE TITLE
Not possible to do display: none on Box

### ISSUE THREAD

**Issue by jvorcak** [vadimdemedes/ink#297]
In the documentation, it says one use `display` property of `Box` element and set it to `none`.

https://github.com/vadimdemedes/ink#visibility

However, no such property is present and I can't hide my elements. Is this a bug or I misunderstood something in the documentation?

<img width="827" alt="Screenshot 2020-06-09 at 18 52 31" src="https://user-images.githubusercontent.com/1083817/84176897-611d4500-aa82-11ea-9a6f-6f1aeece3826.png">

**Comment by sindresorhus** [comment]
It was introduced in https://github.com/vadimdemedes/ink/commit/b51476c7d402208e0112e727ebce990c37dc5ed5 which is not released yet. It will be released with Ink 3 (when it's done).

Like most projects on GitHub, the readme reflects `master` branch. For the latest version, go to the npm page or the tag: https://github.com/vadimdemedes/ink/tree/v2.7.1#readme

**Comment by vadimdemedes** [comment]
Added a note to readme to clarify this.
