### ISSUE TITLE
Handle space key in useInput hook

### ISSUE THREAD

**Issue by elmpp** [vadimdemedes/ink#298]
Hi there, really great library. Thank you.

I'm trying to capture a spacebar press via `useInput()` without success - it's not captured within `key` and the `input` prop is undefined. Have tried hacking within `useInput()` directly but same story - undefined for `data`?

Is there a trick i'm missing?

OSX, iterm terminal.

**Comment by vadimdemedes** [comment]
Hi @elmpp, could you try checking how `data` events look for space keys without Ink (e.g. in a separate standalone script)? Also, what Node.js version are you on? I'm pretty sure space key worked before, maybe it's a regression of some sort.

**Comment by nitsanavni** [comment]
FYI I'm [successfully recognizing space](https://github.com/nitsanavni/mm/blob/table-integration/src/input-map.ts#L20) key by `input === " "`

**Comment by elmpp** [comment]
It wasn't matching the unicode `0020` but does match ` ` as @nitsanavni mentions

Does it make sense adding a it to the `keys` param? (i can PR)

**Comment by vadimdemedes** [comment]
What's `0020`? Could you send a link where I can read more or a reproducible example?

**Comment by elmpp** [comment]
there isn't a bug - i am closing.

As an aside - would you consider a PR to add `key.space`: boolean to `useInput`?

**Comment by vadimdemedes** [comment]
Why not check `input === ' '`? I think `key.space` would be redundant as you can do the same check already.

**Comment by elmpp** [comment]
ok, no worries. Thanks
