### ISSUE TITLE
borderColor for non-double borders

### ISSUE THREAD

**Issue by elmpp** [vadimdemedes/ink#310]
Is there any reason why my terminal (iterm, OSX) would be showing borders as white for all borderStyles except double? I notice there is a test for `round` with color so bit confused 🤷 

```jsx
<Box
      padding={1}
      alignSelf="flex-start"
      borderStyle={'double'}
      // borderStyle={'classic'}
      borderColor={color.hex()}
      marginRight={2}
    >
      <InverseText backgroundColor={color}>{workspace.descriptor.identString}</InverseText>
    </Box>
```

Toggling the commented lines gives:
![Screenshot 2020-06-20 at 19 15 48](https://user-images.githubusercontent.com/864612/85207732-24c3d180-b32b-11ea-9407-2db5ffbb3628.png)

![Screenshot 2020-06-20 at 19 15 30](https://user-images.githubusercontent.com/864612/85207731-2392a480-b32b-11ea-9792-ecefde9282be.png)

**Comment by vadimdemedes** [comment]
Could you try to reduce it to the smallest possible example that reproduces the same issue and share that code with me?

**Comment by elmpp** [comment]
i was double rendering the box which seems to remove the color

**Comment by vadimdemedes** [comment]
Hm, what do you mean?

**Comment by elmpp** [comment]
I [tried to replicate](https://github.com/elmpp/ink-310) with latest version but couldn't repro. Will update if i see again. Thanks
