### ISSUE TITLE
Ink 3 ❤️

### ISSUE THREAD

**Issue by vadimdemedes** [vadimdemedes/ink#311]
Opening this umbrella issue for you folks to test drive pre-release of Ink 3 - https://github.com/vadimdemedes/ink/releases/tag/v3.0.0-0! Latest docs are in [readme](https://github.com/vadimdemedes/ink) and you can install it via:

```
$ npm install ink@next react
```

I haven't migrated any of the 3rd-party components to work with Ink 3 yet, but if you want to migrate a component or two, that's always greatly appreciated! Don't forget to release it as a major version and keep a link to previous docs for those who are still on Ink 2.

Let me know if there are any breaking changes that weren't described in the release notes above. Basically, if anything comes up, just post here and let's talk.

**Comment by Eastonboy99** [comment]
Hello. I am very new to this library but I love it already! I am currently trying to migrate the [ink-select-input](https://github.com/vadimdemedes/ink-select-input) and I am running into this issue:
```
$ C:\Users\user\Documents\Github\ink-select-input\example\node_modules\.bin\ts-node .\index.tsx
C:\Users\user\Documents\Github\ink-select-input\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: ENOENT: no such file or directory, open 'C:/Users/user/Documents/Github/ink-select-input/node_modules/ink/src/reconciler.ts'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at ErrorOverview (C:\Users\user\Documents\Github\ink-select-input\node_modules\ink\src\components\ErrorOverview.tsx:25:25)
    at renderWithHooks (C:\Users\user\Documents\Github\ink-select-input\node_modules\react-reconciler\cjs\react-reconciler.development.js:6036:18)
    at mountIndeterminateComponent (C:\Users\user\Documents\Github\ink-select-input\node_modules\react-reconciler\cjs\react-reconciler.development.js:8570:13)
    at beginWork$1 (C:\Users\user\Documents\Github\ink-select-input\node_modules\react-reconciler\cjs\react-reconciler.development.js:9938:16)
    at Object.invokeGuardedCallbackImpl (C:\Users\user\Documents\Github\ink-select-input\node_modules\react-reconciler\cjs\react-reconciler.development.js:11563:10)
    at invokeGuardedCallback (C:\Users\user\Documents\Github\ink-select-input\node_modules\react-reconciler\cjs\react-reconciler.development.js:11740:31)
    at beginWork$$1 (C:\Users\user\Documents\Github\ink-select-input\node_modules\react-reconciler\cjs\react-reconciler.development.js:15778:7)
    at performUnitOfWork (C:\Users\user\Documents\Github\ink-select-input\node_modules\react-reconciler\cjs\react-reconciler.development.js:14693:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:/Users/user/Documents/Github/ink-select-input/node_modules/ink/src/reconciler.ts'
}
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
If anyone has any thoughts as to why that would be a great help.
My code is here: https://github.com/Eastonboy99/ink-select-input

**Comment by vadimdemedes** [comment]
@Eastonboy99 Fixed via https://github.com/vadimdemedes/ink/pull/313. When you update to `3.0.0-2`, this error should be gone. Thanks for trying it out!

**Comment by vadimdemedes** [comment]
Pushed several more pre-releases, which:
- Add handling of tab, shift+tab, backspace and delete keys in [`useInput`](https://github.com/vadimdemedes/ink#useinputinputhandler-options) hook (https://github.com/vadimdemedes/ink/pull/312 + https://github.com/vadimdemedes/ink/pull/314).
- Fixes rendering of [`<Text>`](https://github.com/vadimdemedes/ink#text) with `undefined` or `null` children (https://github.com/vadimdemedes/ink/pull/315).

Migrated these components today:
- https://github.com/vadimdemedes/ink-text-input (https://github.com/vadimdemedes/ink-text-input/pull/58).
- https://github.com/vadimdemedes/ink-spinner (https://github.com/vadimdemedes/ink-spinner/pull/9).

Also migrated [Emoj](https://github.com/sindresorhus/emoj/) to Ink 3 (https://github.com/sindresorhus/emoj/pull/46).

**Comment by milesj** [comment]
Migrated my CLI to v3 without much issue. Biggest migration is the `Text` changes. Everything else seems to just work. https://github.com/milesj/boost/pull/96/commits/834af7f19b6cab625ce9ca549b29c3400cb77d8b

**Comment by LitoMore** [comment]
Let me help you migrate some [useful components](https://github.com/vadimdemedes/ink#useful-components) to Ink 3.

**Comment by vadimdemedes** [comment]
Thanks @LitoMore and @milesj!

**Comment by vadimdemedes** [comment]
Published [3.0.0-5](https://github.com/vadimdemedes/ink/releases/tag/v3.0.0-5) with a fix for rendering text changes and exiting the app. Oh, and there's a new logo!

<img src="https://user-images.githubusercontent.com/697676/86528273-1939e400-beaf-11ea-8321-1bec939e40da.png" width="240">

**Comment by vadimdemedes** [comment]
Released in [`v3.0.0-6`](https://github.com/vadimdemedes/ink/releases/tag/v3.0.0-6) with a fix for rendering Ink-based app in a TTY-less process. Thanks @jaredLunde and @bartlangelaan!

**Comment by thephilwells** [comment]
This might be more of a "Help me set up my babel config" question, but I can't seem to run Jest tests using `ink-testing-library` since upgrading to Ink 3.

Here's my `.babelrc`:
```json
{
  "presets": ["@babel/env", "@babel/react", "@babel/preset-typescript"],
  "plugins": ["@babel/transform-runtime"]
}
```

Here's my test:
```javascript
import React from 'react'
import { render } from 'ink-testing-library'
import { App } from '../App'

describe('APP', () => {
  it('returns the name of the game', () => {
    // Arrange
    const { lastFrame } = render(<App />)

    // Assert
    expect(lastFrame()).toMatchSnapshot()
  })
})
```

 And here's the app:
```javascript
import React from 'react'
import { render, Text } from 'ink'

export const App = () => {
  return <Text>foo!</Text>
}

render(<App />)
```

I get the following error:
```
 FAIL  src/test/App.test.js
  ● Test suite failed to run

    TypeError: console.Console is not a constructor

      10 | }
      11 |
    > 12 | render(<App />)
         | ^
      13 |

      at Object.patchConsole [as default] (node_modules/patch-console/src/index.ts:36:26)
      at Ink.patchConsole (node_modules/ink/src/ink.tsx:287:37)
      at new Ink (node_modules/ink/src/ink.tsx:95:9)
      at node_modules/ink/src/render.ts:88:9
      at getInstance (node_modules/ink/src/render.ts:126:14)
      at render (node_modules/ink/src/render.ts:86:24)
      at Object.<anonymous> (src/App.js:12:1)
      at Object.<anonymous> (src/test/App.test.js:3:1)
```

Sorry if I'm missing something obvious. Love the project! :heart:

**Comment by vadimdemedes** [comment]
@thephilwells Huh, seems like Jest is patching the global `console` object and forgetting (or doing it on purpose) to assign `Console` class to it. I'm going to push an update to `ink-testing-library` to disable Ink's console patching so that there's no interference between Jest and Ink. Will post back here when done!

Thanks for trying out Ink 3!

**Comment by vadimdemedes** [comment]
Hey @thephilwells, I was wrong, testing in Jest seems to be fine -> https://github.com/vadimdemedes/ink-testing-library/pull/13. Are you using the latest version of Jest?

**Comment by SimenB** [comment]
Jest's custom console does `extends Console`. If it somehow breaks Ink we should fix it in Jest, shouldn't need to work around issues

**Comment by pepperkick** [comment]
Hello,

I was using the Ink `2.7.1` version and migration was pretty easy!

There is this weird issue which I noticed, the `3.0.0-6` flickers a lot more than `2.7.1` when there is any state update. I created a test script to confirm this and indeed it does flicker a lot.

Cli.tsx
```tsx
import React from 'react';
import { App } from './containers/App';
import { render } from 'ink';
import clear from 'clear';

const initialize = () => {
  // Clear terminal
  clear();

  // Render the container
  render(<App />);
}

initialize()
```
App.tsx
```tsx
import React, { Component } from 'react';
import { Box, Text } from 'ink';
import BigText from 'ink-big-text';

interface Props {}

interface State {
  counter: number
}

export class App extends Component<Props, State> {
  state = {
    counter: 0
  }
  
  constructor(props) {
    super(props);

    setInterval(() => {
      this.setState({ counter: ++this.state.counter })
    }, 100)
  }

  render() {  
    return (
      <Box flexDirection="column">
        <BigText colors={["#2196F3", "#212121"]} font="block" text="TEST CLI"/>
        <Text bold>Welcome to Test CLI</Text>
        <Text bold>Counter: {this.state.counter}</Text>        
        <Text bold>End</Text>
      </Box>
    );
  }
}
```

I used Windows Terminal with SSH.

v2.7.1
![ink2](https://user-images.githubusercontent.com/8415891/87399827-995df900-c5d5-11ea-9271-e3826a46f7f4.gif)

v3.0.0-6
![ink3](https://user-images.githubusercontent.com/8415891/87399776-80edde80-c5d5-11ea-8242-8fac171c3a78.gif)

**Comment by vadimdemedes** [comment]
Hey @pepperkick, that looks odd, but I wasn't able to reproduce it on Mac with iTerm 2. I even sped it up to increment every 10ms instead of 100ms and it still wasn't flickering:

![CleanShot 2020-07-22 at 18 40 25](https://user-images.githubusercontent.com/697676/88197444-2c88d580-cc4b-11ea-939f-5c5baa5196d8.gif)


I modified code a bit, I doubt that'll help it, but still:

```jsx
class App extends React.Component {
	constructor(props) {
		super(props);

		this.state = {
			counter: 0
		};
	}

	render() {
		return (
			<Box flexDirection="column">
				<BigText colors={['#2196F3', '#212121']} font="block" text="TEST CLI" />
				<Text bold>Welcome to Test CLI</Text>
				<Text bold>Counter: {this.state.counter}</Text>
				<Text bold>End</Text>
			</Box>
		);
	}

	componentDidMount() {
		this.timer = setInterval(() => {
			this.setState(previousState => ({
				counter: previousState.counter + 1
			}));
		}, 10);
	}

	componentWillUnmount() {
		clearInterval(this.timer);
	}
}
```

**Comment by vadimdemedes** [comment]
> I used Windows Terminal with SSH.

@pepperkick Oh wait, are you running Ink somewhere else and you're SSHed into that machine? That would definitely explain the flickering, because there's latency and you're updating a screen quite often. Could you clarify your setup? Also, have you tried other terminal apps?

**Comment by vadimdemedes** [comment]
> Jest's custom console does extends Console. If it somehow breaks Ink we should fix it in Jest, shouldn't need to work around issues

@SimenB I think it could be something else in @thephilwells's setup, because I've tried running Ink inside Jest an it worked fine -> https://github.com/vadimdemedes/ink-testing-library/pull/13. You are right though, I'll make sure to open an issue in Jest's repo if we confirm the root cause.

**Comment by pepperkick** [comment]
Hey @vadimdemedes, 
Thanks for trying it out!

> @pepperkick Oh wait, are you running Ink somewhere else and you're SSHed into that machine? That would definitely explain the flickering, because there's latency and you're updating a screen quite often. Could you clarify your setup? 

Yes, the application is running on another machine and I am connecting via SSH to that machine to view the output. My end application will be running over SSH most of the time.
Both version 2's and 3's output were in Windows Terminal over SSH.  Version 2's output seems a lot less flickery than version 3 so I did not think latency would have been the cause.

> Also, have you tried other terminal apps?

I tried some other terminals, and it does seem like the issue is only on Windows Terminal over SSH.
putty and vscode (integrated terminal) do not have any flicker while running it over SSH, cmd and powershell over SSH have some flicker but it is manageable. I have only tried version 3 with them though.

I will try some more scenarios and see if there are any more issues like this.
Overall if it's only Windows Terminal being affected then I am fine with it. 

This library is actually really awesome!
Thank You!

**Comment by milesj** [comment]
> To improve developer UX further, Ink 3 intercepts calls to console.log, console.error and other methods to ensure logs are displayed correctly above your app's UI and not interfere with each other. This is necessary, because Ink re-renders your UI all the time, which can overwrite the output from console.log.

OMG yes! I had to do this manually. Love that this is in core 🙏

**Comment by AriPerkkio** [comment]
I believe this is worth adding here so anyone else won't spend an hour for debugging.

If you are seeing those `TypeError: console.Console is not a constructor` errors when testing Ink applications with Jest you'll need to update Jest to v26.6.1. They have recently included constructor to console override: https://github.com/facebook/jest/pull/10502
Everything works flawlessly now.
