### ISSUE TITLE
Stack Trace For Unwrapped Text

### ISSUE THREAD

**Issue by elmpp** [vadimdemedes/ink#317]
I wonder if the same error UI from [this issue](https://github.com/vadimdemedes/ink/issues/288#issuecomment-644976075) could be applied when text isn't wrapped inside `<Text/>`

This is an example of the current UI. When the text is a key; for instance `0` it's very difficult indeed to locate.
![Screenshot 2020-06-27 at 00 01 27](https://user-images.githubusercontent.com/864612/85904702-b50d8500-b809-11ea-8f0e-750904452b5b.png)

There's also a repro on [this branch](https://github.com/elmpp/ink-310/tree/text-error-trace) if required.

**Comment by vadimdemedes** [comment]
I looked into it and Ink doesn't have access to filename/line/column information on where a particular component or text is located. Even though it would certainly be a nice improvement, unfortunately it doesn't seem possible.
