### ISSUE TITLE
Document "Why"

### ISSUE THREAD

**Issue by vadimdemedes** [vadimdemedes/ink#33]
Many people have questions why does Ink exists, why not use blessed/react-blessed, etc. I need to clarify it in the beginning of readme.

**Comment by dave-irvine** [comment]
Hi! I'm also looking for the answer to this question!

I love Ink but I've seen in a couple of Issues you've recommended to use react-blessed for certain 'types' of applications and I'm wondering why this is? I think web-apps map pretty well to the ncurses style interface `blessed` gives you, and I can't really see anything specific about Ink that would stop it working the same way?

It would be great if you could give me some insight why I can't or shouldn't build full-terminal-screen ncurses style apps with Ink?
