### ISSUE TITLE
Throw human readable error when `<Box>` is nested in `<Text>`

### ISSUE THREAD

**Issue by KyleAMathews** [vadimdemedes/ink#337]
Working on a reproduction but tossing the stack trace out. @johno and I have been debugging a problem and boiled it down to this.

![image (4)](https://user-images.githubusercontent.com/71047/88600383-f8366000-d022-11ea-905b-e9cc60b2329e.png)

**Comment by KyleAMathews** [comment]
Ok figured out the reproduction:

```jsx
<Text>*
  <Box>
    <Text>hi</Text>
  </Box>
</Text>
```

**Comment by vadimdemedes** [comment]
I just found out that I mentioned that all text must be wrapped in `<Text>`, but I forgot to mention that `<Box>` can't be inside `<Text>`, similar to React Native. `<Text>` can have only text or nested `<Text>` components inside.

I'll improve the error message for this, thanks for reporting!

**Comment by vadimdemedes** [comment]
Released a human readable error in [3.0.1](https://github.com/vadimdemedes/ink/releases/tag/v3.0.1).
