### ISSUE TITLE
Document built-in <Text> component

### ISSUE THREAD

**Issue by vadimdemedes** [vadimdemedes/ink#34]
<Text> must be documented here https://github.com/vadimdemedes/ink#built-in-components.

**Comment by talon** [comment]
https://github.com/vadimdemedes/ink/pull/36/files

**Comment by mAAdhaTTah** [comment]
Also needs `<Indent>`.

**Comment by vadimdemedes** [comment]
Fixed via https://github.com/vadimdemedes/ink/pull/36. Opened https://github.com/vadimdemedes/ink/issues/51 for `<Indent>`.
