### ISSUE TITLE
Add "Ink in production" section to readme

### ISSUE THREAD

**Issue by vadimdemedes** [vadimdemedes/ink#35]
Currently the list is short:

- [emoj](https://github.com/sindresorhus/emoj).

If you are aware of any high quality CLIs built with Ink, please comment in this thread and I'll add it later to the readme! Also, if some CLI gets rejected, no hard feelings please :)

**Comment by jdeniau** [comment]
Hi, you can add [changelog-view](https://github.com/jdeniau/changelog-view) if you want :)

It's a small cli app that try to check changelogs from installed version of packages. It works with PHP's composer and npm / yarn node_modules

**Comment by vadimdemedes** [comment]
There's "Built with Ink" section in readme now.
