### ISSUE TITLE
regarding installation

### ISSUE THREAD

**Issue by WhoAdarshPandya** [vadimdemedes/ink#352]
hey ink3 is great for making clis but when i try to create a project with ```npx create-ink-app``` it takes longer than 40 to 50 minutes ,i'm using windows 10 as operating system , but it stucks on ```installing dependencies``` (the second step) 
can you figure out how to solve this problem and make projects faster

Thank you very much

**Comment by vadimdemedes** [comment]
Hey @WhoAdarshPandya, this is most likely a problem isolated to your own setup. Can you run these commands in a new folder and see if it takes just as long?

```
$ npm install meow ink react import-jsx
$ npm install --save-dev xo ava @ava/babel ink-testing-library chalk @babel/preset-env @babel/preset-react @babel/register eslint-config-xo-react eslint-plugin-react eslint-plugin-react-hooks
```

**Comment by WhoAdarshPandya** [comment]
hey thanks for suggestion, but i tried it using npx and now after cleaning npx cache it's working fine 

Thank you
