### ISSUE TITLE
`Static` returns stale items on unmount

### ISSUE THREAD

**Issue by herecydev** [vadimdemedes/ink#354]
I'm working on [upgrading to v3 in Gatsby](https://github.com/gatsbyjs/gatsby/pull/26190) and so far it's mostly painless; however it's been taking me a while to track double a double log issue:

![image](https://user-images.githubusercontent.com/11328618/89331445-b4c69c00-d689-11ea-9c2a-37eacbffb79b.png)

I finally tracked it down to this line here, during the unmount: https://github.com/vadimdemedes/ink/blob/master/src/ink.tsx#L234

My question is why is it running `onRender` again, it seems like this always triggers the last `Static` render. We can see that if the last render included 3 new items it will render those 3 again:

![image](https://user-images.githubusercontent.com/11328618/89331802-43d3b400-d68a-11ea-8dae-1e0d8e04860d.png)

(inserting an additional 2 items == 3 items to render)

![image](https://user-images.githubusercontent.com/11328618/89331764-31f21100-d68a-11ea-9fab-cd62a9ab6d30.png)

**Comment by vadimdemedes** [comment]
Hmm, would you be able to create a minimum reproducible example?

**Comment by herecydev** [comment]
I've got the branch pushed here: https://github.com/herecydev/gatsby/tree/feature/updateInk

I'm not sure if I can simplify this issue. I've tried recreating with the static example in this repo; that however works as expected. The only difference I could see is that during the `unmount` method, the rootNode still has childNodes (which looks to be the cause of duplicating logic). In the "static example" the rootNode has **no** child nodes.

Is there anything specific that would trigger that in Gatsby?

**Comment by herecydev** [comment]
So after some further digging, I think I understand what's going wrong. `Static` has a `useEffect` (https://github.com/vadimdemedes/ink/blob/master/src/components/Static.tsx#L44-L46) that fires incrementing the index which will cause a rerender and the children to render will be an empty array. I've added a debug "setting index to {items.length}" to illustrate:

![image](https://user-images.githubusercontent.com/11328618/89831982-a62f2780-db56-11ea-9c46-7b53a0f881a1.png)

This however is not happening in my gatby branch:

![image](https://user-images.githubusercontent.com/11328618/89832043-c4952300-db56-11ea-9745-f180d3d6ae16.png)

**Comment by vadimdemedes** [comment]
Hm, still not sure I understand the issue. Could you try manually replacing `useEffect` with `useLayoutEffect` in `node_modules/ink` and see if that fixes the issue in Gatsby?

**Comment by herecydev** [comment]
Vadim, I've managed to create a simplified repo here: https://github.com/herecydev/ink/tree/feature/staticDuplication

If you run the `examples/static duplication` you should see the following:

![image](https://user-images.githubusercontent.com/11328618/90328978-bac95080-df98-11ea-948f-768e5c0e25a4.png)

**Comment by vadimdemedes** [comment]
Thanks a lot! I traced it down to `useEffect` inside `Static` component. After you dispatch a final action in your example, `unmount()` is called immediately which forces `Static` to return the same items as last frame, because `useEffect` to update list of items hasn't been called yet. The fix was to use `useLayoutEffect` instead which fires synchronously with render.

Submitted https://github.com/vadimdemedes/ink/pull/361 to fix this.

**Comment by vadimdemedes** [comment]
Fix released in [`3.0.4`](https://github.com/vadimdemedes/ink/releases/tag/v3.0.4).

**Comment by herecydev** [comment]
Thanks Vadim I will test that out, do you mind also taking a look at: https://github.com/vadimdemedes/ink-spinner/issues/10
