### ISSUE TITLE
Box attribute textWrap gone and missing from the migration guide

### ISSUE THREAD

**Issue by Snaptags** [vadimdemedes/ink#358]
Using v2.x of ink you could pass a textWrap attribute to `<Box>`.

The attribute is gone from the v3 documentation and at least for TypeScript projects this is a breaking change. There should be a section in the migration guide about textWrap.

**Comment by vadimdemedes** [comment]
Thanks for reporting, updated the migration guide.

**Comment by Snaptags** [comment]
Thank you for updating the guide, I appreciate it. Now it is clear what to do when migrating v2 code.
