### ISSUE TITLE
SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by rharkov** [vadimdemedes/ink#365]
Hey been hitting this error a lot of time and I have used 'importJsx'  to bypass it but it is not a great solution on every jsx and it imposes issues. From my understanding you need good babel config and use 'babel-node' to execute the code. 
![Screen Shot 2020-08-25 at 2 04 58 PM](https://user-images.githubusercontent.com/47150563/91211917-8282ea00-e6dd-11ea-8765-bcf86a40a2eb.png)

```
import React, { useState } from "react";
import { render, Box, Color } from "ink";
import { Tabs, Tab } from "ink-tab";

const MainContent = ({ activeTab }) => (
  <Box>
    {activeTab === "foo" && 'Selected tab is "foo"'}
    {activeTab === "bar" && 'Selected tab is "bar"'}
    {activeTab === "baz" && 'Selected tab is "baz"'}
  </Box>
);

MainContent.propTypes = {
  activeTab: PropTypes.string.isRequired,
};

class TabExample extends Component {
  static propTypes = {
    direction: PropTypes.oneOf(["row", "column"]).isRequired,
  };

  constructor(props) {
    super(props);

    this.state = {
      activeTab: null,
    };

    this.handleTabChange = this.handleTabChange.bind(this);
  }

  handleTabChange(name /* , child */) {
    this.setState({
      activeTab: name,
    });
  }

  render() {
    const { direction } = this.props;
    const { activeTab } = this.state;

    return (
      <Box
        flexDirection={direction === "column" ? "row-reverse" : "column"}
        justifyContent={direction === "column" ? "flex-end" : "flex-start"}
      >
        {activeTab && <MainContent activeTab={activeTab} />}

        {/* eslint-disable-next-line react/self-closing-comp */}
        {direction === "column" && <Box> </Box>}

        <Tabs
          onChange={this.handleTabChange}
          flexDirection={direction}
          width={direction === "column" ? 20 : "100%"}
          keyMap={{ useTab: false }}
        >
          <Tab name="foo">Foo</Tab>
          <Tab name="bar">Bar</Tab>
          <Tab name="baz">Baz</Tab>
        </Tabs>
      </Box>
    );
  }
}

render(
  <TabExample
    direction={process.argv.includes("--column") ? "column" : "row"}
  />,
  { debug: false }
);
```

Also to avoid the import issue I put 'type':"module", in package.json. The code I put is just an example from the ink-tabs repo as I am trying to get the tabs working. 
Problems as well when multiple components like ink-tabs or other ink plugins which throw error in those files as well with 'unexpected token'
Thanks

**Comment by mAAdhaTTah** [comment]
> From my understanding you need good babel config and use 'babel-node' to execute the code.

This or use a bundler like webpack or rollup to generate the CLI build.

**Comment by sindresorhus** [comment]
This issue is not related to Ink. It would apply to anything using JSX.

You can find a good example of Babel setup here: https://github.com/sindresorhus/ink-link/blob/70c43df8b2a23f17681db76b07704b661932c96a/package.json
