### ISSUE TITLE
CI rendering is broken since 3.0.0

### ISSUE THREAD

**Issue by adam-lynch** [vadimdemedes/ink#366]
@vadimdemedes, as I said in https://github.com/vadimdemedes/ink/issues/275#issuecomment-682007306 earlier, I've been trying to narrow down an issue with rendering related to continuous integration services. I managed to narrow it to the Ink 3 release.

I ran `npx create-ink-app`, pasted the counter from the README into `ui.js`, and added an effect which calls exit once the count reaches 10;

```javascript
const React = require("react");
const { useState, useEffect } = React;
const { render, Text, useApp } = require("ink");

const Counter = () => {
  const { exit } = useApp();
  const [counter, setCounter] = useState(0);

  useEffect(() => {
    const timer = setInterval(() => {
      setCounter((previousCounter) => previousCounter + 1);
    }, 100);

    return () => {
      clearInterval(timer);
    };
  }, []);

  useEffect(() => {
    if (counter === 10) {
      exit();
    }
  }, [counter, exit]);

  return <Text color="green">{counter} tests passed</Text>;
};

module.exports = Counter;
```

Locally that works as expected; the count is incremented and then it exits. 10 is rendered.

On CircleCI however, this is what's outputted:

![image](https://user-images.githubusercontent.com/1427241/91581311-34bcea80-e946-11ea-86c2-6d8ae79449e2.png)

No final frame is rendered and there's a bunch of extra newlines.

And it works fine on CircleCI with ink@2.7.1;

![image](https://user-images.githubusercontent.com/1427241/91581413-50c08c00-e946-11ea-811d-88be70b73ef7.png)

Please let me know if I'm using `exit` incorrectly or something like that. I'm happy to make a PR but I just need some feedback

**Comment by vadimdemedes** [comment]
Hm that's odd. I ran your code with `CI=true` environment variable, which triggers the CI rendering behavior, and it works fine. Would you be able to help digging into it? I'd start with capturing output from your script to see what Ink outputs: `node ./ink-test/cli.js > output.txt`.

**Comment by adam-lynch** [comment]
>Would you be able to help digging into it?

Yep, will do

**Comment by adam-lynch** [comment]
`output.txt` contains `10 tests passed` both for `ink@2.7.1` and `ink@3.0.4` surprisingly.

NOTE: In my example, I only use `exit`. I don't use `process.exit` or `waitUntilExit`.

**Comment by adam-lynch** [comment]
If I enable `debug`, `output.txt` is the same for both versions:

```
0 tests passed1 tests passed2 tests passed3 tests passed4 tests passed5 tests passed6 tests passed7 tests passed8 tests passed9 tests passed10 tests passed10 tests passed
```

**Comment by adam-lynch** [comment]
If I change https://github.com/vadimdemedes/ink/blob/master/src/ink.tsx#L248 to...

```diff
+ console.log("this.lastOutput", this.lastOutput);
  this.options.stdout.write(this.lastOutput + '\n');
```

Then the output in the UI looks like this:

![image](https://user-images.githubusercontent.com/1427241/91734445-d8a2d200-eba2-11ea-9dc5-bec514421cb1.png)


(And an extra `this.lastOutput 10 tests passed` line is in `output.txt`

**Comment by adam-lynch** [comment]
In `onRender` where it does:

```
if(isCI) {
  if (hasStaticOutput) {
    this.options.stdout.write(staticOutput);
  }
 this.lastOutput = output;
 return;
```

If I console log `output`, `\n\n\n\n\n\n\n\n\n\n\n\n\n\n` is logged 12 times. This is when running without `> output.txt`.

These logs in `output.txt` are as expected

**Comment by adam-lynch** [comment]
`node.yogaNode.getComputedWidth` returns `0`

**Comment by adam-lynch** [comment]
Replacing that with `80` results in this:

![image](https://user-images.githubusercontent.com/1427241/91738730-d3488600-eba8-11ea-86c1-5861b8eaa387.png)

In the end it's the same problem as #325; `this.options.stdout.columns` returns `0`. #325 uses `??` though. Making a PR...
