### ISSUE TITLE
Would this work with QuickJS?

### ISSUE THREAD

**Issue by bootrino** [vadimdemedes/ink#370]
Very interesting project.

I wonder, would this work with Fabrice Bellard's QuickJS?

https://bellard.org/quickjs/

Then it might be possible to run the entire stack on very small / embedded systems.

**Comment by sindresorhus** [comment]
This would most likely not be feasible. Large parts of Ink depend on Node.js-specific APIs, and many of its dependencies do too. It might be possible to use Browserify/Webpack to polyfill the Node.js APIs, but that would not work perfectly and it would probably be a large undertaking. It's not something we intend to work on, but Ink is open source and you're free to work on a fork.

That being said, it would probably be easier to run Ink on a Node.js version customized for embedded systems, like https://www.neonious.com/lowjs/ (I have not tried it though).

Similar issue: https://github.com/vadimdemedes/ink/issues/250
