### ISSUE TITLE
Byzantine request: Running ink on web-emulated terminals.

### ISSUE THREAD

**Issue by poteat** [vadimdemedes/ink#371]
So, this is a little meta, but my goal is to run a well-designed terminal interface emulated in the browser.  Does someone a little more introduced to this library think that that's even feasible?  I can write the glue code, as long as `ink` gives a generic interface I can implement a "terminal interface" on.

I was thinking of using xterm.js as the actual terminal in this case.

**Comment by mAAdhaTTah** [comment]
Not that byzantine: https://github.com/vadimdemedes/ink/issues/213

**Comment by poteat** [comment]
Thanks! Closing this as duplicate.

**Comment by cjroth** [comment]
FYI I got this working and created a small project around it here: https://github.com/cjroth/ink-web
