### ISSUE TITLE
NerdFont icons fail when rendering inside <Box />

### ISSUE THREAD

**Issue by yeet-bix** [vadimdemedes/ink#374]
Hi there 👋 

I'm having an issue where [nerd font icons](https://www.nerdfonts.com/cheat-sheet) are falling back to their original unicode representations when rendering inside a `<Box />` component. This only happens when rendering multiple `<Text />` components and only affects the first `<Text />` component. Subsequent `<Text />` components are fine. 

I have attached images of a few key use cases.

To reproduce:
- Use any nerd font: https://github.com/ryanoasis/nerd-fonts

**Image 1: Broken icon when rendering multiple `<Text />` components within a `<Box />`** 

<img width="800" alt="Broken" src="https://user-images.githubusercontent.com/28290599/92883800-91df9280-f454-11ea-85fa-7f69815152af.png">

**Image 2: Works with no `<Box />`**

<img width="800" alt="Screen Shot 2020-09-11 at 5 26 48 pm" src="https://user-images.githubusercontent.com/28290599/92883818-960bb000-f454-11ea-9d2d-cf094dff6550.png">

**Image 3: Works when single `<Text />` component**

<img width="800" alt="Screen Shot 2020-09-11 at 5 26 11 pm" src="https://user-images.githubusercontent.com/28290599/92883816-94da8300-f454-11ea-95e2-fe99dcd9c1ab.png">

**Image 4: Still works when single text node**

<img width="800" alt="Screen Shot 2020-09-11 at 5 28 14 pm" src="https://user-images.githubusercontent.com/28290599/92883822-96a44680-f454-11ea-8751-56aa39119ba4.png">

**Comment by vadimdemedes** [comment]
I don't have time at the moment to look into it, would you be able to dive deeper on this?

**Comment by yeet-bix** [comment]
Yep I can take a look when I get some time. Was hoping someone had experienced this before 😛
