### ISSUE TITLE
tsc build issue due to type declarations

### ISSUE THREAD

**Issue by pranshuchittora** [vadimdemedes/ink#375]
I am using TS to build the basic ink example and encountering an error due to the `d.ts` files. 

<details><summary>CLICK ME</summary>
<p>

yarn run v1.21.1
$ tsc -p tsconfig.prod.json
node_modules/ink/build/components/Box.d.ts:2:13 - error TS1005: '=' expected.

2 import type { Except } from 'type-fest';
              ~

node_modules/ink/build/components/Box.d.ts:2:29 - error TS1005: ';' expected.

2 import type { Except } from 'type-fest';
                              ~~~~~~~~~~~

node_modules/ink/build/components/Box.d.ts:3:13 - error TS1005: '=' expected.

3 import type { Styles } from '../styles';
              ~

node_modules/ink/build/components/Box.d.ts:3:29 - error TS1005: ';' expected.

3 import type { Styles } from '../styles';
                              ~~~~~~~~~~~

node_modules/ink/build/components/Box.d.ts:4:13 - error TS1005: '=' expected.

4 import type { DOMElement } from '../dom';
              ~

node_modules/ink/build/components/Box.d.ts:4:33 - error TS1005: ';' expected.

4 import type { DOMElement } from '../dom';
                                  ~~~~~~~~

node_modules/ink/build/components/Newline.d.ts:1:13 - error TS1005: '=' expected.

1 import type { FC } from 'react';
              ~

node_modules/ink/build/components/Newline.d.ts:1:25 - error TS1005: ';' expected.

1 import type { FC } from 'react';
                          ~~~~~~~

node_modules/ink/build/components/Spacer.d.ts:1:13 - error TS1005: '=' expected.

1 import type { FC } from 'react';
              ~

node_modules/ink/build/components/Spacer.d.ts:1:25 - error TS1005: ';' expected.

1 import type { FC } from 'react';
                          ~~~~~~~

node_modules/ink/build/components/Static.d.ts:1:13 - error TS1005: '=' expected.

1 import type { ReactNode } from 'react';
              ~

node_modules/ink/build/components/Static.d.ts:1:32 - error TS1005: ';' expected.

1 import type { ReactNode } from 'react';
                                 ~~~~~~~

node_modules/ink/build/components/Static.d.ts:2:13 - error TS1005: '=' expected.

2 import type { Styles } from '../styles';
              ~

node_modules/ink/build/components/Static.d.ts:2:29 - error TS1005: ';' expected.

2 import type { Styles } from '../styles';
                              ~~~~~~~~~~~

node_modules/ink/build/components/Text.d.ts:1:13 - error TS1005: '=' expected.

1 import type { FC, ReactNode } from 'react';
              ~

node_modules/ink/build/components/Text.d.ts:1:36 - error TS1005: ';' expected.

1 import type { FC, ReactNode } from 'react';
                                     ~~~~~~~

node_modules/ink/build/components/Text.d.ts:2:13 - error TS1005: '=' expected.

2 import type { Styles } from '../styles';
              ~

node_modules/ink/build/components/Text.d.ts:2:29 - error TS1005: ';' expected.

2 import type { Styles } from '../styles';
                              ~~~~~~~~~~~

node_modules/ink/build/components/Text.d.ts:3:13 - error TS1005: '=' expected.

3 import type { LiteralUnion } from 'type-fest';
              ~

node_modules/ink/build/components/Text.d.ts:3:35 - error TS1005: ';' expected.

3 import type { LiteralUnion } from 'type-fest';
                                    ~~~~~~~~~~~

node_modules/ink/build/components/Text.d.ts:4:13 - error TS1005: '=' expected.

4 import type { ForegroundColor, BackgroundColor } from 'chalk';
              ~

node_modules/ink/build/components/Text.d.ts:4:55 - error TS1005: ';' expected.

4 import type { ForegroundColor, BackgroundColor } from 'chalk';
                                                        ~~~~~~~

node_modules/ink/build/components/Transform.d.ts:1:13 - error TS1005: '=' expected.

1 import type { FC, ReactNode } from 'react';
              ~

node_modules/ink/build/components/Transform.d.ts:1:36 - error TS1005: ';' expected.

1 import type { FC, ReactNode } from 'react';
                                     ~~~~~~~

node_modules/ink/build/dom.d.ts:3:13 - error TS1005: '=' expected.

3 import type { OutputTransformer } from './render-node-to-output';
              ~

node_modules/ink/build/dom.d.ts:3:40 - error TS1005: ';' expected.

3 import type { OutputTransformer } from './render-node-to-output';
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/ink/build/dom.d.ts:4:13 - error TS1005: '=' expected.

4 import type { Styles } from './styles';
              ~

node_modules/ink/build/dom.d.ts:4:29 - error TS1005: ';' expected.

4 import type { Styles } from './styles';
                              ~~~~~~~~~~

node_modules/ink/build/hooks/use-focus-manager.d.ts:1:13 - error TS1005: '=' expected.

1 import type { Props } from '../components/FocusContext';
              ~

node_modules/ink/build/hooks/use-focus-manager.d.ts:1:28 - error TS1005: ';' expected.

1 import type { Props } from '../components/FocusContext';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/ink/build/ink.d.ts:2:13 - error TS1005: '=' expected.

2 import type { ReactNode } from 'react';
              ~

node_modules/ink/build/ink.d.ts:2:32 - error TS1005: ';' expected.

2 import type { ReactNode } from 'react';
                                 ~~~~~~~

node_modules/ink/build/measure-element.d.ts:1:13 - error TS1005: '=' expected.

1 import type { DOMElement } from './dom';
              ~

node_modules/ink/build/measure-element.d.ts:1:33 - error TS1005: ';' expected.

1 import type { DOMElement } from './dom';
                                  ~~~~~~~

node_modules/ink/build/render.d.ts:2:13 - error TS1005: '=' expected.

2 import type { ReactElement } from 'react';
              ~

node_modules/ink/build/render.d.ts:2:35 - error TS1005: ';' expected.

2 import type { ReactElement } from 'react';
                                    ~~~~~~~


Found 36 errors.

error Command failed with exit code 2.


</p>
</details>


```json
{
  "compilerOptions": {
    "rootDir": "src",
    "types": ["jest"],
    "esModuleInterop": true,
    "module": "commonjs",
    "jsx": "react",
    "moduleResolution": "node",
    "skipLibCheck": true,
    "target": "es5",
    "strict": false,
    "lib": ["es6", "es2017"],
    "resolveJsonModule": true,
    "declaration": true,
   "sourceMap": true,
    "outDir": "dist"
  },
  "exclude": ["node_modules", "dist", "src/lib/tests", "build"]
}

```

**Comment by sindresorhus** [comment]
Looks like you need to upgrade your TypeScript version to v4.

**Comment by pranshuchittora** [comment]
Thanks @sindresorhus this solves the issue.

But I have a couple of questions.
Q1. This makes `ink` not compatible with TSv3 which might affect some users. It would be great if we can mention this somewhere in the docs.

Q2. Why we have deprecated https://www.npmjs.com/package/@types/ink ? Shipping types separately won't create the above-mentioned error in TSv3.

**Comment by sindresorhus** [comment]
1. https://github.com/vadimdemedes/ink/pull/376
2. DefinitelyTyped definitions easily get out of date. It creates all kinds of other problems.

**Comment by vadimdemedes** [comment]
Hey @pranshuchittora, does TypeScript 3.8 work for you too? `import type` got added in 3.8 - https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html.
