### ISSUE TITLE
Raw Mode and Subprocesses

### ISSUE THREAD

**Issue by elmpp** [vadimdemedes/ink#378]
Hi there,

I'm launching a new process (via [execa](https://github.com/sindresorhus/execa)) but can't seem to find the right combination of [stdio](https://github.com/sindresorhus/execa#stdio) to avoid this error:

```
 ERROR Raw mode is not supported on the current process.stdin, which Ink uses
           as input stream by default.
           Read about how to prevent this error on
           https://github.com/vadimdemedes/ink/#israwmodesupported
```

I need to capture the stdout (pipe) of the subprocess also. I thought this `stdio` setting would be ok:   `['inherit', 'pipe', 'pipe']`  🤔  

I have the latest ink and am using `useInput` exclusively

**Comment by vadimdemedes** [comment]
Could you post a minimal reproduction?

**Comment by elmpp** [comment]
I'm having real trouble creating a minimal reproduction - using the simpler setup with `import-jsx` etc all appears ok.

Perhaps if i describe my expectations a little you might point out the obvious things i'm doing wrong

I'm writing acceptance tests in Jest that call my own CLI app as a subprocess (via execa). The cli app then mounts an ink component and gives an output. This is the relevant mount code:

```
function runInk(
  Component: CommandComponent,
  context: CommandContext,
  cb: (...args: any[]) => void,
  formValues?: Record<string, any>
) {
  // const ContextContext = React.createContext<ContextProject>(context)

  const enterAltScreenCommand = '\x1b[?1049h'
  const leaveAltScreenCommand = '\x1b[?1049l'
  // process.stdout.write(enterAltScreenCommand)
  process.on('exit', () => {
    // process.stdout.write(leaveAltScreenCommand)
  })

  render(
    // <ContextContext.Provider value={context}>
    <Component context={context.context} formValues={formValues} cb={cb} />
    // </ContextContext.Provider>
  )
}
```

I'm hoping to capture the entire subprocess cli output and do assertions. The cli subprocess' `stdio` is set as `['inherit', 'pipe', 'pipe']`. However, Ink throws error due to no [isTTY](https://github.com/vadimdemedes/ink/blob/9ebfe314e865506ccb37b48723a27485346d950b/src/components/App.tsx#L140). 

I see that ink-testing-library [mocks isTTY](https://github.com/vadimdemedes/ink-testing-library/compare/v1.0.1...v1.0.2#diff-168726dbe96b3ce427e7fedce31bb0bcR31) - would this be possible in Jest i wonder?

**Comment by elmpp** [comment]
I wouldn't know where to start with all the layers involved with Jest so i have gotten round this by taking the same approach as [ink-testing-library](https://github.com/vadimdemedes/ink-testing-library/blob/master/source/index.ts#L38) and supplying a mock Stdin.

My `runInk` function now looks like this:

```
class Stdin extends EventEmitter {
	isTTY = true;

	write = (data: string) => {
		this.emit('data', data);
	};

	setEncoding() {
		// Do nothing
	}

	setRawMode() {
		// Do nothing
	}

	resume() {
		// Do nothing
	}

	pause() {
		// Do nothing
	}
}

function runInk(
  Component: CommandComponent,
  context: CommandContext,
  cb: (...args: any[]) => void,
  formValues?: Record<string, any>
) {
  // const ContextContext = React.createContext<ContextProject>(context)

  const enterAltScreenCommand = '\x1b[?1049h'
  const leaveAltScreenCommand = '\x1b[?1049l'
  // process.stdout.write(enterAltScreenCommand)
  process.on('exit', () => {
    // process.stdout.write(leaveAltScreenCommand)
  })

  // const stdin = process.stdin
  // stdin.isTTY = true

  render(
    // <ContextContext.Provider value={context}>
    <Component context={context.context} formValues={formValues} cb={cb} />
    // </ContextContext.Provider>
  , {stdin: new Stdin() as unknown as ReadStream})
}
```

**Comment by junjun1128** [comment]
Do you have any methords to solve this question?  I I encountered the same problem, Thank you very much

**Comment by AKclown** [comment]
I faced the same problem when I ran on git bash gui tool。When I comment out useInput the behavior is normal
![image](https://github.com/vadimdemedes/ink/assets/33648653/5e123ccb-2e2d-4a96-b6d6-4a0b44e7ee2f)
It works normally when I run the cmd that comes with window or bash in vscode.
![image](https://github.com/vadimdemedes/ink/assets/33648653/f9ae215d-3a05-4100-bb22-f5868f1acf69)
