### ISSUE TITLE
Ink defines global window object

### ISSUE THREAD

**Issue by loilo** [vadimdemedes/ink#384]
Ink defines a global `window` object. As far as I can tell, this is done exclusively [for devtools support](https://github.com/vadimdemedes/ink/blob/master/src/devtools.ts#L12-L14).

Defining a global `window` breaks other packages which assume the existence of a web browser based on the existence of `window` (in my case this is [`vue-template-compiler`](https://npmjs.com/package/vue-template-compiler)).

Could we somehow avoid setting a global `window` variable, or only do it if `DEV=true` is set?

**Comment by sindresorhus** [comment]
Maybe Ink could use [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) instead. It should be available in modern browsers.

**Comment by loilo** [comment]
I'll give it a shot and open a PR if it works.

**Comment by loilo** [comment]
Seems like there's nothing Ink can do in the `window` department, apparently the devtools are just [hardcoded to use it](https://github.com/facebook/react/blob/1cbaf48889c6362232d907e57ce6c132744445d0/packages/react-devtools-core/src/backend.js#L34).

The code setting up the global `window`  also can't be moved into the conditional `process.env.DEV === 'true'` block, because they need to be set up before importing `react-devtools-core`, which itself can not be done conditionallly because it's a static ESM import.

That said, this current setup only works because TypeScript compiles the mentioned static import into a CommonJS `require` call. If it would be compiled to ESM, the import would be hoisted which would render the setup code useless.

I also tried to use a dynamic import inside the condition to resolve this, but it doesn't work — apparently, `connectToDevTools` needs to be called synchronously.

It looks like our best bet here would be to convert the `react-devtools-core` import into a `require` call which can be put inside the `DEV` condition. I generally dislike using `require` in TypeScript, but since the setup currently only works because TypeScript does the `import` → `require` conversion anyway, that probably shouldn't be a blocker.

Thoughts?

**Comment by vadimdemedes** [comment]
> It looks like our best bet here would be to convert the react-devtools-core import into a require call which can be put inside the DEV condition.

I think this solution is good, do you want to submit a PR for it?

**Comment by loilo** [comment]
Yep, I'll take care of this.
