### ISSUE TITLE
Functional Testing

### ISSUE THREAD

**Issue by elmpp** [vadimdemedes/ink#386]
I'm using ink to build a fairly large dashboard-style app with separate "pages", pretty complex focus handling between elements etc.

I am using [ink-testing-library](https://github.com/vadimdemedes/ink-testing-library) for some things but it's becoming clear that what's needed is less a unit-testing library and more a functional one. 

Do you have an opinion on which libraries would be a good fit here? 

My main thoughts at this stage:
  - The user journeys i aim to test must be entirely keyboard driven (obvs)
  - I think creating some kind of adapter to interface with stdin and supply the key codes in order could be fairly simple
  - The real problem i see is performing assertions on the "terminal buffer" (my knowledge here isn't great). Tools like Selenium parse this and allow easy querying. Perhaps as this is React existing tools could work?

My dream scenario would be just an adapter for Cypress that would then allow screenshots, test recording etc etc

I don't think i've said so in my issues thus far but thank you for Ink. It's absolutely foundational to the kind of app i've always looked to be building

**Comment by mAAdhaTTah** [comment]
I did this Cucumber & `node-pty`. This is what by World looks like: https://github.com/mAAdhaTTah/brookjs/blob/master/packages/brookjs-cli/features/support/world.ts Some of this specific to my app, but addresses 2 of the 3 bullets. For the third, I'm not testing the UI output at the functional level but the side effects (are these files created?) and mostly doing so with snapshot tests. I test the UI at the unit level, also with snapshot tests. What I'd ideally like to do is combine that with #213 and do the UI development in Storybook, but it's a hobby project so I haven't made a ton of progress there.

**Comment by elmpp** [comment]
It's definitely possible to do _some_ UI testing through unit and snapshots but i'm definitely past there now for my app. 

I'm gonna have to do a lot of research i expect but i'm starting to think there must be a way to assert on the component tree rather than parsing the raw output. At least for a "functional" set of tests vs real "UI" ones 🤷

**Comment by vadimdemedes** [comment]
I admit I haven't given this topic a lot of thought, but definitely open to it. @elmpp could you provide a few example scenarios which you would like to be able to test and why `ink-testing-library` is not a good fit?

**Comment by vadimdemedes** [comment]
Found https://github.com/crutchcorn/cli-testing-library which looks really cool.
