### ISSUE TITLE
Support `style` object on Box

### ISSUE THREAD

**Issue by Remagpie** [vadimdemedes/ink#387]
Currently, we can use the `style` object to specify stylings in the `Static` component.
It would be nice if it's supported on `Box` components so that we can pass a single object instead of passing many separated props.

YMMV, but I had a nice experience with this kind of API in other environments like react-native.

**Comment by vadimdemedes** [comment]
That's a good catch about the inconsistency between `Static` and `Box`. I don't think there's a significant benefit of having `style` prop instead of individual props for each style prop. In fact, you'd get worse performance, because React would see `style` prop value as a new one each time and would have to re-render that component more than needed:

```jsx
// Won't rerender
<Box marginTop={1}/>

// Will rerender, because a new `style` object is created each time
<Box style={{ marginTop: 1 }}/>
```

You could of course use memoize it, but I think it'll get pretty verbose if you have to do that for every component.

**Comment by Remagpie** [comment]
When using object-style `style` prop, the use cases I saw usually defined the style object as a external constant which is not defined inside the `render` function. ex)
```jsx
const FancyBox = () => (<Box style={styles.fancyBox} />);

const style = {
  fancyBox: {
    width: "40%",
    borderStyle: "singleDouble",
  },
};
```
I think we won't have any performance issue in this way.

**Comment by vadimdemedes** [comment]
You could use object spread to keep the `style` object and be compatible with `Box`:

```jsx
<Box {...style.fancyBox}>
```

**Comment by vadimdemedes** [comment]
Another downside to consider when using external objects is that they're not typed with TypeScript out-of-the-box, because to TypeScript this is just another key-value object.

**Comment by Remagpie** [comment]
Oh, I almost forgot that we can use object spread in jsx!
I think it's good enough for my case. You can close this issue if you want.

**Comment by Remagpie** [comment]
BTW, for the typings, I saw we have a `Styles` type in [styles.ts](https://github.com/vadimdemedes/ink/blob/master/src/styles.ts).
I think you can import and use this type.

**Comment by vadimdemedes** [comment]
Yeah, but that's manual work you don't have to do if you just specify props directly on `Box`. Or you'd need this every time you want to store style props outside:

```ts
import {Styles} from 'ink';

const styles: { [key: string]: Styles } = {
  something: { width: '100%' }
};
```
