### ISSUE TITLE
Add Yeoman generators to readme

### ISSUE THREAD

**Issue by vadimdemedes** [vadimdemedes/ink#39]
There are 2 Yeoman generators to easily get started with Ink:

1. https://github.com/vadimdemedes/generator-ink-component - Create a reusable Ink component
2. https://github.com/vadimdemedes/generator-ink-cli - Create a CLI that uses Ink

Having them in the readme would ease the intro to Ink.

**Comment by shakyink** [comment]
@vadimdemedes - I've made a [PR](#44) that adds information on these two generators to the readme.

**Comment by vadimdemedes** [comment]
Fixed via #44.
