### ISSUE TITLE
Background Color to the Box Component

### ISSUE THREAD

**Issue by utsavk28** [vadimdemedes/ink#402]
Recently , I started using the ink to create cli. During this time i felt the need of having background color to box componenets. Because when was building my project, i decided to add themes to it , but that didn't work out as the box components doesn't have background color feature

**Comment by vadimdemedes** [comment]
This is intentional, because previous major version of Ink had a lot of trouble implementing it, so I removed it in Ink 3 in favor of colorful text. You can add colorful borders to `<Box>` too, which could be a better looking alternative to colorful backgrounds in the terminal. See https://github.com/vadimdemedes/ink#bordercolor.

**Comment by manast** [comment]
Hmm, but how do you implement something like a "selector" in a list component? normally you want the selector to be the same wide as the box, not only the text, which looks quite ugly and is not what you would expect...

**Comment by manast** [comment]
Example:
<img width="228" alt="image" src="https://user-images.githubusercontent.com/95200/161426357-72176709-565e-437b-8f46-ab4bff13d37c.png">

**Comment by vadimdemedes** [comment]
I'd specify a background color for a `Text` component.

**Comment by vadimdemedes** [comment]
I don't think there is one right now. If you're building a fullscreen ncurses-like CLI, [`react-blessed`](https://github.com/yomguithereal/react-blessed) might be a better fit for you than Ink.

**Comment by pierpo** [comment]
OK, good to know. Thanks :blush:

**Comment by Mohammer5** [comment]
If you know the width of the box (e.g. by using [this](https://github.com/vadimdemedes/ink/issues/263#issuecomment-765106184) to determine the dimensions of the stdout), you could just add spaces to the end of the string:

```jsx
<Text backgroundColor="green" color="black" wrap="truncate-end">{myString.padEnd(columns, ' ')</Text>
```

![image](https://github.com/vadimdemedes/ink/assets/10101831/efad4b7f-36d2-46f6-8e53-6fbb92abec24)

**Comment by kumavis** [comment]
i do think you should reconsider supporting this, useful for Modals

fyi Readme shows backgroundColor on Box https://github.com/vadimdemedes/ink?tab=readme-ov-file#background

edit: it was re-added here https://github.com/vadimdemedes/ink/pull/729
