### ISSUE TITLE
Invalid asm.js: Type mismatch in assignment

### ISSUE THREAD

**Issue by Jarred-Sumner** [vadimdemedes/ink#415]
Great work with `ink`. I'm using it in [`git-peek`](https://github.com/Jarred-Sumner/git-peek) for repository search.

This warning appears on start from `ink`:
```
(node:23233) V8: /Users/jarredsumner/Code/git-peek/bin/git-peek:43175 Invalid asm.js: Type mismatch in assignment
```

With `--trace-warnings`:
```
node --trace-warnings /Users/jarredsumner/Code/git-peek/bin/git-peek
(node:23233) V8: /Users/jarredsumner/Code/git-peek/bin/git-peek:43175 Invalid asm.js: Type mismatch in assignment
    at /Users/jarredsumner/Code/git-peek/bin/git-peek:65118:6
    at /Users/jarredsumner/Code/git-peek/bin/git-peek:65337:3
    at /Users/jarredsumner/Code/git-peek/bin/git-peek:12:5
    at /Users/jarredsumner/Code/git-peek/bin/git-peek:74929:48
    at /Users/jarredsumner/Code/git-peek/bin/git-peek:12:5
    at /Users/jarredsumner/Code/git-peek/bin/git-peek:76804:38
    at /Users/jarredsumner/Code/git-peek/bin/git-peek:12:5
    at /Users/jarredsumner/Code/git-peek/bin/git-peek:76999:31
    at /Users/jarredsumner/Code/git-peek/bin/git-peek:12:5
    at /Users/jarredsumner/Code/git-peek/bin/git-peek:77343:18
```

Is this related to the yoga stuff? Any idea on how to resolve it without adding `--no-warnings` to the shebang? 

When I tried that, it caused https://github.com/Jarred-Sumner/git-peek/issues/7, which adding `-S` to the shebang caused https://github.com/Jarred-Sumner/git-peek/issues/9. I think `-S` breaks npm's automatic `.cmd` shim thing.

**Comment by vadimdemedes** [comment]
Closing, since it sounds like https://github.com/evanw/esbuild/issues/856 was causing this issue.
