### ISSUE TITLE
chalk colors do not seem to function when compiling with typescript

### ISSUE THREAD

**Issue by fugufish** [vadimdemedes/ink#418]
chalk colors don't function when compiling with typescript (using lerna) this is because the chalk level at compile time, the chalk color level is set to 0, so the templates are compiled with coloring stripped. I resolved this temporarily by setting chalk.color = 3 in `colorize.ts` on my fork.

that said, I don't think that is a good enough solution. I think the best solution would be to have the color level able to be set as a render option. This would allow developers to override the chalk color level if they seem it necessary. I don't have time at the moment to submit a pr to this effect, but the temporary fix (setting it in `colorize.ts` ) at least fixes the immediate bug.

**Comment by vadimdemedes** [comment]
Not sure what you're referring to, since chalk level is determined at runtime, not compile time. Could you create a minimal repository where this can be reproduced?
