### ISSUE TITLE
[Question] Array Input Component

### ISSUE THREAD

**Issue by elmpp** [vadimdemedes/ink#420]
I'd like to accept a collection of values as part of a single field. With web apps there'd customarily be a button to add another text input below the last. 

Would you have any thoughts/gotchyas on how to create such a component?

**Comment by vadimdemedes** [comment]
Usually CLIs use multi selects for this kind of thing, like this https://github.com/terkelg/prompts#multiselectmessage-choices-initial-max-hint-warn. There's no component I'm aware of that builds that with Ink, so you'd have to implement it yourself.
