### ISSUE TITLE
Render straight to stdout via an option 

### ISSUE THREAD

**Issue by elmpp** [vadimdemedes/ink#423]
This is related to the other `log-update` issues, principally [382](https://github.com/vadimdemedes/ink/issues/382)

I have quite a few components, some are "interactive" and some are "non interactive; render once". I have a use case where i'm wanting to capture the last frame of a few of these "render once" components and have it write to the stdout (that i set as an option). I am not worried about overflowing or off-screen correctness, just that the last frame is appended to the stream

I can see that `log-update` sensibly cares only about the current "viewport" and clears before render. This makes sense for "interactive; reactive components". However, for this usecase, could an extra option be considered to "bypass" `log-update` and write to stdout?

I have tried all combinations of `debug` and `CI` which get me close. A "throttled debug without clearing" describes it well enough

Can create a PR if sounds ok

gif showing working version (there are 3 render calls amongst this output):

![ascii_cinema_ink](https://user-images.githubusercontent.com/864612/112315326-526aec00-8caa-11eb-8f6a-f20b57c482c1.gif)

**Comment by mAAdhaTTah** [comment]
I think `Static` is what you're looking for: https://github.com/vadimdemedes/ink#static

**Comment by elmpp** [comment]
I tried Static but it doesn't seem to handle multiline output from a component. As i only want to "render once" this is what i tried:

```
return (<React.Fragment>
          <Static items={[0]}>
            {() => (
              <Component context={context} {...otherProps as any} cb={exitCb} />
            )}
          </Static>
        </React.Fragment>
      )}
```

`Component` here returns anything from 1...1000 lines. When i render it, I see a single empty line

**Comment by elmpp** [comment]
@mAAdhaTTah do you you have an example of using `Static` with a multiline component? This usecase *feels* like it pretty common...

**Comment by elmpp** [comment]
Managed to meet my usecase with a combination of `waitUntilExit()` a custom `patchConsole()`

**Comment by gnidan** [comment]
@elmpp could you share your solution? I've had my eye on best practices around using `Static` and I'd love to see an alternate approach! Thanks!

**Comment by vadimdemedes** [comment]
I'm also curious about `<Static>` not handling a component with multi-line output, I don't see why it wouldn't? Minimal reproduction would be great!
