### ISSUE TITLE
Control which side has a border

### ISSUE THREAD

**Issue by Sun-2** [vadimdemedes/ink#425]
So far, it looks like it's possible to draw only a full box, where borders on all 4 sides are visible.

Is it possible to control which sides are rendered? If not, will it be in the future, by any chance?

**Comment by vadimdemedes** [comment]
You're right, it's not currently supported, but PR is welcome to add `borderTop`, `borderBottom`, etc boolean props to add this!

**Comment by ryan-waltz** [comment]
#**https://github.com/vadimdemedes/ink/pull/431**

**Comment by krychu** [comment]
This would be useful for creating tables and layouts, as an example screenshot from BitVision:

<img src="https://user-images.githubusercontent.com/947457/142940940-04b96130-0c96-4ab7-9a61-6f4373a248cc.png" width="400">

I suspect many apps run into such a need. I saw the PR mentioned above and the concern about inverted API. What about:

## Show all borders (works as before):
```
<Box borderStyle="single"></Box>
```

## Show borders selectively
- As an example: top/bottom ON, left/right OFF

### option A
```
<Box borderStyleTop="single" bordeStyleBottom="single"></Box>
```
Non-listed borders are off.

### option B
```
<Box borderStyle="single" border={[true,false]}></Box>
```
Values of `border` array follow css pattern for `margin` and `padding`: one array value = [all borders]; two array values = [top/bottm, left/right]; four values = [top, right, bottom, left]

### option C
```
<Box borderStyle="single" border={{top: true, bottom: true}}></Box>
```

Non-listed borders are off.

wdyt?

**Comment by vadimdemedes** [comment]
This is closed via https://github.com/vadimdemedes/ink/pull/568.
