### ISSUE TITLE
not running with latest version

### ISSUE THREAD

**Issue by ph98** [vadimdemedes/ink#441]
Hey everyone. 
I tried to run a fresh project with `npx create-ink-app`

and then i run it and I'll get :
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/parham/Desktop/.../node_modules/meow/index.js
require() of ES modules is not supported.
require() of /home/parham/Desktop/.../node_modules/meow/index.js from /home/parham/Desktop/.../cli.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
```

my environment :

```
❯ node -v
v14.16.1
```

**Comment by sindresorhus** [comment]
Will be fixed by https://github.com/vadimdemedes/create-ink-app/pull/14

**Comment by adielhercules** [comment]
Just wondering, the PR seems to be open still, any idea on how soon is this getting merged/published?

Right now it only seems to work with manual configuration. create-ink-app is broken
