### ISSUE TITLE
Broken rendering of box borders containing wide characters

### ISSUE THREAD

**Issue by dundalek** [vadimdemedes/ink#443]
Box borders have issue with rendering when there is text with wide characters inside. It results in the right part of the border being shifted and turns out more broken when boxes are nested.

Since the first "hello" box is positioned correctly and there are no overlaps, it suggests that measuring text dimensions itself is correct. This leads me to believe there is likely a bug in the border rendering code not taking proper text length into account and padding it with incorrect amount of spaces.

Tried it and have same output both in GNOME Terminal and Alacritty.

Might be related to https://github.com/vadimdemedes/ink/issues/369 as emojis also render as two cells like wide characters.

![ink](https://user-images.githubusercontent.com/755611/119221015-c2e08e80-badc-11eb-86e3-bd7173a58aee.png)

```jsx
const React = require('react');
const {Box, Text} = require('ink');

const konnichiwa = "こんにちは";

const Example = (props) => (
  <Box flexDirection="column" {...props}>
    <Box>
      {/* using padding instead of border to match aligment */}
      <Box padding={1}>
        <Text>{konnichiwa}</Text>
        <Box borderStyle="single">
          <Text>hello</Text>
        </Box>
      </Box>
    </Box>
    <Box>
      <Box borderStyle="single">
        <Text>{konnichiwa}</Text>
        <Box borderStyle="single">
          <Text>hello</Text>
        </Box>
      </Box>
    </Box>
  </Box>
)

const App = ({name = 'Stranger'}) => (
  <Box flexDirection="column">
    <Example />
    <Example borderStyle="single" borderColor="cyan" />
  </Box>
);

module.exports = App;
```

**Comment by dundalek** [comment]
Had a look at border rendering unit tests. It looks like `boxen` package is used when checking rendered output. I tried to add cases with wide characters and emojis. It looks like `boxen` renders them correctly which is a promising lead, we just need to check what is done differently in border rendering of ink.

```tsx
test('single node - fit-content box with wide characters', t => {
	const output = renderToString(
		<Box borderStyle="round" alignSelf="flex-start">
			<Text>こんにちは</Text>
		</Box>
	);

	t.is(output, box('こんにちは'));
});

test('single node - fit-content box with emojis', t => {
	const output = renderToString(
		<Box borderStyle="round" alignSelf="flex-start">
			<Text>🌊🌊</Text>
		</Box>
	);

	t.is(output, box('🌊🌊'));
});
```

![image](https://user-images.githubusercontent.com/755611/119221326-549ccb80-bade-11eb-9590-49fad94383e5.png)

**Comment by Netfloex** [comment]
When using the following example

```tsx
<>
	<Box width={20}>
		<Box width={"50%"} borderStyle="single" flexDirection="column">
			<Text>🌊</Text>
		</Box>
		<Box borderStyle="single" flexGrow={1}>
			<Text>Weird</Text>
		</Box>
	</Box>

	<Box width={20}>
		<Box width={"50%"} borderStyle="single" flexDirection="column">
			<Text>Normal</Text>
		</Box>
		<Box borderStyle="single" flexGrow={1}>
			<Text>Correct</Text>
		</Box>
	</Box>
</>
```

I get this inside the terminal:

```
┌────────┐┌────────┐
│🌊      │ │Weird   │
└────────┘└────────┘
┌────────┐┌────────┐
│Normal  ││Correct │
└────────┘└────────┘
```

I'm using ink 3.2.0

(Screenshot)

![image](https://user-images.githubusercontent.com/38650595/149518737-478c16de-39e3-47e3-a62e-377ece781c56.png)
