### ISSUE TITLE
Hide warning message

### ISSUE THREAD

**Issue by jakecastelli** [vadimdemedes/ink#447]
Hi, thanks for the awesome work.

I wanted to hide/ suspend the warning message for the production as I am getting the following sometimes:

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

**Comment by sindresorhus** [comment]
Wouldn't it be better to fix the underlying issue?

**Comment by jakecastelli** [comment]
Hi @sindresorhus 👋 

I am a bit rusted in this situation where usually cause the warning in my code.

Here I have an rest api call in useEffect and while its doing the api call if I press escape key then it would warn me, for example:
```
useInput((_, key) => {
    if (isLoading) {
      return;
    }

    if (key.escape) {
        onClose();
    }
  });`

`useEffect(() => {
// let's say this API call takes 5s and I pressed ESC before its finished
  apiCallToGetSomeData();
}, [])
```

What I did to prevent warning was added another state called `isLoading`, when `isLoading` is true then it will disable the escape key. But it didn't look like a legit fix as the user may request to cancel the api call if it takes too long. I know this question is unrelated to **ink** itself but I still do appreciate your or anyone's help/ feedback.

^ I also looked into [this](https://stackoverflow.com/questions/53949393/cant-perform-a-react-state-update-on-an-unmounted-component)  but it looks like a hack to me as well 😞  _that's why I thought about disable the warning in production._

**Comment by jakecastelli** [comment]
I figured out a way to hack this around just in case anyone needed - **_BUT it is always good to fix the underlying issues_** like @sindresorhus said above ^

The hack is to put the following _after_ the `render(<App />)`, you can custom what sort of error you don't want to display in production code. You can have a mode such as dev or prod, if its dev mode disable the function below.
```
const error = console.error;
function logError(...parameters) {
  let filter = parameters.find((parameter) => {
    return (
      // Filter error because XXX -- Only in production
      // ameter.includes('Warning: %s is deprecated in StrictMode') ||
      // Another error to filter because of YYYY
      parameter.includes('Warning:')
    );
  });
  if (!filter) error(...parameters);
}
console.error = logError;
```
