### ISSUE TITLE
Interest in plugin?

### ISSUE THREAD

**Issue by jimthedev** [vadimdemedes/ink#45]
I wrote a thing to handle exiting processes in ink

Is this something you'd consider putting on the readme?

https://github.com/jimthedev/ink-process

**Comment by vadimdemedes** [comment]
I don't think it has enough value for the majority of users, unfortunately. Do you have an example CLI where this is indeed useful?

**Comment by jimthedev** [comment]
Sure, let's take the following example:

We're building a cli that allows the user to create a new user.  If they fill out all of the information properly then the user will be created. If they fill out all of the information correctly but some error happens when finally persisting the user then the app will exit with an informative *nix exit code to let us know what happened.  If everything succeeds then we'll return an exit code of 0 of course. Here's the kicker, no matter which path they go down we want to show (render) a text summary of what happened during the run. There are multiple things that could fail of course (network error, non-unique usernames or emails that are already in use etc) and each should have a unique status code, but in each case the summary should be rendered pre-exit.

**Comment by vadimdemedes** [comment]
I see, sure, I think it can be included. As for handling errors, I think implementing `componentDidCatch` from React 16 would be very cool. Added to todo ;)

**Comment by vadimdemedes** [comment]
Auto fixed in Ink 2 by using React directly.
