### ISSUE TITLE
Background Color to the Box Component

### ISSUE THREAD

**Issue by BhupathiReddyGaddam** [vadimdemedes/ink#452]
I would like to thank you for Ink library. The features in Ink really helpful for us. The only thing that we needed is the background color to the Box components. We are planning to apply themes to our project and we want to differentiate the sections using different background color for each section. It's helpful if we can apply background color to the Box components.

**Comment by vadimdemedes** [comment]
Replied in here → https://github.com/vadimdemedes/ink/issues/453.
