### ISSUE TITLE
This project is amazing

### ISSUE THREAD

**Issue by dustinlacewell** [vadimdemedes/ink#454]
Feel free to close this, I just wanted to share my appreciation for this awesome library. Blew my mind.

My only feedback is that it needs an official contrib component library!

Thanks a lot for making this.

**Comment by vadimdemedes** [comment]
Thank you! ❤️

> My only feedback is that it needs an official contrib component library!

What would you want to see in it?

**Comment by dustinlacewell** [comment]
All of the various components that are not in core, available in one place, and maintained to track the upstream package!

Currently there's dozens of various ink-* packages in various states of maintenance. We should put them all into a monorepo (or even just a single package) and invite the community to collaborate to keep them in shape.

Much like blessed-contrib.
