### ISSUE TITLE
How to connect React Devtool on the Win10? It reminds me "Cannot find the command dev" when I input "dev = true"

### ISSUE THREAD

**Issue by ParadiseWitch** [vadimdemedes/ink#474]
![image](https://user-images.githubusercontent.com/37146904/131429809-58c6dbb8-8ec0-4336-8bd3-b4db37008a0e.png)

**Comment by sindresorhus** [comment]
The guides assume a Unix environment. You can Google how to set environment variables on Windows. Or better yet, install WSL.

**Comment by ParadiseWitch** [comment]
How to set environment variables for a program named DEV
