### ISSUE TITLE
How to exit stdin (useInput) but persist final output

### ISSUE THREAD

**Issue by milesj** [vadimdemedes/ink#476]
I have a series of input fields that all render and work beautifully, and I would like Ink to render the "final output" of these input fields when form is submitted. However, this doesn't seem currently possible because:

- Ink will never close unless the stdin streams are closed. This only happens when a component using `useInput` _unmounts_, which ends the stream. https://github.com/vadimdemedes/ink/blob/master/src/hooks/use-input.ts#L192
- Unmounting the component means the final output is now gone (we rendered null last) and will not be persisted in the console.
- I don't think we can use `Static` here, since it would put us back in the stdin stream?

Maybe `useInput` can return some functionality to force the stream to close?

```ts
const close = useInput();
```

**Comment by vadimdemedes** [comment]
You can try disabling [`isActive`](https://github.com/vadimdemedes/ink#isactive) option for each `useInput` hook, which should stop Ink from using stdin.
