### ISSUE TITLE
Duplicated Output

### ISSUE THREAD

**Issue by mAAdhaTTah** [vadimdemedes/ink#48]
Loving the concept of Ink but having some issues with the rendering. I'm seeing this duplicated output:

<img width="245" alt="menubar_and_bash" src="https://user-images.githubusercontent.com/4371429/34317150-2fddd508-e776-11e7-9c4a-1ecd2f6d3423.png">

Have you seen this before? Any idea what the issue could be? I'm not sure this is a bug, but I can't seem to nail down the cause. While I'm typing the answers to the questions, it works fine. It only starts to break when it renders the other parts of the UI.

Thanks for your help and happy holidays!

**Comment by mAAdhaTTah** [comment]
Playing around with this today, it appears to only happen when rendering multiline strings. So rendering:

```jsx
<div>{message}</div>
```

where `message` is a multiline string, using either template string or output from a `spawn`ed process. I'm working on producing an isolated reproducible case.

**Comment by mAAdhaTTah** [comment]
Isolated to a `log-update` issue: https://github.com/sindresorhus/log-update/issues/28

**Comment by Kikobeats** [comment]
Having the same issue using [Table](https://github.com/maticzav/ink-table) component with a dataset higher than `37`

**Comment by mAAdhaTTah** [comment]
Yeah.. I have to imagine this is a fairly low level issue. I personally have made zero progress here, unfortunately.

**Comment by vadimdemedes** [comment]
This bug indeed depends on terminal size. If output from your command is taller than terminal height, it can't be correctly rendered, unfortunately. That's the limitation of the environment Ink is in 🤷‍♂️

In Ink 2 there's a `<Static>` component which permanently flushes output of its children to terminal, which I believe should help most cases. For example, in Jest or AVA or any other test framework, there's a list of completed tests. This sort of thing will never ever fit into terminal's "viewport", so it's useful to use `<Static>` to flush those tests and forget about them:

```jsx
<Static>
	<Test key="test-1" title="Completed test #1"/>
	<Test key="test-2" title="Completed test #2"/>
	{/* ... */}
</Static>
```
