### ISSUE TITLE
my mac terminal show error when i start project 

### ISSUE THREAD

**Issue by fiqryq** [vadimdemedes/ink#485]
i cant run my project and get error like this  ``` sh: dist/cli.js: Permission denied ``` , I try using sudo but it's also not working, any advice?

![Screen Shot 2021-10-22 at 01 13 24](https://user-images.githubusercontent.com/25787603/138334091-6f125e1c-3a8e-4d86-ae4a-2fa641aea580.png)

**Comment by LitoMore** [comment]
Related to https://github.com/vadimdemedes/create-ink-app/pull/19

Before this fix merged, you could run `chmod +x dist/cli.js` manually.

**Comment by LitoMore** [comment]
@vadimdemedes BTW, I have some pull requests for bug fixing. Could you take a look?

https://github.com/vadimdemedes/create-ink-app/pulls

**Comment by fiqryq** [comment]
> Related to [vadimdemedes/create-ink-app#19](https://github.com/vadimdemedes/create-ink-app/pull/19)
> 
> Before this fix merged, you could run `chmod +x dist/cli.js` manually.

hoo I see , thanks
