### ISSUE TITLE
Newline is cannot be used inside Box - maybe add something like BoxNewline?

### ISSUE THREAD

**Issue by risenforces** [vadimdemedes/ink#487]
Hi!

My component renders something like that:

```tsx
<Box>
  <Text>Logs</Text>
  {/* Here I want one empty line */}
  <Text>{messages}</Text>
</Box>
```

First, I tried `Newline`, but it works bad inside `Box` (yeah, I saw the `Newline`'s docs)

So, I created `BoxNewline`:

```tsx
import { Text } from 'ink'
import React from 'react'

export const BoxNewline: React.FC<{ count?: number }> = ({ count = 1 }) => {
  const text = ' ' + '\n'.repeat(count - 1)
  return <Text>{text}</Text>
}
```

Maybe, I did something wrong? If I'm right, what do you think about adding this logic in `Newline` / adding `BoxNewline` to the library?

P.S. The `ink` is great tool, thanks! But I really miss the scrollable box feature from `blessed`

**Comment by risenforces** [comment]
Oops, my `BoxNewline` causes some wrong renders, for example, there are often disappearing characters...

**Comment by risenforces** [comment]
Now I use `<Box height={1} />` for this purposes.

**Comment by vadimdemedes** [comment]
`Newline` should be used only inside `<Text>`, not `<Box>`. But if `<Box height={1} />` works for you, that's good too.
