### ISSUE TITLE
Clear screen before exit

### ISSUE THREAD

**Issue by mordv** [vadimdemedes/ink#489]
Initially, I expected this to work: `waitUntilExit().then(clear);` but it doesn't, since `unmount()` [calls log.done()](https://github.com/vadimdemedes/ink/blob/d9b356aadbe5570682716e069e0656dce969a631/src/ink.tsx#L254)

I can hack that and use 
```ts
export const { clear } = render(<App />)
...
const { exit } = useApp();
useInput((_, { escape }) => {
  if (escape) {
    clear();
    exit();
  }
});
```
And if I want `ctrl+c` behave the same way:
```ts
  const { stdin } = useStdin();
  useLayoutEffect(() => {
    const listener = (input: string) => {
      if (input === ctrlC) {
        clear();
        exit();
      }
    };
    stdin.addListener(`data`, listener);
    return () => void stdin.removeListener(`data`, listener);
  });
```
That's where I get sad. Am I missing something? If not - can we add something like a flag `clearBeforeUnmount` to `render`'s options and use it [here](https://github.com/vadimdemedes/ink/blob/d9b356aadbe5570682716e069e0656dce969a631/src/ink.tsx#L254)?

**Comment by vadimdemedes** [comment]
Have you tried [`clear`](https://github.com/vadimdemedes/ink#clear) function?
