### ISSUE TITLE
react-devtools-core adds 14 MB to every installation using Ink

### ISSUE THREAD

**Issue by JamesHenry** [vadimdemedes/ink#491]
Hi @vadimdemedes,

Thank you so much for such an incredible package!

We've noticed that ink adds a lot of weight to the tool we want to use it for, and upon digging further into it, well over 80% of that weight (**14 MB**) comes exclusively from `react-devtools-core`, which is obviously completely unused by end users of tools which leverage ink at runtime.

Would you accept a PR which removes the direct dependency on `react-devtools-core` in favour of throwing a clear error if a developer tries to use the devtools without having first installed them? I think this trade off in favour of end users is well worth it.

Thanks again!

**Comment by vadimdemedes** [comment]
Hi! Yeah, I think that would be a good improvement, thank you!

**Comment by JamesHenry** [comment]
Hi @vadimdemedes just to set expectations here, in the interim we ended up going with a zero-framework solution which did not bring in any native dependencies.

I think the task would still make sense for someone to take on but as I am not yet an ink user it is unlikely I will have time to take it on myself any time soon.

Best of luck with your fantastic open-source work!

**Comment by vadimdemedes** [comment]
@JamesHenry No worries!
