### ISSUE TITLE
[Feature request] Table support

### ISSUE THREAD

**Issue by vitalics** [vadimdemedes/ink#495]
Hi All,

I would like to use tables in my CLI app like in the screenshot below,
This example generated via [CLI-table3 ](https://www.npmjs.com/package/cli-table3)library
![image](https://user-images.githubusercontent.com/8816260/148739199-47e471c4-bf79-44c3-856d-f2d0d94714b8.png)

My suggestion here is using common HTML Table approach 

Possible components:
- `Table` - common wrapper with general table settings (example: general spacing, dot styles, etc)
- `THead` - header wrapper tag
- `TBody` - table body wrapper
- `TRow` - table row, can be used in `THead` and `TBody` tags
- `TData` - table cell data, like text

**Comment by tvedtorama** [comment]
Why not use [ink-table](https://github.com/maticzav/ink-table)?
