### ISSUE TITLE
Is there vue alternative?

### ISSUE THREAD

**Issue by liudonghua123** [vadimdemedes/ink#496]
I like this package, it is really wonderful. However, I also used `vue` a lot, so I want to find a vue alternative like this. Or how can I reimplement it using vue? I am new to this package and `yoga`, I do not know where to start.

**Comment by vadimdemedes** [comment]
Ink is strongly tied to React and wouldn't exist without it, so unfortunately it's not a simple matter of adding support for another framework like Vue or even Preact.
