### ISSUE TITLE
Update required Node.js version to at least 12

### ISSUE THREAD

**Issue by loreanvictor** [vadimdemedes/ink#499]
Currently on the package [it is mentioned](https://github.com/vadimdemedes/ink/blob/763db800f6b93c0807b016c6dc1ac8cccef0a67b/package.json#L14-L16) that it is compatible with `node>=10`. However, just had an issue with a coworker running node `v10.12.0` which couldn't run an internal CLI tool based on ink, and resolved it by simply upgrading node. This was the issue that got resolved:

```bash
.../node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename
```

Perhaps the engine requirement should be bumped to `node>=10.24`?

**Comment by vadimdemedes** [comment]
Fixed in #543.
