### ISSUE TITLE
3.2.0 Emojis render with trailing spaces within Boxes

### ISSUE THREAD

**Issue by NikitaIT** [vadimdemedes/ink#505]
This again doesn't work. See https://github.com/vadimdemedes/ink/pull/444

Version: 3.2.0
Platform: Windows 10 (vs-code, powershell)

![image](https://user-images.githubusercontent.com/16810067/158066464-6c0dd618-a801-4391-b9d4-658e5bf5f9f5.png)

**Comment by lucas-labs** [comment]
I'm having the same issue, looks like a regression

![image](https://user-images.githubusercontent.com/12949236/193646403-f5d2f868-08c9-4bff-bc1c-a64df260cc1a.png)
