### ISSUE TITLE
All development is paused until Ukraine wins the war against russia

### ISSUE THREAD

**Issue by vadimdemedes** [vadimdemedes/ink#506]
If you'd like to support Ukraine to win this war sooner, donate to ["Come Back Alive" organization](https://www.comebackalive.in.ua/donate).

**Comment by vadimdemedes** [comment]
No.

**Comment by dustinlacewell** [comment]
Who's up for a community fork?

**Comment by zach-is-my-name** [comment]
In solidarity with Ink,  [Ink Solid](https://github.com/zach-is-my-name/ink-solid/discussions/1) is available for contributions until @vadimdemedes is able to resume... take care everyone... _long live peace, freedom, and open source collaboration..._

**Comment by vadimdemedes** [comment]
Hey folks, I'm going back to open source soon, so I just wanted to drop you a note that Ink will get updates soon. Thanks for everyone's understanding and patience, you're the best!
