### ISSUE TITLE
useInput keys not responding properly (ctrl, backspace, shift)

### ISSUE THREAD

**Issue by jrson83** [vadimdemedes/ink#512]
This is related to #409

There is something really wrong with the key detection.

### ctrl & tab

For me on both linux and windows, `key.ctrl` doesn't get detected at all, when pressing ctrl.

Instead when pressing `tab`, both `key.tab` and `key.ctrl` getting detected.

You can check with logging:

```js
useInput((input, key) => {
  console.log(key)
}

// output when pressing TAB
{
  upArrow: false,
  downArrow: false,
  leftArrow: false,
  rightArrow: false,
  pageDown: false,
  pageUp: false,
  return: false,
  escape: false,
  ctrl: true,
  shift: false,
  tab: true,
  backspace: false,
  delete: false,
  meta: false
}
```

### backspace & delete

`key.del` gets detected when pressing `del`. But when pressing `backspace` it does not detect `key.backspace`, but instead `key.del`.

```js
useInput((input, key) => {
  console.log(key)
}

// output when pressing BACKSPACE
{
  upArrow: false,
  downArrow: false,
  leftArrow: false,
  rightArrow: false,
  pageDown: false,
  pageUp: false,
  return: false,
  escape: false,
  ctrl: false,
  shift: false,
  tab: false,
  backspace: false,
  delete: true,
  meta: false
}
```

### shift

When pressing `shift` it does not get detected at all.

**Comment by manast** [comment]
Yeah it has a funny behaviour I just noticed this in MacOS. I could confirm this weird things:
- ```shift``` only gets to true if pressed together with a character, not with the arrows and not with any other key or alone.
- Pressing ```tab``` sets both ```tab``` and ```ctrl``` to true.
- Pressing ```ctrl```  alone is not detected, but together with other characters yes.
- Pressing ```alt``` by its own is not detected, however pressing alt+arrows it gets detected as ```meta```, however the arrows themselves are not detected :(.

Probably other stuff, I did not test everything...

**Comment by vadimdemedes** [comment]
Pushed https://github.com/vadimdemedes/ink/commit/26b83643f91855b407f39c2bec2fef1dbdede13b to stop enabling `ctrl` for <kbd>Tab</kbd> and detect arrow keys when pressed together with meta key.

**Comment by vadimdemedes** [comment]
Merged #576, so Ink should now parse keyboard the same as `readline` in Node.js would.

**Comment by mochienya** [comment]
the backspace being delete behavior is still there for me, I'm on NixOS with the kitty terminal, version 6.3.1 of library

**Comment by Zzzen** [comment]
> the backspace being delete behavior is still there for me, I'm on NixOS with the kitty terminal, version 6.3.1 of library

Same on mac with version 6.3.1 of library
