### ISSUE TITLE
Rendering an image - Recommended library/approach

### ISSUE THREAD

**Issue by goldbergyoni** [vadimdemedes/ink#514]
Kudos for the amazing work here.

I'd like to render an image, I know that there is no built-in component for this, any chance you can recommend a package that can do this, or how should I approach this? The only package I found is not supporting v3. Tried to use terminal image libs and render within Text but its base64 encoding was printed instead. Appreciate some guidance.

**Comment by Rxann** [comment]
Hi, there is an ink-image library! It is in the docs

**Comment by vadimdemedes** [comment]
@Rxann is right, there's [ink-image](https://github.com/kevva/ink-image), but it hasn't been update to support Ink 3. I'd suggest either submitting a pull request or forking and publishing your own package compatible with Ink 3.
