### ISSUE TITLE
dev tools components disappear after short time

### ISSUE THREAD

**Issue by matart15** [vadimdemedes/ink#518]
very simple component 
`render(<Text color="red">some text</Text>);`

when i run `DEV=true yarn cli` dev tools show `Text`. 
<img width="434" alt="Screen Shot 2022-05-27 at 20 28 00" src="https://user-images.githubusercontent.com/17027219/170691067-5d681459-c1d9-4ae7-a110-767f933cb890.png">

but after about 1 second it disappears.
<img width="796" alt="Screen Shot 2022-05-27 at 20 28 08" src="https://user-images.githubusercontent.com/17027219/170691108-8ce11104-01c0-4426-820e-42fe636e9d25.png">

What am i missing?

**Comment by vadimdemedes** [comment]
Not sure, it works for me. Closing until there are more details or reports from others.
