### ISSUE TITLE
Ink Solid in solidarity with Ink and its creator and principal author

### ISSUE THREAD

**Issue by zach-is-my-name** [vadimdemedes/ink#521]
We all hope @vadimdemedes is ok, along with anyone they know or share kinship in the conflict.  The intent of Ink Solid is to honor Ink and its creator while still progressing on the dream of rich, featureful CLI's built with the ease of creating a React web app.  Hopefully, Vadim and Ink come back soon, [til then feel free contribute to ideas to bootstrapping Ink Solid](https://github.com/zach-is-my-name/ink-solid) 

Long live Peace, Freedom, and Open Source Collaboration

**Comment by vadimdemedes** [comment]
Thank you, @zach-is-my-name, you're so kind ❤️

**Comment by vadimdemedes** [comment]
Thanks @zach-is-my-name for the support while I was gone! Let me know if you're still interested in maintaining a Solid fork of Ink and I'll gladly add link to it in readme.
