### ISSUE TITLE
`Newline` takes up two lines

### ISSUE THREAD

**Issue by NSExceptional** [vadimdemedes/ink#522]
`Newline` inserts _two_ blank lines, not one, when created like `<Newline />` or `<Newline count={1} />.

I think the issue is that it ends up taking up the line you put it on as well as the next one, somehow. Or am I using it wrong?

**Comment by NSExceptional** [comment]
Just saw the "must be used within `Text` components` note, shit. That's not what I thought it was for. Why is that a requirement?

**Comment by vadimdemedes** [comment]
Because `Newline` is a text underneath (`\n`), so it's required for it to be inside other `Text` component.

**Comment by ericbiewener** [comment]
This _is_ an issue even when one is using it inside a `<Text>` component correctly.
