### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by richburdon** [vadimdemedes/ink#526]
Update to React v18

```
unmet peer react@^17.0.2: found 18.2.0
```

**Comment by vadimdemedes** [comment]
This is planned for the next major release.

**Comment by SimenB** [comment]
Should these be set to `16.x || 17.x` or something while we're waiting for v18 support? https://github.com/vadimdemedes/ink/blob/ba6b7ea0fd749829c2b612106213cc67a6271267/package.json#L102-L103

**Comment by sindresorhus** [comment]
https://github.com/vadimdemedes/ink/releases/tag/v4.0.0
