### ISSUE TITLE
Terminal cleanup code breaks correct app behavior

### ISSUE THREAD

**Issue by rzcoder** [vadimdemedes/ink#549]
The correct behavior for a full-screen CLI application is to restore the state of the terminal to what it was before the application was called. This can be achieved with `stdout.write("\x1b[?1049h")` and `stdout.write("\x1b[?1049l)` sequences.

However, the code below breaks this behavior by preemptively clearing the console.

https://github.com/vadimdemedes/ink/blob/93b7e2dab5eea4cb2b6bb876d4af30a9c9e53d05/src/ink.tsx#L152-L157

**Comment by vadimdemedes** [comment]
This code supports re-rendering output that's taller than a terminal window. Without it, only lines that are currently visible will be re-rendered and lines that don't fit into the terminal window won't.

I think Jest was (not sure about today) doing this trick as well to work around this limitation, which is where I borrowed it from.

I know it's not ideal, but I don't know any other way to re-render the entire output, including the one that doesn't fit into the terminal window.
