### ISSUE TITLE
TypeScript doesn't find type declarations in v4.0.0

### ISSUE THREAD

**Issue by AlCalzone** [vadimdemedes/ink#552]
I believe `package.json` must be changed in one of the following ways:

```diff
	"type": "module",
-	"exports": {
-		"types": "./build/index.d.ts",
-		"default": "./build/index.js"
-	},
+	"module": "./build/index.js",
+	"types": "./build/index.d.ts",
```
(tested, works) or
```diff
	"type": "module",
	"exports": {
-		"types": "./build/index.d.ts",
-		"default": "./build/index.js"
+		".": {
+			"types": "./build/index.d.ts",
+			"default": "./build/index.js"
+		}
	},
```
according to https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing

**Comment by AlCalzone** [comment]
typescript 4.8 in VSCode?

**Comment by AlCalzone** [comment]
Ok, so I did this
```
npm init -y
npm i typescript ink-repro
echo 'import {render} from "ink"' > index.mts
code index.mts
```

and got:
![grafik](https://user-images.githubusercontent.com/17641229/222525474-70874752-faec-496f-804c-160afd2d2571.png)

It does start working after I add a tsconfig with the corresponding `module` and `moduleResolution` flags (or change it in an existing project).
I'd argue though that adding two lines (first diff) is a small price to pay to allow consumers not to change their config, causing other issues down the line.

**Comment by maxijonson** [comment]
I have the same issue. 

@sindresorhus Not sure what "issue with your build tool" means if all other packages work just fine. 

I'm new to Ink, is it ESM only? (similar to how the latest versions of Chalk are). @AlCalzone  seems to be using "mts" files. Changing my `module` would be more of a hassle and if Ink is now ESM only, I don't quite understand packages like Chalk that force ESM to their consumers 😅 But I'm not here to debate build practices, I'd just like a solution that doesn't break the rest of my development workflow.

Furthermore, on NPM, there seem to be no included type definitions, hence the "DT" logo, suggesting a @types package, but the package has a deprecation notice stating it's a stub. However, I can confirm that they are present in my node_modules, but I don't understand why TypeScript (and NPM) isn't seeing the declarations. Again, Ink is the only package in my project with this kind of issue.

**Comment by sindresorhus** [comment]
> I'm new to Ink, is it ESM only?

Yes: https://github.com/vadimdemedes/ink/blob/a53daa328200eff951ae9da7d8d3e22f507bd530/package.json#L12

**Comment by AlCalzone** [comment]
@maxijonson You don't actually have to use mts files, but typescript's `module` and `moduleResolution` fields must be set to `node16`.

Alternatively you could use `yarn patch` to edit the package.json of ink like my first diff, which also works and is a less invasive measure than the tsconfig change.

I understand why so many packages are being converted to ESM, I just don't understand why it has to be in the most breaking way possible 🤷🏻‍♂️

**Comment by maxijonson** [comment]
Thanks, I followed what you said and my project is now ESM 😅 

I only had an issue with `useStdoutDimensions` not being able to be used because "require() of Ink from useStdoutDimensions is not supported" and I don't feel like I know enough about ESM errors to open an issue, in case it's just my project. Hopefully, I won't have any more compatibility issues!

**Comment by AlCalzone** [comment]
Same. I just copied that hook into my project and compiled it myself.

**Comment by sindresorhus** [comment]
https://github.com/vadimdemedes/ink/pull/553#issuecomment-1464867958

**Comment by kevinwolfcr** [comment]
@sindresorhus I am having the same error, but only within VScode, not by running the compiler. This is my `tsconfig.json`:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "composite": false,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "react",
    "lib": ["ES2022"],
    "module": "node16",
    "moduleResolution": "node16",
    "noEmit": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "preserveWatchOutput": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "ES2022"
  },
  "ts-node": {
    "transpileOnly": true,
    "files": true,
    "experimentalResolver": true
  },
  "include": ["./src"],
  "exclude": ["./node_modules"]
}
```

**Comment by ericbiewener** [comment]
Frustrating that the `npx create-ink-app --typescript` command doesn't provide a TSConfig file that lets the types work. For those who arrived here after using that command, the first sentence in [this comment](https://github.com/vadimdemedes/ink/issues/552#issuecomment-1455039790) should fix it.

**Comment by coreyward** [comment]
Even if your project is already ESM with `type: "module"`, ink types don't seem to work. I don't have issues with any other package (we're using over 100), just ink. 🤷 

> Cannot find module 'ink' or its corresponding type declarations.

Could have something to do with the fact that the `build/index.d.ts` file referenced by `package.json` is pointing to the wrong paths (*.js instead of the adjacent *.d.ts, or as I typically see, extensionless paths):

```ts
export type { RenderOptions, Instance } from './render.js';
export { default as render } from './render.js';
export type { Props as BoxProps } from './components/Box.js';
export { default as Box } from './components/Box.js';
export type { Props as TextProps } from './components/Text.js';
export { default as Text } from './components/Text.js';
export type { Props as AppProps } from './components/AppContext.js';
export type { Props as StdinProps } from './components/StdinContext.js';
export type { Props as StdoutProps } from './components/StdoutContext.js';
export type { Props as StderrProps } from './components/StderrContext.js';
export type { Props as StaticProps } from './components/Static.js';
export { default as Static } from './components/Static.js';
export type { Props as TransformProps } from './components/Transform.js';
export { default as Transform } from './components/Transform.js';
export type { Props as NewlineProps } from './components/Newline.js';
export { default as Newline } from './components/Newline.js';
export { default as Spacer } from './components/Spacer.js';
export type { Key } from './hooks/use-input.js';
export { default as useInput } from './hooks/use-input.js';
export { default as useApp } from './hooks/use-app.js';
export { default as useStdin } from './hooks/use-stdin.js';
export { default as useStdout } from './hooks/use-stdout.js';
export { default as useStderr } from './hooks/use-stderr.js';
export { default as useFocus } from './hooks/use-focus.js';
export { default as useFocusManager } from './hooks/use-focus-manager.js';
export { default as measureElement } from './measure-element.js';
export type { DOMElement } from './dom.js';
```

**Comment by sindresorhus** [comment]
> Even if your project is already ESM with type: "module", ink types don't seem to work.

This is not enough to make a proper ESM project when using TypeScript. I have documented the required steps: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm

> Editing package.json to add types: "./build/index.d.ts" works for me in a Next app.

`"types": "./build/index.d.ts"` will just paper over the real problem and it may stop working at any time.
