### ISSUE TITLE
Document all exports

### ISSUE THREAD

**Issue by saadq** [vadimdemedes/ink#56]
Hey, great work with this package.

I had been planning on writing some Flow type definitions, but I noticed that some exports aren't documented in the README. You already have an open issue for [`Indent`](https://github.com/vadimdemedes/ink/issues/51), but there's also [`StringComponent`](https://github.com/vadimdemedes/ink/blob/master/index.js#L13), [`build`](https://github.com/vadimdemedes/ink/blob/master/index.js#L25), and [`diff`](https://github.com/vadimdemedes/ink/blob/master/index.js#L26). It would be great if these could be documented just to know whether I should include them in the type definitions or not.

Thanks again for `ink`!

**Comment by vadimdemedes** [comment]
`StringComponent`, `build` and `diff` are private (internal) functions, they shouldn't be used by users of Ink.

P.S. Glad you like it!
