### ISSUE TITLE
Lifecycle methods and Context API from React 16.3

### ISSUE THREAD

**Issue by benwiley4000** [vadimdemedes/ink#57]
The official React 16.3 release is still upcoming, but there are several highly anticipated features whose implementation could start now: https://medium.com/@baphemot/whats-new-in-react-16-3-d2c9b7b6193b

Particularly the new Context API, which could be built on top of the existing API for now.

Also important to implement will be `static getDerivedStateFromProps`, which replaces ~`componentDidMount`~ `componentWillReceiveProps` (and is allegedly necessary for async rendering).

**Comment by kylealwyn** [comment]
Small edit: `static getDerivedStateFromProps` will be replacing `componentWillReceiveProps`, not `componentDidMount`

**Comment by benwiley4000** [comment]
@kylealwyn you're right, my mistake! Well, I thought `componentDidMount` was faster to type, and maybe no one would notice... 😄

**Comment by jdeniau** [comment]
Apparently, ink 2.x will be a "real" implementation of react, with react-reconcilier, so all react features will be "built-in"

**Comment by rozzzly** [comment]
Hurray for flexboxes!!

**Comment by benwiley4000** [comment]
@vadimdemedes I noticed v2 has several releases. What's the stability of the v2 API - can I start using it and should I expect anything to change much?

**Comment by vadimdemedes** [comment]
@benwiley4000 I don't expect major changes at this point to the API, but just to be safe I'd stick to `render(<JSX/>)` only for now. Full v2 release should be out very soon.

**Comment by vadimdemedes** [comment]
Closing as Ink 2 uses React directly, so Ink doesn't need to reimplement these.
