### ISSUE TITLE
Custom border style does not work as per the documentation

### ISSUE THREAD

**Issue by nathan-fiscaletti** [vadimdemedes/ink#578]
In the [documentation for `borderStyle`](https://github.com/vadimdemedes/ink#borderstyle), it's stated that you can add a custom border-style to the `Box` component.

> Alternatively, pass a custom border style like so:
> 
> ```jsx
> <Box
>     	borderStyle={{
> 		topLeft: '↘',
> 		top: '↓',
> 		topRight: '↙',
> 		left: '→',
> 		bottomLeft: '↗',
> 		bottom: '↑',
> 		bottomRight: '↖',
> 		right: '←'
> 	}}
> >
> 	<Text>Custom</Text>
> </Box>
> ```

However, when you attempt to run this you get the following error:
> ```
> Type '{ readonly topLeft: "↘"; readonly top: "↓"; readonly topRight: "↙"; readonly left: "→"; readonly bottomLeft: "↗"; readonly bottom: "↑"; readonly bottomRight: "↖"; readonly right: "←"; }' is not assignable to type 'keyof Boxes'.ts(2322)
>
> styles.d.ts(114, 14): The expected type comes from property 'borderStyle' which is declared here on type 'IntrinsicAttributes & Except<Styles, "textWrap"> & { readonly columnGap?: number; readonly rowGap?: number; readonly gap?: number; readonly margin?: number; ... 7 more ...; readonly overflowY?: "visible" | "hidden"; } & { ...; } & RefAttributes<...>'
> ```

I'm not sure if i just have something wrong with my configuration.

**Comment by vadimdemedes** [comment]
Support for `borderStyle` wasn't released yet, just merged to `master`. Will publish a release in a moment.

**Comment by vadimdemedes** [comment]
Released [4.2.0](https://github.com/vadimdemedes/ink/releases/tag/v4.2.0). When you update to this version, you should be able to customize the border style.
