### ISSUE TITLE
"space-evenly" value is missing for justifyContent property of the Box Component 

### ISSUE THREAD

**Issue by kasra0** [vadimdemedes/ink#613]
Hi,

It seams that space-evenly is missing. Indeed we have  
readonly justifyContent?: 'flex-start' | 'flex-end' | 'space-between' | 'space-around' | 'center';

Is it possible to add support for "space-evenly" to be aligned with CSS flexbox specs ?

Thanks.

**Comment by vadimdemedes** [comment]
If [Yoga](https://yogalayout.com) supports it, then it should be possible.

**Comment by kasra0** [comment]
Yes Yoga supports [space-evenly](https://yogalayout.com/docs/justify-content)

**Comment by vadimdemedes** [comment]
Feel free to open a PR then 👍

**Comment by skirianov** [comment]
@vadimdemedes mind if I take this one?

**Comment by vadimdemedes** [comment]
@skirianov Sure, go ahead.
