### ISSUE TITLE
Please fix the issue that TS can't find ink's types

### ISSUE THREAD

**Issue by alengYuan** [vadimdemedes/ink#620]
I use ink (4.3.1) in VSCode (1.81.1), and TS says that `Cannot find module 'ink' or its corresponding type declarations.ts(2307)`.

Please add field `types` in `package.json` of ink, just like this:

```json
{
    "name": "ink",
    ...
    "types": "build/",
    ...
}
```

It would fix the issue.

**Comment by sindresorhus** [comment]
Duplicate of #552
