### ISSUE TITLE
isUpdate is confusing

### ISSUE THREAD

**Issue by chinanf-boy** [vadimdemedes/ink#63]
https://github.com/vadimdemedes/ink/blob/master/lib/diff.js#L133

``` js
let isUpdate = true;
// you make the update call isUpdate is ok
```

https://github.com/vadimdemedes/ink/blob/master/lib/diff.js#L178

``` js
return isUpdate ? prevNode : nextNode;
// but isUpdate == true ?  prev
```

If the `Vnode` is need to `Update` , should return `nextNode`, no `prevNode`

May you can change `isUpdate` to > `isPrev`

**Comment by vadimdemedes** [comment]
`prevNode` is actually a current node and it should be updated in order to update existing components that are being rendered to terminal. `nextNode` should be rendered (`return`ed) only when there was no previous node to compare to. It happens on initial render, for example.

**Comment by chinanf-boy** [comment]
# Ok , I got it, Thanks a lot 😊
