### ISSUE TITLE
Bun support

### ISSUE THREAD

**Issue by DaniGuardiola** [vadimdemedes/ink#636]
I want to use ink with Bun. In my testing, the basic rendering seems to work, but useInput does not, it simply doesn't register the inputs, which is a show-stopper.

**Comment by sindresorhus** [comment]
Bun recommends opening issues on [their](https://github.com/oven-sh/bun) issue tracker for compatibility issues. Their goal is full Node.js compatibility. Comment the issue link here for future reference.

**Comment by DaniGuardiola** [comment]
https://github.com/oven-sh/bun/issues/6862
