### ISSUE TITLE
Friendly request to include tailwind-ink in the README

### ISSUE THREAD

**Issue by DaniGuardiola** [vadimdemedes/ink#637]
I just published this package: https://github.com/DaniGuardiola/tailwind-ink

Essentially, Tailwind CSS but for Ink :)

I've put a lot of effort into it because I love both of these technologies and I'm pretty happy with the result. I would love it if it could be referenced somewhere in the README.

Thank you! <3

**Comment by vadimdemedes** [comment]
That's pretty cool! Feel free to open the PR to add your project to https://github.com/vadimdemedes/ink#useful-components.
