### ISSUE TITLE
When bundling with esbuild, `isRawModeSupported` is always false

### ISSUE THREAD

**Issue by isaacroldan** [vadimdemedes/ink#646]
Hi!

I'm working with the Shopify CLI and we are trying to bundle our dependencies to reduce the node_modules footprint of our users.
However, when including `ink` in the bundle we've encountered a couple issues:

We solved the first one by marking `react-devtools-core` and `yoga-wasm-web` as external 👌 

The second one is about ink behaviour: When bundled, `isRawModeSupported` will always return `false`
Any idea why this happens? Or how to fix it?

Thanks!

**Comment by sindresorhus** [comment]
This would be a question for the bundler you're using. `isRawModeSupported` is just a facade for `stdin.isTTY`, which is a Node.js API.
