### ISSUE TITLE
Rename `<Text>` component to `<Color>`

### ISSUE THREAD

**Issue by sindresorhus** [vadimdemedes/ink#65]
It makes it sound like it can only color text, but it works on any Ink component, so you could use it to color [`ink-box`](https://github.com/sindresorhus/ink-box), for example.

We can add separate components for the existing `<Text bold>` and `<Text underline>` styling: `<Bold>` and `<Underline>`.

**Comment by karaggeorge** [comment]
I can work on a PR for this if you want

**Comment by sindresorhus** [comment]
@karaggeorge Sure :)

**Comment by karaggeorge** [comment]
I think this can be closed now 😄 https://github.com/vadimdemedes/ink/pull/69
