### ISSUE TITLE
📏 How to make the box automatically shrink to the size of the content?

### ISSUE THREAD

**Issue by okineadev** [vadimdemedes/ink#686]
I decided to switch to `ink` and use it instead of `boxen`, but I have a problem - the box expands to the size of the terminal and not shrinks to the size of the content

![image](https://github.com/user-attachments/assets/5507bb01-b796-4edd-b150-5163335cfaa2)

In the first example I use `ink` and in the second I use `boxen`

As you can see, `boxen` automatically compresses the box to the width of the longest line in the text

How to make `ink` compress the box to the size of the content?

**Comment by okineadev** [comment]
I have temporary solution!

```typescript
import widestLine from 'widest-line'

// @ts-expect-error
const DynamicBox = ({ children, ...props }) => {
	const longestLine = widestLine(children.toString())
	return (
		<Box {...props} width={longestLine}>
			{children}
		</Box>
	)
}
```

Then use `<DynamicBox>` just like `<Box>`

**Comment by okineadev** [comment]
Again the problem is, the component I wrote above calculates the width incorrectly if `<DynamicBox>` has at least 2 child `<Box>`

<img alt="screenshot" src="https://github.com/user-attachments/assets/aebda2a7-426c-45f1-973b-5e1fe3c264b1" width="260" align="left">

This is because children = `[object Object],[object Object]`, and because of this I cannot get the length of the entire text (I expected the `.toString()` method to return the text from all elements entirely)

Please help, I will be very grateful

**Comment by mAAdhaTTah** [comment]
@okineadev Without looking at your implementation, my expectation would be that you could resolve this by styling it properly, rather than doing a calculation. Everything in Ink is based on Flexbox, so you should be able to make it work by doing that correctly.

**Comment by okineadev** [comment]
> @okineadev Without looking at your implementation, my expectation would be that you could resolve this by styling it properly, rather than doing a calculation. Everything in Ink is based on Flexbox, so you should be able to make it work by doing that correctly.

How?

**Comment by mAAdhaTTah** [comment]
Couple of caveats:

1. This is obviously a web implementation, so not 100% sure it'll translate.
2. Web support `width: min-content` which would be a simpler solution here

However, proposed solution is [here](https://codesandbox.io/p/sandbox/t7lr78). Basic idea is you have a box that's `flex-direction: row`, then the first child is `flex-direction: column` and `flex-grow: 0`.  That column width with thus only grow to fill the space needed by its content.

Again, haven't tested on Ink itself so ymmv, but that's the idea.

**Comment by okineadev** [comment]
Fixed with `alignSelf="flex-start"` !

Thanks
