### ISSUE TITLE
Is ImportJsx required?

### ISSUE THREAD

**Issue by Flaque** [vadimdemedes/ink#77]
In the [yeoman generator](https://github.com/vadimdemedes/generator-ink-cli/blob/333e092d4536a9b8ce7694a2375146ee16bb6de0/app/templates/cli.js#L4), `importJsx` is used to require the `ui.js` file. 

From the `ui.js` file, is that needed to import and use locally defined components? (ones not from an npm package)

**Comment by sindresorhus** [comment]
You need to transpile the JSX syntax somehow. It's up to you how to do that. Either with `import-jsx` or a prepublish-step using Babel.
