### ISSUE TITLE
Full screen layouts

### ISSUE THREAD

**Issue by danny-waite** [vadimdemedes/ink#78]
I'm looking to build some full screen layouts, that contain multiple section, much in the same way that react-blessed makes possible with boxes.  I note the following https://github.com/vadimdemedes/ink/issues/5 that seems promising but I wondered how/if people are doing this with the current feature set?

Great project, loving working with ink.

**Comment by vadimdemedes** [comment]
It's a complicated problem, I'm still working on it, so I can't promise any ETAs. But that's definitely something that should be possible in future.

> Great project, loving working with ink.

❤️

**Comment by vadimdemedes** [comment]
It's now possible to get available space for components, but I'd still wouldn't recommend using it for anything complex. It's a good fit for simple things like progress bars, etc. If you need a full blown fullscreen CLI, I'd recommend going with `react-blessed`.
