### ISSUE TITLE
Error importing ink-spinner, ink-table, et al using 0.5.0

### ISSUE THREAD

**Issue by kellyi** [vadimdemedes/ink#79]
Thanks for creating this library! I've been trying it out a bit and while using version 0.5.0 I kept encountering this error when using the Spinner, Table, and Select components:

```
throw new TypeError(`Expected component to be a function, but received ${typeof component}. You may have forgotten to export a component.`);
```

Downgrading to 0.4.1 enabled each to work, though.

**Comment by vadimdemedes** [comment]
I accepted all the PRs by awesome people who upgraded these components to 0.5.0. Should be good now!

I didn't have time to write release notes for 0.5.0, will do that soon. Definitely taking the blame here!
