### ISSUE TITLE
Extra redundant new line at end of render

### ISSUE THREAD

**Issue by aicioara** [vadimdemedes/ink#85]
When rendering the app to the terminal, there is an extra redundant new line at end of render which is not occupied by anything. I could be doing something wrong, I am not quite sure.

To reproduce:

```bash
yo ink-cli
node cli.js
```

Expected:

```
$ node cli.js 
I love Ink
```

Actual: having an additional new line at the bottom of the terminal that is not being used

```
$ node cli.js 
I love Ink

```

**Comment by aicioara** [comment]
I have been looking into this a bit more. This is more pronounced with `div`s. Take for instance the following examples

```es
render() {
    return <Color red> Hello World </Color>
}
```

vs

```es
render() {
    return <div>
        <Color red> Hello World </Color>
    </div>
}
```

vs

```es
render() {
    return <div>
        <div>
            <Color red> Hello World </Color>
        </div>
    </div>
}
```

I can possibly open a PR for this, but wanted to first check if this is the desired behavior?

**Comment by vadimdemedes** [comment]
You are right, it comes from `log-update` here: https://github.com/sindresorhus/log-update/blob/master/index.js#L34. It's needed, so that terminal prompt doesn't end up on the same line with your CLI output.
