### ISSUE TITLE
NodeJS hello world example?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [vadimdemedes/ink#91]
I'm just starting to play with this. I'm trying to find the shortest way to run the example in your Readme.

I don't have a web stack, so I don't need webpack or a compilation step.

I copy https://github.com/vadimdemedes/ink#usage into a file called index.jsx, and then install babel-cli and transform-react-jsx, and do
 
```babel --plugins transform-react-jsx index.jsx```

I get

```
/node_modules/ink/lib/diff.js:17
const getProps = vnode => Object.assign({}, vnode.component.defaultProps, vnode.props);
                                                           ^

TypeError: Cannot read property 'defaultProps' of undefined
    at getProps (/node_modules/ink/lib/diff.js:17:60)
    at mount (/node_modules/ink/lib/diff.js:28:16)
    at diff (/node_modules/ink/lib/diff.js:136:3)
    at build (/node_modules/ink/lib/renderer.js:10:9)
    at Renderer.update (/node_modules/ink/lib/renderer.js:25:20)
    at exports.render (/node_modules/ink/index.js:59:14)
    at Object.<anonymous> (/index2.js:36:1)
```

**Comment by GeoffreyPlitt** [comment]
@vadimdemedes Am I misinterpreting the demo/animation in the README, or does this work running in NodeJS rendering an app experience into Terminal/Console, i.e. STDOUT? Or is this mainly a browser technology?

**Comment by vadimdemedes** [comment]
I copied the code from "Usage" and completed a "Getting Started" step (https://github.com/vadimdemedes/ink#getting-started), it works for me. Could you try again and see if it works?

**Comment by GeoffreyPlitt** [comment]
@vadimdemedes Can you post your code? The example uses JSX, which doesn't really work with NodeJS out of the box. I followed your instructions and get the following error, which is expected.

```
$ node index.js 
/Users/giro/Desktop/t/index.js:14
			<Color green>
			^

SyntaxError: Unexpected token <
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
Geoffs-MacBook-Pro-3:t giro$ 
```

Very curious to see your actual code if you got it working in console.

**Comment by egoarka** [comment]
@GeoffreyPlitt 
Actually, I had the same problem.
It should work with [babel node](https://babeljs.io/docs/en/next/babel-node.html)
if you still get struggle, pull this [package.json](https://gist.github.com/egoarka/37734765b4f5ea56e6303fc647287e71) and type in console
`npm install && npx babel-node index.js`
don't forget to create index.js and type your code there
hope it helps you :)

**Comment by GeoffreyPlitt** [comment]
@egoarka Did everything you said. Used your package.json and installed npx.

My index.js is:
```
const {h} = require('ink');

const Demo = () => <div/>;```

I do `npm install && npx babel-node index.js```, and there is no output to console.

**Comment by egoarka** [comment]
@GeoffreyPlitt yes, it's apparently; `<div />` renders to blank string, you should provide some text, and *render* it e.g. 

`
const {h, render} = require('ink');

const Demo = () => <div>hello world</div>;
render(<Demo />);
`

**Comment by GeoffreyPlitt** [comment]
That worked, thanks!
