### ISSUE TITLE
Proposal: add clear option to unmount

### ISSUE THREAD

**Issue by Leko** [vadimdemedes/ink#94]
Hi there.
I propose to add `clear` option to unmount() to clear ink output.

I would like to build a part of the CLI application with ink.

Example:

```js
console.log("xxx");
const unmount = render(<div>yyy</div>);
unmount({ clear: false });
console.log("zzz");
```

Expected behavior (clear=false, by default):

```
$ node clear.js
xxx
yyy

zzz
```

Expected behavior (clear=true):

```
$ node clear.js
xxx
zzz
```

How about it?

**Comment by vadimdemedes** [comment]
Could you explain the use case for it? Where would it be useful?

**Comment by jasonkuhrt** [comment]
Was looking for this too. Building a terminal app that toggles between UI (handled by ink) and logs (regular stream piping from child process to stdout). when user toggles between two views, would like the UI to be cleared, not just unmounted.

**Comment by jasonkuhrt** [comment]
Workaround for us, so far, was something like this:

```ts
          await new Promise(resolve =>
            readline.cursorTo(process.stdout, 0, 0, resolve)
          )
          await new Promise(resolve =>
            readline.clearScreenDown(process.stdout, resolve)
          )
          await new Promise(resolve =>
            readline.clearLine(process.stdout, 0, resolve)
          )
```
