### ISSUE TITLE
Proposal: Add an option to disable default "escape" behavior

### ISSUE THREAD

**Issue by WalterWeidner** [vadimdemedes/ink#95]
I would like to use the escape key to return to top level menus in my CLI tool. The default escape behavior, however, ends the process by default.

Could we make this configurable? 

The fix is pretty simple here: [https://github.com/vadimdemedes/ink/blob/master/index.js#L64](https://github.com/vadimdemedes/ink/blob/master/index.js#L64)

For example:
```		
if ((key.name === 'escape' && !options.exitOnEscape) || (key.ctrl && key.name === 'c')) {
	exit(); // eslint-disable-line no-use-before-define
}
```

**Comment by vadimdemedes** [comment]
Agree, I imagine this behavior could be annoying, I use only Ctrl+C to exit the process myself.

**Comment by rstacruz** [comment]
I'd be very interested to have this option, too! I keep on pressing escape by mistake.

**Comment by Anifacted** [comment]
In case you need a workaround: This can be hacked by changing the name of the `key` object on the fly. In your keypress handler:

```js

process.stdin.on("keypress", (name, key) => {
  key.name = "__PREVENT_ESCAPE__";

  // your logic for handling ESC events...
});
```

It works because your handler runs before Ink's handler, but it's a dirty hack ;)

**Comment by Anifacted** [comment]
It still has a bit of a delay, though :/

**Comment by vadimdemedes** [comment]
Closing as Ink 2 won't have this "quit via escape" functionality at all.
