### ISSUE TITLE
React set state not working properly

### ISSUE THREAD

**Issue by Rockson** [vadimdemedes/ink#97]
```
class App extends React.Component {
  state = {
    foo: {
      a: 1,
      b: 1
    }
  };

  componentDidMount() {
    this.setState(state => ({
      hello: { ...state.foo, a: state.foo.a + 1 }
    }));
    this.setState(state => ({
      hello: { ...state.foo, b: state.foo.b + 1 }
    }));
  }

  render() {
    const { a, b } = this.state.foo;
    return (
      <div>
        {a} - {b}
      </div>
    );
  }
}
```

This code should print 2 - 2, instead it prints 1 - 2 because in the second setState `...state.foo` is `{a: 1, b: 1}` so it doesn't update with the previous one.
With the actual version of react this problem doesn't exists

[Here is the sandbox](https://codesandbox.io/s/l5rxkj3jrq)

**Comment by jdeniau** [comment]
Ink in it's actual version (0.x) is "inspired" by react, but not using react itself.

The v2 version, currently in beta, does use react and react-reconcilier, so I think it will work fine ;)

**Comment by Rockson** [comment]
Thanks for the good news :blush:

**Comment by jdeniau** [comment]
@vadimdemedes ink-tab is already ready for it 😉

https://github.com/jdeniau/ink-tab/blob/next/package.json#L27

**Comment by vadimdemedes** [comment]
@jdeniau Awesome!

**Comment by vadimdemedes** [comment]
Closing, as Ink 2 uses React directly, so it shouldn't be a problem anymore.
